### ISSUE TITLE
What is Registration Key in Sign Up page ?

### ISSUE THREAD

**Issue by rahul799** [conbench/conbench#105]
I have done a local setup of conbench, and the flask app is working fine, but whenever I am trying to register myself on the sign-up page, it asks for a registration key. I can't find anything about that in the README. Would you please let me know how I can get the key? Thank you.

**Comment by dianaclarke** [comment]
Good question. I should document that at some point.

The registration key currently defaults to `Benchmarking2021`:

    https://github.com/ursacomputing/conbench/blob/main/conbench/config.py#L15

But you can also override that with an env var:

    export REGISTRATION_KEY=WelcomeCode
    
The registration key is a secret used to prevent benchmark viewers from creating accounts, as they don't need to. The results are public. Only benchmark publishers need a valid conbench account to `POST` benchmark results to the Conbench API.

**Comment by rahul799** [comment]
Thanks a lot @dianaclarke for resolving my issue.
