### ISSUE TITLE
legacy conbench library: allow submission of both results and error

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1073]
Today when calling `conbench.record()` in the legacy `conbench` library, we suppress POSTing result data if there was an error:
https://github.com/conbench/conbench/blob/5393917be45cb2703e5997d2c73b5cf131e2935b/conbench/runner.py#L309-L317
But these days, the server can handle both keys. We should allow clients to be able to POST stats if there's also an error.

**Comment by jgehrcke** [comment]
Cool. I think it would be important to write a few words here about the use case that was 'broken by this', or that lacked this feature. 

> But these days, the server can handle both keys.

Can you clarify what changed, which are those two keys that we refer to here? 

Does this relate to the discussion in https://github.com/conbench/conbench/issues/813#issuecomment-1458624021?

**Comment by austin3dickey** [comment]
I added a lot more history to the PR: https://github.com/conbench/conbench/pull/1074#issuecomment-1502058137

In terms of a use case this would power: basically, one project is interested in storing how long a benchmark ran before the error occurred. This data of course is "incomparable" to non-errored results, but we already protect for that in the history queries.
