### ISSUE TITLE
api/compare: Separate comparison dict into baseline, contender, and analysis sub-dicts

### ISSUE THREAD

**Issue by alistaire47** [conbench/conbench#1091]
Split out of #1075 to keep PRs tidy and small. In `/api/compare/benchmark-results` and `/api/compare/runs/`, clarify the comparison dict by separating keys into `baseline` (raw info), `contender` (raw info), and `analyses` sub-dicts

**Comment by jgehrcke** [comment]
I like that! As indicated in https://github.com/conbench/conbench/pull/1114#pullrequestreview-1384888406 I think it will be valuable to have a per-method string identifier, such as `lookback_z_score` and `pairwise`; we can then re-use these identifiers across the code base and across various JSON schemas, and each identifier directly corresponds to a specific method that can be documented.

Roughly:
```json
{
"analysis": {
    "lookback_z_score": {},
    "pairwise": {}
  }
}
```
