### ISSUE TITLE
DB schema: do not use user-given data in primary key (insert order invariant)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1139]
Follow-up from #789 and #1138.

**Comment by austin3dickey** [comment]
This makes sense to me, but it will require some coordination with clients (and our client libraries). Most clients create a Run with a client-generated ID before posting results to that Run.

Example: Velox generates a unique run ID by using the GHA run number:
https://github.com/facebookincubator/velox/blob/9a07acb5bcac718a5cdb40ae914f4a40bf0c459c/.github/workflows/conbench_upload.yml#L118

Probably we can simply change all client logic to use the primary key that's returned from the first Run POST. But we'll have to scope out how much work that will take.

**Comment by jgehrcke** [comment]
Not everything might be obvious, buuut: most sane systems do not let the user set the primary key, and most sane systems also do not leak/expose the primary key.

A primary key most of the times is an implementation detail. An important one.

It is important to be able to _change the primary key_ (as we see here), _without breaking user's references to entities_ (as we also see here).

> Most clients create a Run with a client-generated ID before posting results to that Run.

I think we could even keep everything compatible with current client logic, just not use the user-facing "run ID" as primary key. Not sure if we want that though, need to think this through a tiny little more.

**Comment by austin3dickey** [comment]
Ah, I see what you mean. Yes, my main point was just that "we want users to be able to associate a POSTed benchmark result with an existing run" even after making this change. And depending on how we make this change, that could take a little extra work in the clients -- or not.

**Comment by alistaire47** [comment]
Long-term, we could create run IDs server-side when runs are posted, and then users grab that ID and use it for posting results. But very few of our users are independently creating runs explicitly right now (they're implicitly created when a benchmark result with a new run ID is submitted), so that's not a quick solution.

**Comment by austin3dickey** [comment]
This is no longer a concern now that we've deleted the Run table.
