### ISSUE TITLE
c-bench: `rel err` column sort order broken when "n/a" values are present

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1153]
### unsorted:
![image](https://user-images.githubusercontent.com/265630/233930415-cdc71a61-37a6-49ec-86c8-671108fd6309.png)

### sorted:
![image](https://user-images.githubusercontent.com/265630/233930554-29c11077-a856-4144-b3dd-dbfdae226cd4.png)

8.2 is not the largest!

**Comment by alistaire47** [comment]
String sorting?
