### ISSUE TITLE
UI: benchmark result view: deal with edge case where current result is failed, but we still want to show history

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1185]
It should be possible to generate history for a failed benchmark result, and to show a history plot where the current result then is _not_ represented (at least not with a "here is the mean value" data points).

**Comment by jgehrcke** [comment]
This was resolved in #1182.

**Comment by jgehrcke** [comment]
We should enhance test coverage, including this case. Tracked in https://github.com/conbench/conbench/issues/1185.

**Comment by jonkeane** [comment]
Thanks for this! 

Strong agree on:

> It should be possible to generate history for a failed benchmark result, and to show a history plot where the current result then is not represented (at least not with a "here is the mean value" data points).

And I'm glad to see this back in action!
