### ISSUE TITLE
benchalerts: use new ConbenchClient

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1186]
Instead of the `LegacyConbenchClient`, `benchalerts` should make use of the new `ConbenchClient` backed by `RetryingHTTPClient` introduced in #1148.

This change will involve fixing the unit test mocking framework since that takes advantage of the old `adapter` arg which is not used anymore.

**Comment by jgehrcke** [comment]
> This change will involve fixing the unit test mocking framework since that takes advantage of the old adapter arg which is not used anymore.

Ah, I remember. Yes! Thanks for creating the ticket.
