### ISSUE TITLE
benchalerts: Use the comparison URL instead of entity URL (or in addition to)?

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#1189]
Currently with benchalerts, when a benchmark indicates a regression or improvement we link to the benchmark result itself. Is it possible to link to the comparison of that benchmark with the baseline that was used by default? 

It's currently a little tricky to go from the benchmark result to the comparison page to actually see the z-score, what the baseline looked like etc. etc.

And same thing for runs, it's nice to be able to get to the run itself, but most people are probably looking to get to the comparison first from these alerts.

**Comment by austin3dickey** [comment]
This makes sense! And it should be pretty easy.
