### ISSUE TITLE
benchalerts: notify/fail if there are no results on the contender

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1191]
Right now I suspect that when running `benchalerts`, if there are no benchmark results associated with any contender run, you will get a PR comment like

>There were no benchmark performance regressions. 🎉

with a successful GitHub Check. I think we definitely want to notify about this case, and probably by default we'd want to fail the GitHub Check. We could make that user-configurable in https://github.com/conbench/conbench/issues/756.

**Comment by jonkeane** [comment]
> I think we definitely want to notify about this case, and probably by default we'd want to fail the GitHub Check. We could make that user-configurable in https://github.com/conbench/conbench/issues/756.

💯 on notifying + possibly not failing. We can use the warning | yellow status with these checks right? That might be a good one so folks know to look but it's not ❌

**Comment by austin3dickey** [comment]
>We can use the warning | yellow status with these checks right?

Here are the current statuses: https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-checks?apiVersion=2022-11-28#about-check-runs

There used to be this nice picture in the docs but I can't find it in the docs anymore: 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/16600275/235196739-2c795d14-b99c-420a-8531-8dc60c1bdad5.png">

It seems that there's no "warning" status. Today we use "neutral" when `benchalerts` encountered an error during its pipeline (since that doesn't mean the benchmarks failed, only that the notification failed). Maybe that's an option here if we don't want to block the build. We can still alert on the situation in the PR comment.

**Comment by jonkeane** [comment]
Aaah right right (I find the two sets of these categories very difficult to keep apart in my head!).

Yeah, I wonder if we want to do something like have a "flexible mode" and a "strict mode". In the flexible mode, anything that is not literally a benchmark regressed or a benchmark errored is neutral and then in strict mode those are action required?
