### ISSUE TITLE
benchalerts: handle run comparisons without commits

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1196]
Today I think this will break when `benchalerts` tries to analyze a run without a commit:
https://github.com/conbench/conbench/blob/1e6e2b603b53cd754e729360606ec88cefaf708e/benchalerts/benchalerts/conbench_dataclasses.py#L267
The "commit" value will be None.

**Comment by alistaire47** [comment]
This is why I specified the commit hash needed to be specified in future gh steps if `GetConbenchZComparisonForRunsStep` get used; I think it prevents the `commit_hash` property from getting called. So things might not fail, but yes, we should still handle this better
