### ISSUE TITLE
BMRT cache: cpu work regression as of `sigfig.round()`

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1218]
Pulling this out of https://github.com/conbench/conbench/pull/1205#issuecomment-1534347430.

In this plot we see that the BMRT cache update time jumped from below 10 seconds to a minute:
![screenshot](https://user-images.githubusercontent.com/265630/236158684-cd438879-d7d7-41de-bbf4-26f9e58a1be2.png) (note: this is a custom application metric :rocket:).

The CPU work regression can also be seen here:
![image](https://user-images.githubusercontent.com/265630/236228579-441404ed-de4d-4e44-a599-d7a95888bf20.png)
Around April 11 the surge was as of BMRT cache introduction. The additional surge on top of that towards end of April/beginning of May was a negative side effect of https://github.com/conbench/conbench/pull/1205.

I did basic profiling work and found that (given real-world data: Arrow DB snapshot) when the BMRT cache update took ~16 seconds, that ~10 seconds were spent in `sigfig.round()`. Wow:

```
conbench-app-1  | name                                                                                                  ncall  tsub      ttot      tavg      
conbench-app-1  | /app/conbench/job.py:99 _fetch_and_cache_most_recent_results                                          1      0.490366  15.88532  15.88532
conbench-app-1  | /app/conbench/entities/benchmark_result.py:455 BenchmarkResult.ui_mean_and_uncertainty                20000  0.074558  9.699357  0.000485
conbench-app-1  | /usr/local/lib/python3.11/site-packages/sigfig/sigfig.py:560 round                                    244..  0.159072  9.666894  0.000395
conbench-app-1  | /app/conbench/entities/benchmark_result.py:482 <genexpr>                                              35514  0.029356  6.600892  0.000186
```

The profiling output tells us that `BenchmarkResult.ui_mean_and_uncertainty()` is what after all resulted in many calls of `sigfig.round()`.

That's an easy fix. Compute that only when needed by UI, not in advance within the BMRT cache update.

**Comment by jonkeane** [comment]
> Compute that only when needed by UI, not in advance within the BMRT cache update.

💯 on this — and not even only from a performance stand point, I've found it routinely best to defer presentation details until the last second (e.g. only in the UI) to avoid various other malignancies like double-rounding, inconsistent styles of soundings etc. 

This is one place where having a JS frontend that did this for us and entirely outside of the scope of forming the underlying data would be fantastic (though I suspect would be a relatively large lift to do this from where we are, which is fair enough)

**Comment by jgehrcke** [comment]
> This is one place where having a JS frontend that did this for us and entirely outside of the scope of forming the underlying data would be fantastic 

Yes!

> (though I suspect would be a relatively large lift to do this from where we are, which is fair enough)

Yessss! Having a modern JS/TS-based frontend stack is IMO out of question for us in terms of team resources.  I find interesting that there's movement _back_ from client-side to server-side rendering, and there are extremely cool technologies somewhere in the middle of the spectrum (HTMX is pretty hype). I find https://news.ycombinator.com/item?id=33218439 extremely insightful.

I am sure we can do much better than current Jinja-HTML-hacky-hacky, but we don't need to do SPA.

I especially like https://news.ycombinator.com/item?id=33220196 which starts with

> As someone who has been writing code for 30 years and has been developing "web apps" since the late 90s, it's really funny to me how things come full circle.

Edit: just yesterday again a massive thread on HTMX: https://news.ycombinator.com/item?id=35829733

**Comment by jgehrcke** [comment]
And yet I'd like to add that generating O(10^5) strings from, say, O(10^6) floating point numbers should not take O(10 s) in 2023. That's incredibly inefficient use of silicon. That could totally be a sub-second operation (and of course there are many ideas for how to get there, but for now we just move the calc to a different time :)).

**Comment by jgehrcke** [comment]
Closing this as 'done' for now.
