### ISSUE TITLE
UI: "repo-less" runs show up prominently

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1226]
We know that we have to tackle https://github.com/conbench/conbench/issues/1165 properly. I want to mention one specific motivator, fallout: the repo-less runs right now display rather prominently before regular runs on the landing page, and that's not so nice:

![Screenshot from 2023-05-05 15-56-35](https://user-images.githubusercontent.com/265630/236478623-de9ff455-e53e-46da-bfb0-c98c6f3e3f4d.png)

Related: https://github.com/conbench/conbench/issues/885

A bit of an ambiguous question, but I have labeled this as "bug" because I think we agree that this must not look like that; it's kind of landing page UX regression.

**Comment by jgehrcke** [comment]
Raises questions, ideas. Pre-merge stuff centers around pull requests (merge requests in gitlab). Metadata that might be interesting: author of pull request. pull request number. URL to pull request.

**Comment by jgehrcke** [comment]
When clicking on such a run, the details look rather boring / well, even wrong/fishy:
![image](https://user-images.githubusercontent.com/265630/236480685-488fc12f-3968-4057-9453-28fe4523d426.png)

**Comment by austin3dickey** [comment]
All runs are associated with a repo now.
