### ISSUE TITLE
Explore removing Run table (in favor of run_id on Benchmark_Result, also commit, hardware, etc)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1227]
We recently had another discussion about the pros and cons of having a distinct Run table. This ticket here is supposed to briefly account for that discussion. It's also non-exhaustive.

In this discussion I found one more time that there might be a huge opportunity for simplification (as previously identified in related discussions, e.g. around implicit run creation).

For most types of analyses one needs to look at individual results anyway, and places in code where we do `result.run.commit` / `result.run.hardware` hide a lot of database interaction complexity. The BMRT cache-based work goes into that direction: here, run is just an indirection to get to commit/hardware info.

We identify that a ‘CI run’ perspective is probably where the ‘Benchmark Run’ came from, and where it provides value from a UX perspective. Run as a UX primitive can be implemented as a 'virtual view', in the database it would be sufficient to have a something like a `run_id` property on each BenchmarkResult object/row. That allows for grouping results by run_id, and UI as well as API routes could maintain current behavior.

There is desire to mark a Run as started and finished and failed. That would be difficult to build. But JP notes that this is error-prone and does not yield to the desired outcome anyway:
* Creating a ‘failed Run’ seems to provide value for reporting.
* But we have to plan for / with the scenario that ‘even just creating the Run object’ will fail, and then there’s a void. Conbench is _not_ the primary CI system.
* That is, consuming tooling needs to inspect the CI job that is supposed to submit benchmark results to Conbench anyway.
* The CI job may fail _before_ it is able to submit a “new Run” to Conbench. And it will fail doing so, leaving no trace in Conbench (may be rare, but it will happen).
* At the highest level, this is a ‘classic’ “optimization-first” architecture error: The reporting tooling needs to consult the CI runner anyway (e.g., buildkite), and be prepared for unexpected CI job failure (before Conbench can even be contacted). That is so-to-speak the error handling foundation that must be built. On top of that, as an optimization, one could in theory do more, but the value isn’t clear if the foundation is built nicely.

In practice, we see that Runs are not marked as finished.

Strongly related:
* https://github.com/conbench/conbench/issues/1165
* https://github.com/conbench/conbench/issues/863
* https://github.com/conbench/conbench/issues/864

**Comment by austin3dickey** [comment]
ah, this is done :)
