### ISSUE TITLE
benchmark result compare page: should display errors if present

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1228]
The `/compare/benchmarks/{baseline_result_id}...{contender_result_id}` page should show benchmark result errors if they exist, just like the `/benchmark-results/{result_id}` page does:
https://github.com/conbench/conbench/blob/7c4968e631ecdc064559c86a1174a1353713b700/conbench/templates/benchmark-result.html#L89

**Comment by jgehrcke** [comment]
> The /compare/benchmarks/{baseline_result_id}...{contender_result_id} page should show benchmark result errors if they exist

Yes!

Having worked in that HTML template today I think we might want to rework that, and create a fresh template tailored to the result-to-result comparison.

The attempt to make a generic anything-to-anything comparison (see [code](https://github.com/conbench/conbench/blob/95d40c938500e1fdd169aafb06a0ee7754cb8a74/conbench/templates/compare-entity.html)) was I think a truly honorable attempt, but might just as well be considered a pre-mature abstraction (adding abstraction before it is needed, with too much abstraction creating maintenance/testing burden).
