### ISSUE TITLE
ui: certain numbers are missing across the webapp

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1230]
I've noticed a few cases across the webapp where numbers are missing that I'd expect to be there (or be handled better).

1. `/compare/runs` - all `Baseline` and `Contender` column values for benchmark results without errors just display `s` without a number.
2. `/compare/runs` - if a benchmark result has an error, there's no indication of that. I believe we used to display a (!) glyph.
3. `/compare/runs` - if a benchmark result is missing a pairwise change, there's just a `%` displayed
4. `/compare/benchmarks` - the `Baseline` and `Contender` cells just display `s` without a number
5. `/compare/benchmarks` - if the comparison is missing a pairwise change, there's just a `%` displayed
6. `/compare/benchmarks` - the z-score-related rows are always empty and do not belong with the stats anymore
7. `/benchmark-results` - the z-score-related rows are always empty and do not belong with the stats anymore

Screenshots:
<img width="1309" alt="Screenshot 2023-05-05 at 11 35 17" src="https://user-images.githubusercontent.com/16600275/236519232-3abc95d2-0bc3-420c-9a91-ce4dce022fb2.png">
<img width="1220" alt="Screenshot 2023-05-05 at 11 43 49" src="https://user-images.githubusercontent.com/16600275/236519234-9adf082e-f8bd-4758-bcec-3d84d7c24994.png">
<img width="1231" alt="Screenshot 2023-05-05 at 11 46 20" src="https://user-images.githubusercontent.com/16600275/236519237-a7d202a6-2182-47ef-9f05-28ee076e219f.png">
<img width="1320" alt="Screenshot 2023-05-05 at 11 44 09" src="https://user-images.githubusercontent.com/16600275/236519239-e5290abe-dcba-425d-bd7b-7e0709295065.png">
<img width="651" alt="Screenshot 2023-05-05 at 11 48 42" src="https://user-images.githubusercontent.com/16600275/236519241-d4f97805-efa0-4bf0-b6cb-243ac10b2cb8.png">

**Comment by jgehrcke** [comment]
Thank you for noting down the individual places. We have accumulated a whole bunch of bugs like this over time. 

Most important conclusion: we really need to work on UI test coverage.

We even lack GETting relevant routes at all. We should GET them, confirm that response contains HTML, and then also to pragmatic grep-like checks if expected values/numbers/words are in there. That will generate a whole lot of confidence without requiring to do complex UI testing.

**Comment by jonkeane** [comment]
Thanks for this! Yeah those little things are super pernicious

**Comment by austin3dickey** [comment]
I poked around staging Conbench and validated that all these bugs are fixed, with no unexpected 500s anywhere. I'll deploy to higher environments soon.

**Comment by jonkeane** [comment]
> I'll deploy to higher environments soon.

Thank you!
