### ISSUE TITLE
Request for enhancement: Filter benchmark results by run reason and time window

### ISSUE THREAD

**Issue by boshek** [conbench/conbench#1231]
In this issue, I am hoping to outline a specific use case for filtering benchmark results in Conbench.

Related to https://github.com/conbench/conbench/issues/746. 

Users may need to filter benchmark results by specific run reasons and/or time windows to get insights into their system performance at any arbitrary point in time for a specific reason. 

I am looking to get all benchmark results for a specific run reason over a defined time window of when that benchmark was run. 

Within that benchmark result I am looking to get the following fields:
- aggregated mean value
- all tags, hardware, additional benchmark details
- commit sha, timestamp
- any error information
- run_id
- benchmark and run conbench links
 
I don't think the API currently supports this directly because AKAIK the runs endpoint only accepts queries for the commit sha.

**Comment by jgehrcke** [comment]
Nice. Thanks!

> Filter benchmark results by run reason and time window

Time window makes absolute sense, relates to https://github.com/conbench/conbench/issues/872.

About "run reason" specifically, I'd love to go a little deeper and ask which convention you/we are applying for putting information into that free-form text field. Clarification: `run reason` can be set freely by users. Users can build their own conventions using this field. How exactly do we use it? Which information do we put into "run reason" that we don't put elsewhere? 

Should this be a exact text match? Or do we maybe need something like substring matching like `run_reason_contains="sunshine"` :sun_with_face:?

**Comment by jonkeane** [comment]
> Clarification: run reason can be set freely by users. Users can build their own conventions using this field. How exactly do we use it? Which information do we put into "run reason" that we don't put elsewhere?

Yup, exactly. And in this case, what we are trying to do is take the convention that users have established (where a specific reason is used for a specific kind of triggered run) such that we can grab the (recent) data for all of those runs and then process it. 

> Should this be a exact text match? Or do we maybe need something like substring matching like run_reason_contains="sunshine" 🌞?

Good catch — there's lots that we could do here to make this fancy, but let's do the simplest thing for now: exact text match. If someone wants substring or regex or the like, they can open a separate issue to add that.

**Comment by jgehrcke** [comment]
> what we are trying to do is take the convention that users have established [...]

Yes :) I would still love to have a super short reply to

> How exactly do we use it? Which information do we put into "run reason" that we don't put elsewhere?

Thanks! :pray: 

> there's lots that we could do here to make this fancy

Yes. For the record: not proposing fanciness, just trying to be precise about the desired use case.

**Comment by jgehrcke** [comment]
> How exactly do we use it? Which information do we put into "run reason" that we don't put elsewhere?

From Slack: this is about e.g. "pr" vs. "scheduled", i.e. we want a solution to filter for `run_reason="<one-of-a-few-categories>"`.

**Comment by boshek** [comment]
After the improvements in #1276 and #1257 were merged, I tried out the `benchmark-results?run_reason=foo`.

This is a wonderful improvement and even in it's current incarnation, reduces (and makes more readable) the amount of code needed to query data from a conbench api. I've updated the R client over here: https://github.com/conbench/conbenchcoms/pull/8.

Two pieces of feedback which are a bit intertwined. 

One - I currently have to make a separate api call to the `/runs/` endpoint to get `hardware` and `commit` information. Both of these are critical. Changes in `hardware` affect history and `commit` information is such a first calss citizen in conbench that being without it hampers what you can do with the data. After I've queried both endpoints, I perform a join on `run_id` to add that data to what is returned by `benchmark-results`. This has two ramifications:
- I need to make two api calls to conbench to get all the information I want -> great latency
- My rate limiting step, to get all the required `hardware` and `commit` data is the `runs` call because the [1000 run](https://github.com/conbench/conbench/blob/2f8a2b0a99da5d09b4a862b2f37f9fe040d343d3/conbench/api/runs.py#L150) limit.  


Two - the importance of a time window has been further solified for me. The _vast_ majority of api calls that I make are to gather all data over the past couple weeks. [55000](https://github.com/conbench/conbench/blob/2f8a2b0a99da5d09b4a862b2f37f9fe040d343d3/conbench/api/results.py#L195) is useful in some cases but I am also experiencing the time cost of such a large call. Having the ability to restrict the size of that call remains an important feature.

**Comment by jgehrcke** [comment]
> One - I currently have to make a separate api call to the /runs/ endpoint to get hardware and commit information. [...] After I've queried both endpoints, I perform a join on run_id to add that data to what is returned by benchmark-results

This is horrible. Yes, each benchmark result object emitted by the HTTP/JSON API should have commit and hardware properties. Would these following properties in particular be sufficient for the case you envision?

* commit timestamp
* commit hash
* commit URL (also contains hash, but also repo)
* hardware ID
* hardware name

High level remarks:

Why was it initially decided to expose the individual benchmark result object without these critical properties? Hm. Without them, a consumer needs to do the rather hard work of feeding relating entities to one another (as you describe). Maybe this had to do with (pre-mature?) performance concerns? I want to say that this here is the very typical normalized vs. denormalized data topic, and there is little we can add here that hasn't already been said in e.g. https://news.ycombinator.com/item?id=35924259 where this was once again discussed very recently. I want to add: data _mutation_ (after initial storage, a reason for storing denormalized) in Conbench in my experience does not happen ('finished_at' excluded, it's not too useful anyway).

I want to have a Conbench which simply emits all relevant properties on individual benchmark result objects, even if that results in a massive amount of duplication across the JSON response.

This _heavily_ relates to https://github.com/conbench/conbench/issues/1227.

**Comment by boshek** [comment]
> Why was it initially decided to expose the individual benchmark result object without these critical properties?

I am not certain. I do think that it will always be useful to have a `/runs/` endpoint so I am definitely still in favour of having that. 

> I want to have a Conbench which simply emits all relevant properties on individual benchmark result objects, even if that results in a massive amount of duplication across the JSON response.

That sounds great. 

> Would these following properties in particular be sufficient for the case you envision?
> 
> - commit timestamp
> - commit hash
> - commit URL (also contains hash, but also repo)
> - hardware ID
> - hardware name

Actually I do not believe so hardware. There are so many way that people can tweak configurations that anything outside of all the hardware properties will results in additional requests to add this or that. So I would strongly argue that we need output *all of the hardware properties for a given benchmark result*.

For the commit properties that seems very reasonable.

**Comment by jgehrcke** [comment]
> For the commit properties that seems very reasonable.

ok

> I am not certain. 

:) yeah. Was a bit of a rhetorical question.

 > I would strongly argue that we need output all of the hardware properties for a given benchmark result.

good feedback!

> I do think that it will always be useful to have a /runs/ endpoint so I am definitely still in favour of having that.

Of course. For the record, #1227 is only about implementation detail. As long as a Run is a UX concept it by definition is exposed. From https://github.com/conbench/conbench/issues/1227:

> Run as a UX primitive can be implemented as a 'virtual view', in the database it would be sufficient to have a something like a run_id property on each BenchmarkResult object/row

**Comment by austin3dickey** [comment]
This is done :)
