### ISSUE TITLE
benchmarks.py: accidental key insert upon key lookup

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1236]
https://github.com/conbench/conbench/blob/65cd5c269e6fae1d444e2f24bd78e7f67757c1af/conbench/app/benchmarks.py#L73 -- well, that was so funny I noted the details down here: https://gehrcke.de/2023/05/dont-underestimate-the-dot-shared-state-is-dangerous/

**Comment by jgehrcke** [comment]
Repaired via #1237 :hammer_and_pick:

**Comment by austin3dickey** [comment]
wow, entertaining blog post :)
