### ISSUE TITLE
c-bench UI: "nan" in uplot data breaks plot

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1263]
![image](https://github.com/conbench/conbench/assets/265630/3d9c539b-47ae-4cd9-a092-b752a3f31ccf)

from the raw JSON in the HTML doc:

```
        "21.64405",
        "21.30293",
        "nan",
        "21.42239",
        "22.25914",
        "21.36055",
        "21.74071",
```
https://github.com/leeoniya/uPlot/issues/208

> Ah nevermind, you're supposed to use null not NaN.

**Comment by jonkeane** [comment]
> Ah nevermind, you're supposed to use null not NaN.

🥲

**Comment by jgehrcke** [comment]
Need to see how we even get to the point where the string `"nan"` appears in the JSON doc. 

```
>>> orjson.dumps([float("NaN"), float("Infinity"), float("-Infinity")])
b'[null,null,null]'
```
