### ISSUE TITLE
conbench: `socket.timeout: The read operation timed out` (response timeout) `../compare/runs/...` for the apache/arrow conbench

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#1283]
This wasn't noticed because of #1280 but once that was resolved (via https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/114) we started seeing a timeout when getting one of the compare endpoints. It looks like this is what is causing the other errors too (that first one about NoneType has no attribute id), but that might be a separate issue (and if it is, it's likely with arrow-benchmarks-ci)

FWIW, when I try and go to that compare endpoint myself, I get a 504 currently: https://conbench.ursa.dev/api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/

```
[2023-05-25 12:32:20,654] ERROR in publish_benchmark_results_on_slack: 'NoneType' object has no attribute 'id'
--
  | Traceback (most recent call last):
  | File "/app/buildkite/schedule_and_publish/publish_benchmark_results_on_slack.py", line 19, in publish_benchmark_results_on_slack
  | text = notification.generate_slack_message_text()
  | File "/app/models/notification.py", line 118, in generate_slack_message_text
  | + self.generate_comment_with_compare_runs_links()
  | File "/app/models/notification.py", line 63, in generate_comment_with_compare_runs_links
  | url = self.benchmarkable.conbench_compare_runs_web_url(machine)
  | File "/app/models/benchmarkable.py", line 169, in conbench_compare_runs_web_url
  | baseline_run_id = self.baseline_machine_run(machine).id
  | AttributeError: 'NoneType' object has no attribute 'id'
  | [2023-05-25 12:32:20,734] INFO in __init__: send: GET https://conbench.ursa.dev/api/compare/runs/b6784a310fcc4d97a49e4f33b4fb801f...c17ef6eed50744a185d6871b9efec1de/
  | [2023-05-25 12:32:20,963] INFO in __init__: reply: 200
  | [2023-05-25 12:32:21,051] INFO in __init__: send: GET https://conbench.ursa.dev/api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
  | [2023-05-25 12:32:51,076] WARNING in connectionpool: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Read timed out. (read timeout=30)")': /api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
  | [2023-05-25 12:33:29,122] WARNING in connectionpool: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Read timed out. (read timeout=30)")': /api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
  | [2023-05-25 12:34:15,209] WARNING in connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Read timed out. (read timeout=30)")': /api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
  | [2023-05-25 12:35:17,289] WARNING in connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Read timed out. (read timeout=30)")': /api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
  | [2023-05-25 12:36:51,409] WARNING in connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Read timed out. (read timeout=30)")': /api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
  | [2023-05-25 12:37:21,469] ERROR in publish_benchmark_results_on_slack: HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Max retries exceeded with url: /api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/ (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conbench.ursa.dev', port=443): Read timed out. (read timeout=30)"))
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 536, in _make_request
  | response = conn.getresponse()
  | File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 454, in getresponse
  | httplib_response = super().getresponse()
  | File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
  | response.begin()
  | File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
  | version, status, reason = self._read_status()
  | File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
  | line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  | File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
  | return self._sock.recv_into(b)
  | File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
  | return self.read(nbytes, buffer)
  | File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
  | return self._sslobj.read(len, buffer)
  | socket.timeout: The read operation timed out

```

https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43149#018852e4-1ca1-43c4-88c8-c688c863033b/116-134

**Comment by alistaire47** [comment]
Looked into the `AttributeError` a bit, and there’s some work to do (and not a tiny lift, unfortunately) to rearrange this to use the `candidate_baseline_runs` instead of going straight to GitHub. Switching it to use benchalerts would make this moot and is maybe a better use of time (though also a non-tiny lift).

I suspect (though I’m far from sure) what might be going on is a previous run on that machine failed, and since it’s using GitHub to determine the baseline commit hash instead of Conbench, it’s not walking up to the last commit with a run for that machine, so there’s no run in the baseline commit to have an `id`.

**Comment by jonkeane** [comment]
If those are both long-to-implement fixes, can we rollback the deployment so we can get over this? Or do you think that the current state of arrow-benchmarks-ci is such that it needs some other manual intervention to get unstuck?

**Comment by alistaire47** [comment]
If my understanding of the cause is correct (again, not certain), the attribute error should be transient—it should only occur when the comparable run on the parent commit failed. The Conbench updates were unrelated; it would occur regardless.

The `/api/compare/` timeout is likely related to the updates, though; we did some serious work on that. JP might have a better idea why it's timing out and what the best course of action there is.

**Comment by jonkeane** [comment]
> If my understanding of the cause is correct (again, not certain), the attribute error should be transient—it should only occur when the comparable run on the parent commit failed. The Conbench updates were unrelated; it would occur regardless.

What would you need to validate that this is transient?

**Comment by alistaire47** [comment]
To figure out which commit it was running on when this happened and compare runs on its parent. I dug through the build, and if I understand it was running on [10 merged arrow PRs](https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43149#018852e4-1c61-48fa-9f5a-5f1094240609). Messages on the PRs don't exist for at least some of those, so I think I'll have to map them all to Conbench manually, which will take a bit.

**Comment by alistaire47** [comment]
Ok, I think the `arm64-m6g-linux-compute` run on `dcdeab76b4ba4bac0b4115925c820961ef70ae0d` failed (search it on [arrow conbench](https://conbench.ursa.dev/) and you'll see 6 runs), and it's the parent of `c4ea194c6880d6471a0258db1e8a292df3fa2954` (which has all 7 runs), so the baseline for [this run](https://conbench.ursa.dev/runs/027478583195451598a660aec0a0b016/) is its grandparent. If you [GET it from the API](https://conbench.ursa.dev/api/runs/027478583195451598a660aec0a0b016), you can see the `parent` baseline candidate skips a commit:

```json
{
  "candidate_baseline_runs": {
    "fork_point": {
      "baseline_run_id": null,
      "commits_skipped": null,
      "error": "the contender run is already on the default branch"
    },
    "latest_default": {
      "baseline_run_id": "7154cf8348a44403b511aea9065a350d",
      "commits_skipped": [],
      "error": null
    },
    "parent": {
      "baseline_run_id": "903b87498c4c44a584a6f3b73505970d",
      "commits_skipped": [
        "dcdeab76b4ba4bac0b4115925c820961ef70ae0d"
      ],
      "error": null
    }
  },
  ...
}
```
The abci alerting is not set up to handle this situation, so I'm reasonably confident my assessment was correct. As I said, it's fixable if we're willing to commit the time, but it is a corner case that will only pop up on runs where the parent failed.

And none of this addresses the `/api/compare/` timeout; arrow Conbench was giving me lots of 503s in the course of my investigation of this, so I suspect we've got more general stability/performance problems happening here.

**Comment by jgehrcke** [comment]
> ERROR in publish_benchmark_results_on_slack: HTTPSConnectionPool(host='conbench.ursa.dev'

Needs naming fixing: code in a function called `publish_benchmark_results_on_slack()` should not interact with `conbench.ursa.dev`: slack? conbench? both? what?

About timeout err: this read timeout happens while waiting for / reading the HTTP response. This timeout constant should be chosen with system awareness. Using knowledge about the ~expected response time. I have written exhaustively about https://github.com/conbench/conbench/issues/801. The timeout constant chosen here is 30 s:

```
Read timed out. (read timeout=30)"))
```

In my experience this is not a good choice for Arrow Conbench. Many responses are _expected_ to be generated after far longer than 30 s. Showing a distribution-over-time plot for Arrow Conbench obtained a while back:

![image](https://github.com/conbench/conbench/assets/265630/9c78eddd-7221-4ed2-99ae-ec90acf3b054)

We know that Arrow Conbench is hopelessly overloaded and slow (is, and has always been since I have been looking at it). Clients can deal with that by using large timeout constants.

Immediate action item:
- identify HTTP client code in use here
- bump this timeout constant to something like 180 s

**Comment by jgehrcke** [comment]
> The /api/compare/ timeout is likely related to the updates, though; we did some serious work on that. JP might have a better idea why it's timing out and what the best course of action there is.

:) We need to get a bit into the habit of understanding timeout errors in distributed systems. The first impulse should be to review the timeout constant! Yes, maybe the new behavior slightly increased the response generation time. But a timeout constant should be chosen so that smallish changes do not affect the outcome too much.

**Comment by jgehrcke** [comment]
Small patch increasing the read timeout that I think applies for the affected request here: https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/115 (untested).

**Comment by jonkeane** [comment]
I'll review the PR + possibly respond to other bits later, but wanted to get this detail out sooner:

> Needs naming fixing: code in a function called publish_benchmark_results_on_slack() should not interact with conbench.ursa.dev: slack? conbench? both? what?

I'm 90% sure this is what posts updates to #benchmarking in the voltron data slack — meant as a place that will tell us if something is going off the rails or something we need to fix

**Comment by jgehrcke** [comment]
> I'm 90% sure this is what posts updates to #benchmarking in the voltron data slack 

yes! :) I was trying to say: if the error message isn't buggy then it tells me that we interact with host conbench.ursa.dev _within_ a function called `publish_benchmark_results_on_slack()`. That is, within that function we do not only interact with Slack. But do much more. Needs cleanup either way (buggy error message or bad naming of function / misleading code structure).

**Comment by jonkeane** [comment]
Aaah ok, got it! Sorry I misinterpreted

**Comment by jonkeane** [comment]
I can open a separate issue (since it doesn't _look like_ this is still timeout related), but ultimately, we're going to need to find a way to get around where this pipeline seems to be stuck: https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43311#_ for the recent past has been spending ~ 8 min on the step `Publish Benchmark Results on Slack` and then being cancelled because the next scheduled run is starting. Which means the job is never getting to the part where it will (attempt to) post the comments on github.

If we believe this is transient and will eventually be just fine — maybe we should increase the time between the runs to let one run go through and clear things out. Or we might need to go in and manually stop whatever is causing abci to take as long as it is, where it is, so that it's (practically?) never(?) getting to the alerting / documentation stage that apache/arrow depends on

**Comment by austin3dickey** [comment]
One possibility of the root cause of this issue: https://github.com/conbench/conbench/issues/1285

**Comment by austin3dickey** [comment]
I'm now tracking the specific problem of "the ABCI notification build can't get past its 10-minute timeout" here: https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/118

I suspect we'll have to resolve #1285 to quiet down the 50Xs on the API. But we'll leave this ticket open in case fixing the memory leak doesn't stop the 50Xs, and we need to do further work to fix these timeouts.

**Comment by jgehrcke** [comment]
Closing this for now. I did not go through all build logs, bug through some. Have not seen the `The read operation timed out` in a while.

**Comment by austin3dickey** [comment]
For what it's worth, I just got a 504 when GETting the original problematic endpoint. Let's continue to keep an eye on this. I do believe that faithfully retrying would help because the DB has a "warmup effect," so we might not see this problem in logs.
```
> curl https://conbench.ursa.dev/api/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

But this does affect users trying to navigate to the compare page, like https://conbench.ursa.dev/compare/runs/395700bedb034d948c4adfb39e009124...9c499d087b5e490e92d9261cb2acd096/ .

**Comment by jgehrcke** [comment]
>  I just got a 504 when GETting the original problematic endpoint

Yes. Want to clarify that this ticket here was about a timeout observed by the _client_ while waiting for an HTTP response.

**Comment by austin3dickey** [comment]
Related: #745 for tracking intermittent 504s on the Arrow compare runs webapp page.
