### ISSUE TITLE
web app: memory leak (around /api/compare/runs?)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1285]
Seen in a production environment: Memory usage growing over time until the OOM kill hits in:
![image](https://github.com/conbench/conbench/assets/265630/be6ab368-64a8-4a30-a244-9042460ac69b)

**Comment by jgehrcke** [comment]
Could in an initial investigation not reproduce a memory leak caused by BMRT cache update:
![image](https://github.com/conbench/conbench/assets/265630/60353e3f-4b73-43d5-88a9-3647a928dde3)

(time axis is about one hour wide)

At least not via the database state I am working with which is a constant set of results
```
BMRT cache population done (192569 results, took 23.539 s)
```

Edit. After much more time (6 hours):

![image](https://github.com/conbench/conbench/assets/265630/2efa1bb6-c574-4584-8e1a-e8dc0961b86a)

**Comment by jgehrcke** [comment]
Doing more debug work by generating API load during the memory analysis.
Also see https://github.com/conbench/conbench/pull/1287.

**Comment by jgehrcke** [comment]
Reproduced mem leak with mixed load:
![image](https://github.com/conbench/conbench/assets/265630/a7974b40-d60b-45fa-b991-737ea45200f4)

Now simplifying load.

**Comment by jgehrcke** [comment]
memory leak reproduced with just write load (posting benchmark results at high rate): 
![image](https://github.com/conbench/conbench/assets/265630/c0ed789d-f04c-4f31-9209-a5716999a1f2)

(the right-most scenario is the one with just write load)

**Comment by jgehrcke** [comment]
> memory leak reproduced with just write load (posting benchmark results at high rate):

That was a flawed setup where the BMRT cache size was set much higher (3*10^5) than the number of benchmark results in the database (1.5*10^5). With that setup, the memory consumed by the cache is expected to grow over time until it reaches its max size. Trying to reproduce again with the cache size being smaller than the number of results in the database.

**Comment by jgehrcke** [comment]
Update: no memory leak with high constant influx of benchmark results, tested for ~two hours:
![image](https://github.com/conbench/conbench/assets/265630/f504daf2-15ed-4035-a406-00f249b8e674)

**Comment by jgehrcke** [comment]
> Reproduced mem leak with mixed load:

note: here, I mainly stressed the api/compare/runs endpoint.

**Comment by jgehrcke** [comment]
No memory leak around BMRT cache found. Alternative explanation in https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/124.

**Comment by jgehrcke** [comment]
As talked about in sync meeting @austin3dickey the left-hand plot in https://github.com/conbench/conbench/issues/1285#issuecomment-1570429300 shows all the wiggling and memory growth because of requests to the compare/runs/... endpoint. It looks like this might actually be a relevant memory leak that needs debugging:  https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/124#issuecomment-1580563578

**Comment by austin3dickey** [comment]
Fascinating! I am going to reopen and rename this issue to track that. If you'd rather I create a new issue that's fine, but I think there's enough relevant context here.

**Comment by jgehrcke** [comment]
For now I consider there to be no memory leak.

Just slow convergence:
![image](https://github.com/conbench/conbench/assets/265630/159132e4-e593-46bc-b955-dab5ae282e34)

The growth pattern has to do with what RSS is after all measuring, and what needs to happen for RSS to decrease. Memory pressure may be required. 

For example, from the GO 1.12 release notes:

> On Linux, the runtime now uses MADV_FREE to release unused memory. This is more efficient but may result in higher reported RSS. The kernel will reclaim the unused data when it is needed. To revert to the Go 1.11 behavior (MADV_DONTNEED), set the environment variable GODEBUG=madvdontneed=1.

Does CPython use MADV_FREE? Maybe: https://github.com/python/cpython/blob/a8d69fe92c65d636fc454cfb1825c357eb2e6325/Modules/mmapmodule.c#L1710

Maybe not: https://github.com/python/cpython/issues/70788

From other discussions:

> Hmm. I see what you're saying. The tricky part is that there are actually two levels of "released to the OS" on Linux: there's "release this if you need it" and there's "release this right now". Go now uses "release this if you need it" on Linux instead of "release this right now" and is much more aggressive about marking memory as "release this if you need it." Maybe the second bullet needs to be reworded so that it's not about when the Go runtime itself releases memory...

> This is expected and RSS will drop if the system is under memory pressure.
