### ISSUE TITLE
c-benchmarks: trends: build from 'default branch' results only

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1307]
This should maybe be a boolean on each benchmark result: `default_branch`. Right now it's unnecessarily complicated to filter benchmark results obtained for the default branch, unless I am missing something.

**Comment by austin3dickey** [comment]
The way we filter benchmark results, runs, and commits to the default branch today (in at least six places) is checking whether `commit.sha == commit.fork_point_sha`. This is definitely confusing and maybe [causes slow performance](https://github.com/conbench/conbench/issues/745#issuecomment-1442363191) in some cases. As I proposed in that comment, it's probably better to have a boolean property on the commit object.

Additionally, you're suggesting denormalizing this property of a commit onto the benchmark result, which of course heavily relates to https://github.com/conbench/conbench/issues/1227. It's an interesting idea!

**Comment by jgehrcke** [comment]
Thank you for the feedback, Austin! You were fast haha, I wanted to ping you and ask specifically about your opinion.

>  it's probably better to have a boolean property on the commit object.

I made a tiny (real tiny) bit of progress here: https://github.com/conbench/conbench/pull/1308/files#r1228321980

**Comment by jgehrcke** [comment]
this is done :)
