### ISSUE TITLE
silence sigfig warning

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1324]
```
/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py:586: UserWarning: warning: 4 significant figures requested from number with only 3 significant figures
```
probably from units.py

**Comment by alistaire47** [comment]
At this point we only import `sigfig` in `api/compare.py` and `entities/benchmark_result.py`: https://github.com/search?q=repo:conbench/conbench%20sigfig&type=code The warning is pretty definitely coming from the latter, as the former has `warn=False` set (`sigfig.round()` is verbose in its warning about corner cases, so it has an easy opt-out).

**Comment by jgehrcke** [comment]
> warn=False

cool, good way to silence warnings when using `sigfig.round()`.

>  coming from the latter

probably, yes!

I want to state a goal statement from before. After https://github.com/conbench/conbench/pull/1245 we want to use the new numstr() instead of sigfig.round for coverting a numeric data type into a string, using a desired number of significant digits. `sigfig.round()` is then (only) useful for uncertainty string building, done e.g. here: https://github.com/conbench/conbench/blob/52cf34f96cb471f493dc201b0a57ece6132eb10d/conbench/entities/benchmark_result.py#L582

**Comment by jgehrcke** [comment]
I browsed web app logs, I think this is done!
