### ISSUE TITLE
benchmark result submission: require to pick from a known set of unit strings (for reliable less/more-is-better determination)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1335]
Most benchmarks are measuring a duration where smaller values are better. But there are also other types of benchmarks that report values where more is better. These benchmarks measure for example iterations per second or bytes per second.

Example for a benchmark where each result reports the unit i/s (which is iterations per second? items per second?): https://conbench.ursa.dev/benchmark-results/1b98a98dc8ad4d3fa4d236d5049d5eff/

The unit text/string (in case of the example shown: `i/s`) is user-given.

As of today, Conbench allows users to set any unit string with a benchmark result, and Conbench cannot reliably translate that unit to either "more is better" or "less is better". In fact, Conbench assigns "less is better" when it in fact doesn't know. That is historic decision-making, and a problem. Core value proposition is to detect change and to notify with decent signal-to-noise ratio. Getting the directionality wrong (along the "better"-"worse" axis) leads to significant user-facing data reporting bugs.

A conceptually better way could be to have the user also provide the directionality as in less_is_better: true/false, or that the user must pick from a set of pre-defined unit strings where the translation is hard-coded.

Having to pick from a pre-defined list would be a breaking change. For not breaking at least the deployments that we operate, we can of course make sure to handle all so-far known unit strings.

(in a second step) we could make this set of known units configurable to give other users/deployments a migration path.

**Comment by jgehrcke** [comment]
Each supported unit should come with three properties to cover these concepts:
- short version (string)
- long version (string)
- less_is_better definition (boolean)

**Comment by alistaire47** [comment]
It would be convenient to use a standard for units so long versions and abbreviations are consistent. At a glance it looks like ISO/IEC/ISQ-80000 is probably what we're after, but I haven't found a nice machine-readable version. Or Unicode CLDR has some more lightweight unit standardization, e.g. https://www.unicode.org/cldr/charts/42/supplemental/unit_conversions.html

**Comment by jgehrcke** [comment]
As the first step, I think we should simply have a hard-coded map in application code covering what's in today's databases. Then add new validation into the result submission http handler. Emitting 400 Bad Request for an unknown unit.

**Comment by alistaire47** [comment]
Yeah, long-term if we ever get to the point where our userbase needs customizable units we'll have to stick it in the database, but a Python object accessible from the various parts of the codebase that need it is sufficient and faster for now.

To explicitly state what's already likely an assumption (and I think true in our current usage?): We should not allow multiple units to have the same abbreviation (case-sensitive), and units should have only one abbreviation, i.e. it should be a 1:1 unit:abbreviation mapping.

**Comment by austin3dickey** [comment]
I just checked: of all the databases I know about, here are all the units used this month:
- `s`
- `ns`
- `B/s`
- `b/s`
- `i/s`
- null

**Comment by alistaire47** [comment]
Null meaning `stats` is not supplied because the case errored? Otherwise `unit` is a required field...

And are `B/s` and `b/s` bytes and bits or just lazy capitalization?

**Comment by austin3dickey** [comment]
>Null meaning `stats` is not supplied because the case errored?

Probably, yes. Technically `unit` is nullable:
https://github.com/conbench/conbench/blob/35a6c65c6add366686d4a7f1b5e94f4063245d26/conbench/entities/benchmark_result.py#L101

And is only filled in if `stats` is provided:
https://github.com/conbench/conbench/blob/35a6c65c6add366686d4a7f1b5e94f4063245d26/conbench/entities/benchmark_result.py#L180

But I'm not 100% positive that explains all `null` rows; there could have been different code in the distant past that inserted `null` rows for a different reason.

>And are B/s and b/s bytes and bits or just lazy capitalization?

I just queried one benchmark result for each of these units from the Arrow database. The [C++ microbenchmarks](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/cpp_micro_benchmarks.py) use `B/s`. The [Go benchmarks](https://github.com/apache/arrow/blob/main/ci/scripts/go_bench_adapt.py) use `b/s`, at least [sometimes](https://github.com/apache/arrow/blob/085a0baf78685a4e30bd12db307f771ae9cafed7/go/arrow/bitutil/bitmaps_test.go#L236).

**Comment by alistaire47** [comment]
Given the incoming unit for the Go benchmarks there is `MBPerSec` and it's multiplied by 1e6 instead of 8e6, it appears that `b/s` should be `B/s`

https://github.com/apache/arrow/blob/main/ci/scripts/go_bench_adapt.py#L86

**Comment by jgehrcke** [comment]
> Given the incoming unit for the Go benchmarks there is MBPerSec and it's multiplied by 1e6 instead of 8e6, it appears that b/s should be B/s

Thanks for digging this up. Line of code in question:

```
data = benchmark["Mem"]["MBPerSec"] * 1e6
```
Original intent of author not clear (ambiguous variable name, no code comment). Yes, it is probably trying to convert from `MB/s` (which hopefully is not actually `MiB/s`) to `B/s`.

**Comment by jgehrcke** [comment]
We can consider this 'done' for now after https://github.com/conbench/conbench/pull/1373.

Next up: use this information in analysis, plotting.
