### ISSUE TITLE
cluster info: include optional_info in unique constraint

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1340]
I just noticed this curious behavior of Cluster upserting:

https://github.com/conbench/conbench/blob/2175b9b19c1c53603c109e2790c7401d74e94994/conbench/entities/hardware.py#L115-L122

This is called whenever a Run is created. So it sounds like we're attempting to put a unique constraint on `(name, info)` for Cluster objects. One consequence of this is that we overwrite the cluster `optional_info` whenever we post a new Run with the same `(name, info)`.

One problem with this: in practice, this unique constraint has no technical enforcement. For example, in an internal Conbench instance, we see:
```
=> SELECT COUNT(DISTINCT name || info::text), COUNT(*) FROM hardware;
 count | count
-------+-------
   102 |   181
```
I'm not exactly sure how the database got in that state, but it can't be good that line 117 might return one row or another nondeterministically.

Another problem with this: we have a use case where we want to manage multiple Cluster instances that each have their own `optional_info` (for tracking purposes) but share the same `(name, info)` so that they're still comparable for history via the hashing algorithm: 

https://github.com/conbench/conbench/blob/2175b9b19c1c53603c109e2790c7401d74e94994/conbench/entities/hardware.py#L124-L131

I think that should be fully supported. It seems that `hash` was created to allow for this kind of thing; allowing the flexibility to choose which attributes should be incomparable or not. Therefore I think we should include `optional_info` in the unique constraint (and actually enforce that unique constraint so that the upsert works correctly).

**Comment by jgehrcke** [comment]
Thank you! I'd like to also mention here that I think the way we treat hardware/platform is rather complex. Might be an opportunity for valuable simplification. This relates to #1281 (machine/cluster distinction). I find interesting: hardware id is a hash derived from some properties, hardware hash is a hash derived from other properties, hardware name has a bit of an unclear relationship to either. I didn't think this through at all, but if we have to mutate DB contents anyway maybe we can try to simplify significantly at the same time.

**Comment by jgehrcke** [comment]
> One consequence of this is that we overwrite the cluster optional_info whenever we post a new Run with the same (name, info).

Maybe this "overwrite" was intentional as in "last known state takes precedence"? Not sure if that makes sense or not, but maybe it was meant as a means against possible table growth when optional_info contains properties that evolve over time (like a path to a temporary directory, or byte counters, or anything like that).

**Comment by austin3dickey** [comment]
>This relates to https://github.com/conbench/conbench/issues/1281

Yes, I like your comment there: https://github.com/conbench/conbench/issues/1281#issuecomment-1620150838. I think implementing that would go hand-in-hand with this issue.

>Maybe this "overwrite" was intentional as in "last known state takes precedence"? 

Agreed. However, I don't think that behavior makes sense for this DB schema. For instance, let's say we change the value of a byte counter in the optional_info of a row of the Hardware table today. Then, for a report, we query historic benchmark results from last month, and left join the hardware information. Those old benchmark results will have the "wrong" value of that byte counter, which could be confusing for reporting.

**Comment by austin3dickey** [comment]
>in practice, this unique constraint has no technical enforcement.

Ah. This is because we're storing both `Machine` and `Cluster` in the same `Hardware` table, and `Machine` rows are `null` for `info` and `optional_info`. We can't put a unique constraint on `(name, info, optional_info)` or else we'd break how the `Machine` part of the table works. As you said, rather complex!

My plan to address this issue: 
1. To unblock some work at my company, I'm just going to add `optional_info` to the upsert logic today. None of the public Conbench instances use Clusters, only Machines, so this change won't affect them. This change may result in extra rows in our internal Conbench instance, but nothing worse than that.
2. I'm planning on addressing many of the DB schema ideas we've been talking about recently over the next quarter. I will simplify the Hardware schema (#1281) then.
