### ISSUE TITLE
UI: "delete run", "delete benchmark result" buttons are visible even if user is not logged in

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1349]
Example: log out and view https://velox-conbench.voltrondata.run/runs/GHA-5485811622-1/

and https://velox-conbench.voltrondata.run/benchmark-results/064a7f4092a07baa8000fd57b8107e4a/

**Comment by jgehrcke** [comment]
I double-checked: anonymous users do not have the privilege to delete, however; that should also be covered by the test suite.

Yes, we can wrap this button (and others) in corresponding conditionals.

**Comment by jgehrcke** [comment]
Done, taken care of via https://github.com/conbench/conbench/pull/1352.
