### ISSUE TITLE
c-bench: tinyplots: use hardware hash for grouping,  not hardware ID

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1353]
In the c-bench UI in tinyplots I have been grouping into individual timeseries via hardware ID and not via hardware hash. That creates bugs!

relates to #1281 / https://github.com/conbench/conbench/issues/1340#issuecomment-1618469152

For example, these belong together:

![image](https://github.com/conbench/conbench/assets/265630/6fb09b2c-d8e3-431a-ad42-dd66622a83df)

**Comment by austin3dickey** [comment]
Thanks for the catch! Simplifying the "environment" schema will help us so much.

**Comment by jgehrcke** [comment]
Done via https://github.com/conbench/conbench/pull/1357.
