### ISSUE TITLE
z-score calculation: Exclude prior results on same commit

### ISSUE THREAD

**Issue by alistaire47** [conbench/conbench#1360]
Currently, if a run results in an extreme regression and then a user reruns the benchmark on the same commit without changing anything, the extreme value will be included in history when calculating the z-score for the rerun, lowering it significantly. To analyze this fairly, we should exclude prior results on the same commit when pulling history for calculating z-scores.

Note this solution is not robust to user behavior—if they make a subsequent docs or empty PR and rerun, Conbench can't tell that the prior result should be excluded. A more robust option for runs on PRs would be to exclude all results on PR commits back to the fork point. That's more drastic and more work to implement, but worth consideration.

Theoretically the initial result should be excluded as an outlier, but the current outlier detection will never exclude it, because it relies on a subsequent result that reverts towards normal, so it can never mark the most recent value as an outlier. (This is by design; it's impossible to tell the difference between an outlier and a distribution shift without more data.)

**Comment by austin3dickey** [comment]
>the extreme value will be included in history when calculating the z-score for the rerun

I don't think this is true. When we do the rolling analysis, we roll over commits (not results), with an open window on the right side, so it should be excluding all results from the current commit:
https://github.com/conbench/conbench/blob/98cbd080f15d83a3cfe68c388825b2106e87161b/conbench/entities/history.py#L641-L647

>A more robust option for runs on PRs would be to exclude all results on PR commits back to the fork point.

As far as I know, all repos are already doing this today when running `benchalerts` on PRs. [Arrow](https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/81c1389fde31ce8de190c502fb852344923a1007/models/benchalerts_run.py#L76-L78) and [Velox](https://github.com/facebookincubator/velox/blob/d18d67f966dbdbddffb8f3fd6ed0e4e0c8ebc2e0/scripts/benchmark-alert.py#L116-L118) both compare PR runs to the fork-point commit, not the parent commit.
