### ISSUE TITLE
benchadapt: ArcheryAdapter is reporting suite name for benchmark name

### ISSUE THREAD

**Issue by alistaire47** [conbench/conbench#1379]
`ArcheryAdapter` is currently substituting suite name for benchmark name, e.g. https://conbench.ursa.dev/benchmark-results/064be78e31f67168800063884199004a/ 

<img width="662" alt="image" src="https://github.com/conbench/conbench/assets/1693477/e3f55652-3b78-4863-bc7f-5861011e593c">

and the benchmark name is entirely missing.

After fixing this, we'll need to bump the benchadapt version for voltrondata-labs/benchmarks to get it to pick up the change.

**Comment by austin3dickey** [comment]
awesome: this is the root cause of https://github.com/conbench/conbench/issues/1350#issuecomment-1632264749

**Comment by alistaire47** [comment]
Update: I discovered the issue is not actually in `ArcheryAdapter`—the data being sent is correct:

<details>
  <summary>Example result</summary>

From https://conbench.ursa.dev/api/benchmark-results/064c29de44da729a8000da6354e851fa/

``` json
{
  "batch_id": "c6b3f53b5e924822b9983f28097cdb6d",
  "change_annotations": {},
  "error": null,
  "id": "064c29de44da729a8000da6354e851fa",
  "links": {
    "context": "http://conbench.ursa.dev/api/contexts/ee186706d53446a9a8c4dff18cd251c6/",
    "info": "http://conbench.ursa.dev/api/info/064adb5d5a91755a800058ccdbc7d4fd/",
    "list": "http://conbench.ursa.dev/api/benchmarks/",
    "run": "http://conbench.ursa.dev/api/runs/e57e82d6a8c6464a8a43abb70e0020bc/",
    "self": "http://conbench.ursa.dev/api/benchmarks/064c29de44da729a8000da6354e851fa/"
  },
  "optional_benchmark_info": null,
  "run_id": "e57e82d6a8c6464a8a43abb70e0020bc",
  "stats": {
    "data": [
      155600496.22750118
    ],
    "iqr": null,
    "iterations": 1,
    "max": null,
    "mean": 155600496.22750118,
    "median": null,
    "min": null,
    "q1": null,
    "q3": null,
    "stdev": null,
    "time_unit": "us",
    "times": [
      6739.396261624419
    ],
    "unit": "i/s"
  },
  "tags": {
    "name": "MinMaxDoublesGroupedByMediumInt",
    "params": "1048576/1",
    "source": "cpp-micro",
    "suite": "arrow-acero-aggregate-benchmark"
  },
  "timestamp": "2023-07-27T16:36:24Z",
  "validation": null
}
```

</details>

You can also see in [the UI](https://conbench.ursa.dev/benchmark-results/064c29de44da729a8000da6354e851fa/) that `name` is correct even though the display name is `suite`:

<img width="647" alt="image" src="https://github.com/conbench/conbench/assets/1693477/61d641b8-7e1f-496b-bc0b-9fca702d7f5c">

<img width="648" alt="image" src="https://github.com/conbench/conbench/assets/1693477/58b7b383-40a4-4576-8b6a-a0df0f54d2f9">

This is because of this line in `conbench/hacks.py`:

https://github.com/conbench/conbench/blob/038977d8153510c7fef4d6f656229764b809304c/conbench/hacks.py#L93-L95

I believe it should be fine to remove that line; `name` is required to be populated by the API, and AFAIK should always be the value users want to see.

Good news: This means if we fix this, old results will show with the correct name too—we don't have a bunch of incorrect data in our database.

**Comment by alistaire47** [comment]
Closing in favor of #1392
