### ISSUE TITLE
benchalerts: display benchmark name and language in notifications

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1395]
Currently, to identify a benchmark result in `benchalerts` notifications, we use the `case_permutation` value from the compare endpoint's `contender` payload:

https://github.com/conbench/conbench/blob/038977d8153510c7fef4d6f656229764b809304c/benchalerts/benchalerts/conbench_dataclasses.py#L65

That payload also has `benchmark_name` and `language` keys. User feedback: these should be displayed as well.

`benchmark_name` is of course incredibly important, and a big reason we missed it is that before #1114 we didn't have good access to it. IMO it boils down to #942.

**Comment by alistaire47** [comment]
> `benchmark_name` is of course incredibly important, and a big reason we missed it is that before #1114 we didn't have good access to it. IMO it boils down to #942.

I think it was there, it was just very confusingly called `batch` 🤦 https://github.com/conbench/conbench/pull/1114/files#diff-d05ae8ad3a2fd4d2856472286add3ea0a256a030442393c7f13a491fd0eb10a1L49
