### ISSUE TITLE
benchadapt: Remove BenchmarkRun class

### ISSUE THREAD

**Issue by alistaire47** [conbench/conbench#1430]
As we move towards removing the Run table (see #1227), the `/api/runs` POST endpoint will be removed. The [`BenchmarkRun` class from benchadapt](https://github.com/conbench/conbench/blob/2411b0efb70036dc3563c19b12f6bd3ffd482594/benchadapt/python/benchadapt/run.py) reflects this endpoint, and should be removed.

Part of this story is tracking any usages of this class and taking steps towards mitigating them. (Almost all versions are pinned, so changes here can be merged before fixes if necessary.) Already known: benchconnect (#1429)

**Comment by jgehrcke** [comment]
Good thinking. I want to say that for achieving our high-prio goals and for having less constraints to manage, we can take the tension / stress out of this by making `/api/runs POST` be a noop on the API implementation side, at least for a transition time. It's a typical strategy buying peace of mind.

A clear migration path with no parts obviously breaking already requires managing a dependency tree by doing specific changes in a certain order. That can be tough to plan. The more simple this dependency tree can be made the less likely are fatal oversights.

think: for achieving our actual goals we do not need to break clients yet that _try to_ POST to /api/runs; this does not need to be part of the 'first transaction'.

**Comment by alistaire47** [comment]
Cool, that makes it easier to deal with this when we've got capacity. The exception is if the client does something with the response or hits the API for it later, but benchconnect doesn't:

https://github.com/conbench/conbench/blob/b03b1ffa0716098143ac0cbe354aa9169205a275/benchconnect/benchconnect/_start.py#L36
