### ISSUE TITLE
devprod: `current_session` type hint isn't optimal

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1461]
https://github.com/conbench/conbench/pull/1301 was a great change for the performance of our webapp, but it left one drawback. For example, see this diff:
<img width="529" alt="image" src="https://github.com/conbench/conbench/assets/16600275/a513e214-2a86-4473-95a0-ca0fc3e2d09c">

In my IDE, the `.scalars()` and `.all()` methods are well-defined for the `Session` variable (which is a `sqlalchemy.orm.Session` instance) but not for the `current_session` variable (which is a `werkzeug.local.LocalProxy` instance). This means that query results aren't type-hinted correctly throughout the code base anymore, which makes it a little harder to develop.

**Comment by jgehrcke** [comment]
Oh. Thanks for noting this down; I think I also noticed this regression at some point but didn't realize how/when it was introduced.
