### ISSUE TITLE
/api/runs/: if sha arg is given, don't restrict to days

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1478]
Today, `benchalerts` hits the `/api/runs/?sha=X` endpoint in order to get information about all runs on a given commit:
https://github.com/conbench/conbench/blob/759930578c6234debd085abd8f89882d3f2934e3/benchalerts/benchalerts/pipeline_steps/conbench.py#L201-L203

But if benchmark results associated with that commit hash are from more than 30 days ago, that endpoint won't return those runs:
https://github.com/conbench/conbench/blob/759930578c6234debd085abd8f89882d3f2934e3/conbench/api/runs.py#L468-L473

I think we should relax the date constraints if a specific commit hash is requested. The database is indexed on `commit_id` now too, so it should be fairly fast to query runs associated with a commit hash regardless of date.

**Comment by boshek** [comment]
Thanks for noticing this. This will also break the Arrow performance release report which compares a release candidate to the most recent release which will span longer than 30 days. So an `api/run/sha=sha1,sha2` call won't work.

**Comment by austin3dickey** [comment]
Closed in #1480.
