### ISSUE TITLE
landing page: 'recent runs' query may still be slow occasionally (> 10 s)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1482]
Seen for Arrow Conbench, response generation time of ~25 seconds:

![Screenshot from 2023-09-18 12-12-48](https://github.com/conbench/conbench/assets/265630/db40f96f-d1af-48b3-a40e-0dfa76e362d0)

Also represented in the response generation time histogram over time:

![image](https://github.com/conbench/conbench/assets/265630/2c35a4de-a18e-4d5f-ad8f-d4d0c8fb7161)

(population of the 20s - 40s bucket on the right-hand side).

**Comment by jgehrcke** [comment]
Screenshot from RDS performance insights, database load over time for _only_ the skip scan query (driving the 'recent runs' output):

![image](https://github.com/conbench/conbench/assets/265630/696e4b33-1864-4307-9127-50c3be2938cb)

That plot database load ("AAS" metric) over time. 

It represents three queries, one with a (clearly visible) AAS of almost 1, and if you look closely then there are two more occurrences with much smaller AAS values.

What do we from taht plot?
- Via time correlation we know that the big peak corresponds to those two access log lines shown in the screenshot above.
- As of the color code we see that most of the time was spent in `buffer_io` and `DataFileRead` categories, not so much CPU.
- For the two subsequently issued skip scan queries the DB response was provided much quicker.

**Comment by jgehrcke** [comment]
> most of the time was spent in buffer_io and DataFileRead categories

Digging a bit deeper. This is from a plot "sliced by waits".

A clearer way to say what happened was that 37 % of the time spent "answering the query" was spent in waiting for something represented by the name `buffer_io`. What is that something?

It is a lock, time was spent acquiring that lock. More specifically:

> The LWLock:BufferIO event occurs when RDS for PostgreSQL is waiting for other processes to finish their input/output (I/O) operations when concurrently trying to access a page. Its purpose is for the same page to be read into the shared buffer.

(https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/wait-event.lwlockbufferio.html)

That is, one part of the answer here is why that specific query response was slow: the DB was busy with other work. That other might might for example have to do with populating the BMRT cache (periodically occurring significant read load on DB).

Let's see how often this happens. Maybe it is rather rare.

**Comment by austin3dickey** [comment]
Thanks for the initial analysis!

**Comment by austin3dickey** [comment]
This does seem to be happening quite often. Maybe about half the time, the page loads in >5s.
<img width="1265" alt="image" src="https://github.com/conbench/conbench/assets/16600275/c310a5d0-365c-41b6-94b2-25a397a7baed">

**Comment by austin3dickey** [comment]
I was running an EXPLAIN ANALYZE on this query and found that the first run took ~28s and subsequent runs took ~1s. Looking at the performance dashboard, I don't see any `buffer_io` waits for the long run; just a lot of file IO. I wonder if this query simply benefits a lot from the shared buffers. If that's the case, we could consider running it as a job periodically. But there might also be a smarter index we could benefit from, or a better time filter.

<img width="1464" alt="image" src="https://github.com/conbench/conbench/assets/16600275/99fd43d6-3a5f-4def-b26e-ffc650b4fa93">

**Comment by austin3dickey** [comment]
Just hit a painfully-slow execution of this query on an internal instance with "small" data, while trying to load the landing page. The query took 69 seconds, mostly reading data files, and from the query plan I assume this was time spent on the INDEX SCAN of run_id.

I think it makes sense to create a partial index of `run_id`, covering the last few months, and scope this skip scan query to that same time frame. That will result in reading much fewer files upon a cache miss.

This naturally implies regular maintenance of this index, recreating it every now and then with a different start date so it doesn't grow too large. Not ideal. With each passing day I wonder about solutions like TimescaleDB. (#929)

<img width="1495" alt="image" src="https://github.com/conbench/conbench/assets/16600275/ca8bd9c7-468e-42d3-bc14-48a7eb58b1ec">

**Comment by austin3dickey** [comment]
Anecdotally, deploying the above PR seems to have helped a lot. We'll collect more data and see if we can spot a cache miss.
