### ISSUE TITLE
deployment pipeline: cannot `jb install kube-prometheus`

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1493]
Seen, for example, [here](https://github.com/conbench/conbench/actions/runs/6318525930/job/17157695989).

When running this command:

https://github.com/conbench/conbench/blob/89ddc4b5745c8bbef74900a5a8ff7d4f51caa0d9/Makefile#L316-L317

we see

```
GET https://github.com/pyrra-dev/pyrra/archive/f2052cce0c848bb8c4c4d5d964a97b5038237487.tar.gz 200
panic: rename vendor/.tmp/jsonnetpkg-github.com-pyrra-dev-pyrra-config-crd-bases-main336769959/config/crd/bases vendor/github.com/pyrra-dev/pyrra/config/crd/bases: no such file or directory
```

I think there might be something wrong with the vendored `pyrra` repo? We got a different tar the [last time](https://github.com/conbench/conbench/actions/runs/6303291179/job/17112233182) the run succeeded.

**Comment by austin3dickey** [comment]
This is currently reproducible on my laptop by running the above `docker run` command.

**Comment by austin3dickey** [comment]
Oh, this is not just a CI instability. Because it affects `make jsonnet-kube-prom-manifests`, it is blocking any deployment pipeline from executing.

**Comment by jgehrcke** [comment]
In progress, findings here: https://github.com/prometheus-operator/kube-prometheus/issues/2224

**Comment by jgehrcke** [comment]
Changed kube-prometheus build method, bumped it too. Deployed to VD-2. Looks good for now.
