### ISSUE TITLE
DOC: Unclear the difference between `unit` and `time_unit` in adapter's `stats` dictionary 

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1538]
I'm not sure how to set `unit` in the `stats` dictionary of an adapter.
I can't find the difference between that and `time_unit`. 
I think `unit` can have `s` or `hertz`. Can it take more values? 
Did you remove the requirement of `time_unit`? (I just saw a merged PR about it!).

My adapter has this:
```
parsed_benchmark = BenchmarkResult(
                        batch_id="A", #CORRECT THIS
                        stats={
                            "data": [data],
                            "unit": "s", #CORRECT THIS
                            "times": [data],
                            "time_unit": benchmarks_info[name]['unit'],
                            "iterations": 1,
                        },
                        ...
```
BTW, I'm not sure (yet) how to set the `batch_id` either. Should I open another issue? Am I polluting the issues list?

**Comment by DeaMariaLeon** [comment]
Never mind, asv only uses either seconds or bytes as units. 
Sorry for the noise.

**Comment by austin3dickey** [comment]
Agreed that there needs to be more doc clarity here.

>Am I polluting the issues list?

Not at all! I'm really grateful for the bugs and doc uncertainties you've surfaced. It's very difficult to anticipate the diverse needs of users who aren't following the patterns we've used before. Every perspective is appreciated!
