### ISSUE TITLE
Enhancement: Units of data Bytes not available, only Bytes/second 

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1543]
Benchmarks library asv uses seconds or Bytes as units. Conbench does not give the option to use "Bytes". We have to use Bytes/second. Can just "Bytes" be added?

![Screenshot 2023-11-27 at 09 53 46](https://github.com/conbench/conbench/assets/11835246/cc126737-bb11-4e1b-94be-4ce65a10d0c3)

In case this helps (this is temporary): 
http://15.235.45.255:5000/

**Comment by austin3dickey** [comment]
Yes! I think this would be a rather simple change to https://github.com/conbench/conbench/blob/main/conbench/units.py.
