### ISSUE TITLE
Question about using 2 containers (this raises ReadTimeout error)

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1548]
Is it possible to run 2 conbench containers at  the same time? (I thought docker should let me do that). 
I need to perform tests on a server, I was already running conbench web app in a containerized fashion on port 5000. I added a second conbench installation. For this, I set it up on port 5050.
So the Makefile is now as follows:
```
.PHONY: run-app
run-app: set-build-info
	export DCOMP_CONBENCH_HOST_PORT=0.0.0.0:5050 && \
		docker compose down && docker compose up --build
```

This second version works fine if the commits have a few benchmarks (I was testing files or commits with about 60 benchmarks tests). But as soon as I use the real commits (that have more than 7000 tests), then it raises:
```
Traceback (most recent call last):
  File "/home/bench/conbench/conbench_toy/client.py", line 34, in <module>
    adapter_instance(new_file)
  File "/home/bench/conbench/conbench_toy/client.py", line 26, in adapter_instance
    adapter.post_results()
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/benchadapt/adapters/_adapter.py", line 194, in post_results
    raise error
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/benchadapt/adapters/_adapter.py", line 179, in post_results
    res = client.post(path="/benchmarks/", json=result_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/benchclients/base.py", line 63, in post
    res = self.session.post(url=url, json=json, timeout=self.timeout_s)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bench/miniforge3/envs/conbench-env/lib/python3.12/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='0.0.0.0', port=5050): Read timed out. (read timeout=75)
```

This is what docker has now:

```
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                    PORTS                       NAMES
20d62fc3c2e6   conbench-app           "gunicorn -c conbenc…"   50 minutes ago   Up 50 minutes (healthy)   0.0.0.0:5050->5000/tcp      conbench-app-1
1935cf5d15f8   dexidp/dex:v2.35.3     "/usr/local/bin/dock…"   50 minutes ago   Up 50 minutes             127.0.0.1:32793->5556/tcp   conbench-dex-1
9787a7ce4489   postgres:15.2-alpine   "docker-entrypoint.s…"   50 minutes ago   Up 50 minutes (healthy)   127.0.0.1:32792->5432/tcp   conbench-db-1
6da6d409aaa8   conbench-clone-app     "gunicorn -c conbenc…"   11 days ago      Up 11 days (healthy)      0.0.0.0:5000->5000/tcp      conbench-clone-app-1
f0b6da2e884f   dexidp/dex:v2.35.3     "/usr/local/bin/dock…"   11 days ago      Up 11 days                127.0.0.1:32776->5556/tcp   conbench-clone-dex-1
8d1b9e3360bc   postgres:15.2-alpine   "docker-entrypoint.s…"   11 days ago      Up 11 days (healthy)      127.0.0.1:32777->5432/tcp   conbench-clone-db-1
```
The first container (on port 5000) is still running, but I have not added more data. 
Is conbench's code able to handle what I'm trying to do?

**Comment by austin3dickey** [comment]
Hey, thanks for the issue!

There's nothing I know off the top of my head that would prohibit this use case. It's encouraging that it worked for smaller data. The traceback you shared indicates that once you tried larger data, the writing process started timing out.

There's [lots that happens](https://github.com/conbench/conbench/blob/4eddeecf4a33e26703b71e86e416b76062c5dce6/conbench/entities/benchmark_result.py#L172) upon writing data that could have been the bottleneck. Did container logs mention anything? It's also possible that more resources devoted to the containers might help. I'm not sure how much load the DB was under.

**Comment by DeaMariaLeon** [comment]
Thank you for your reply. It seems that I will have access to a better server. So, fixing this issue is not so important for me at this point. I spent a lot of time on it (but it was good for my learning). I do have a lot of logs that I can send to you if you are interested. Logs from the containers and logs from the server. 

Maybe I should install conbench on the new server not with the local env setup, but with a production one so I'm not experimenting. The documentation for a webapp has a link to [config.py](https://github.com/conbench/conbench/blob/main/conbench/config.py) and that's it. Would getting this config right be enough? Is that the "production" setup?
Does Arrow's conbench setup use docker at all? 

I have experience with setting up a django website, but my first contact with docker (and flask) is here, trying conbench. Any help on deciding the best approach would be more than welcome. Thanks in advance.

**Comment by austin3dickey** [comment]
>Does Arrow's conbench setup use docker at all?

Unfortunately as you've noticed, the admin process for setting up the production Conbench servers is underdocumented. It's something we're still working on ourselves. 

For Arrow, we deploy using a [Buildkite pipeline](https://github.com/conbench/conbench/blob/main/.buildkite/conbench-deploy/pipeline.yml) that builds a Docker container and deploys to Kubernetes. It's fairly custom to the specific AWS infra we have already set up, but the steps should be reusable, especially if your infrastructure looks similar (EKS, RDS, etc).

If you want to give the steps in that Buildkite pipeline a try, here are the env vars we set for Arrow:
```
APPLICATION_NAME="Arrow Conbench"
BENCHMARKS_DATA_PUBLIC=true
BUILDKITE_BRANCH=(current branch)
BUILDKITE_COMMIT=(current commit)
CERTIFICATE_ARN=(aws secret)
CONBENCH_INTENDED_BASE_URL=https://conbench.ursa.dev
DB_HOST=(rds secret)
DB_NAME=(rds secret)
DB_PASSWORD=(rds secret)
DB_PORT=5432
DB_USERNAME=(rds secret)
DISTRIBUTION_COMMITS=100
DOCKER_REGISTRY=(aws secret)
EKS_CLUSTER=ursa-2
FLASK_APP=conbench
GITHUB_API_TOKEN=(github secret)
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
NAMESPACE=default
PROM_REMOTE_WRITE_API_TOKEN=(creds for grafana cloud)
PROM_REMOTE_WRITE_ENDPOINT_URL=(creds for grafana cloud)
PROM_REMOTE_WRITE_USERNAME=(creds for grafana cloud)
REGISTRATION_KEY=(your choice)
SECRET_KEY=(I think this was deprecated)
```

**Comment by DeaMariaLeon** [comment]
Thank you so much for your reply.
