### ISSUE TITLE
api/benchmark-results: still seeing large query times

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1549]
An internal Conbench instance is seeing timeouts when hitting `/api/benchmark-results` with `page_size=1000`, `run_reason=SOME_REASON`, `earliest_timestamp=SOME_DATE`, `latest_timestamp=21_DAYS_LATER`, and `cursor=SOME_CURSOR`.

This only happens sometimes. The query seems to last for over 5 minutes. Upon retry, it typically executes in 12 seconds or 1 second depending on how recently it was last run. When it does run for a long time, according to RDS Performance Insights it typically spends all its time reading data files. When it runs for a shorter time, it's typically able to get most of its data from the shared buffer cache.

The query plan is what I expected: it scans the partial `benchmark_result_run_reason_id_idx` with the index condition being `((benchmark_result.run_reason = 'SOME_REASON'::text) AND ((benchmark_result.id)::text < 'SOME_CURSOR'::text))`. Then it filters the matching data to `((benchmark_result."timestamp" >= 'SOME_DATE'::timestamp without time zone) AND (benchmark_result."timestamp" <= '21_DAYS_LATER'::timestamp without time zone))`.

Upon a recent execution of this query, the index condition returns 80327 rows, and then the timestamp filter filters out all except 653 of them. My hunch says that if we attempt to read much fewer files we'll be in better shape, especially since we throw out 99.2% of the matching index data. One way we could do that is by providing a lower bound on `benchmark_result.id` in addition to the upper bound. We could get this by converting the `earliest_timestamp` into a UUID7.

It's a currently-known limitation that the ID corresponds to DB insertion time, which could be different from the user-given result timestamp. However, if we make the assumption that the user-given timestamp will never be _later_ than the insertion timestamp (i.e. it's unlikely that a client would submit data with a timestamp from the future; at least I don't know of any that do this), then this change should not cause any problems. Proof:
- assume insertion_time >= user_time
- today we return data where user_time >= SOME_DATE
- therefore we already return data where insertion_time >= SOME_DATE

**Comment by austin3dickey** [comment]
Wow, just tried this out locally and it was lightning fast. The query only had to read 0.8% of the data. PR incoming.

**Comment by austin3dickey** [comment]
Definitely see an improvement after this deployment (this shows a mixture of instances).
<img width="847" alt="image" src="https://github.com/conbench/conbench/assets/16600275/7ab8fc79-3082-4f3a-b225-6d5b5a273f07">

**Comment by deepsihag** [comment]
Great! 

> Definitely see an improvement after this deployment (this shows a mixture of instances). <img alt="image" width="847" src="https://private-user-images.githubusercontent.com/16600275/290323212-7ab8fc79-3082-4f3a-b225-6d5b5a273f07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDIyODIsIm5iZiI6MTcwMjUwMTk4MiwicGF0aCI6Ii8xNjYwMDI3NS8yOTAzMjMyMTItN2FiOGZjNzktMzA4Mi00ZjNhLWIyMjUtNmQ1YjVhMjczZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIxMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkODVhMWIwZGU5MjJjNmE3MjNmZjdkOTY0ODJjYWJkNTY2NDZiNzE4YmVlNTdmOTNhNDBjMTVmMzE5OGJjMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.943da4RXSjeDt8C1ygYCdx-c_34Ay1kjAN3tKisMeH8">
