### ISSUE TITLE
Import benchalerts.pipeline_steps raises

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1552]
Following the documentation [here](https://conbench.github.io/conbench/pages/benchalerts_readme.html#:~:text=os%0A%0Aimport%20benchalerts.-,pipeline_steps,-as%20steps%0Afrom) I get NotFoundError.

```
(conbench) *[algos2][~/conbench_toy]$ python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import benchalerts.pipeline_steps as steps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'benchalerts.pipeline_steps'
```

If I do `[~/mambaforge/envs/conbench/lib/python3.12/site-packages]$ ls` , `benchalerts` is listed. 
Or if I do `pip list` then there is 
```benchalerts                   2023.2.15```

and `site-packages` is included in the path:

```
>>> import sys
>>> print(sys.path)
['', '/Users/dealeon/mambaforge/envs/conbench/lib/python312.zip', '/Users/dealeon/mambaforge/envs/conbench/lib/python3.12', '/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/lib-dynload', '/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages']
``` 

I first had made an environment with mamba, when it was activated I installed the following (I think I used python -m pip):

```
pip install benchadapt
pip install benchalerts
pip install benchclients
pip install benchconnect
pip install benchrun
```

I tried several ways to access it in the script but I couldn't. 

I did have a lot of issues when I had to install the following: (but maybe I should open another issue with the details. I managed to install it but with lots of work). 
```
pip install 'conbench@git+https://github.com/conbench/conbench.git@main'    # webapp
``` 

I'm on a mac. Am I missing something? 
Thanks

**Comment by austin3dickey** [comment]
Hey, thanks for the issue. The simplest answer: [version 2023.2.15](https://github.com/conbench/conbench/tree/benchalerts-2023.2.15/benchalerts/benchalerts) does not include the `pipeline_steps` module, and we haven't released a new version to PyPI since then. I apologize for the confusion. Many users have been installing from GitHub.

I think it's fine to release new versions to PyPI at this point since we're more stable than we have been. I will do that now.

**Comment by DeaMariaLeon** [comment]
I had also installed it from GitHub, but I must have done something wrong.. sorry. And thank you again. :)

**Comment by austin3dickey** [comment]
No problem! Try `pip install benchalerts==2023.12.18 benchclients==2023.12.18` and see if that fixes your issue.

**Comment by DeaMariaLeon** [comment]
Yes, thanks. :-)
