### ISSUE TITLE
webapp: /compare/runs can still time out

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1564]
Even after recent speedups, the `/compare/runs` page can still time out if there's a sufficient number of results in the two runs. Example: hitting https://conbench.ursa.dev/compare/runs/0a6ecfdb41e1454397a9d93d12144620...8308d2cc67a646098a415f91edb959d4/ , recently @pitrou received this error: https://gist.github.com/pitrou/ec6a768455a6b5d254c6925bfabbbfee . This sometimes goes away upon a retry, but even then it takes a long time.

Strategies to mitigate:
- Can we use a similar strategy to pagination in the API endpoint, loading only some benchmark result comparisons at a time? (It's still important we eventually load all of them because the typical workflow is to sort by z-score.)
- Should we re-consider caching the "recommended comparison" z-scores? (This wouldn't help for loading other comparisons besides the recommended one, but that's a somewhat rare use case.)

**Comment by austin3dickey** [comment]
We also may be able to get the benefits of the first strategy without all the extra JS that's required for it, by implementing a pagination strategy behind the scenes. Today we make a DB query with no pagination:
https://github.com/conbench/conbench/blob/14b2a6df786403eaab6d780cf002e83c42e9e407/conbench/app/compare.py#L287
But we've seen in the past that there's a sweet spot of page size that can minimize total load time: https://github.com/conbench/conbench/pull/1547#issue-2027146165

So implementing pagination here would theoretically stop the "DB timeout" error from occurring, and could even speed up page load time. It still wouldn't be fast but it would return something, and wouldn't be a lot of work.

**Comment by DeaMariaLeon** [comment]
Hi @austin3dickey, a core dev from pandas mentioned that he waited for 15 minutes for a "compare/runs" and didn't get the results (I'm not sure if it timed-out). But I did have a time-out myself when I tried to do the same with his commit. After retrying it worked. 
I mentioned to them (to pandas devs) that work was being done to improve this. I wonder if you are discussing this issue with other people.

**Comment by austin3dickey** [comment]
Is this for the webapp page or the API? If it's for the webapp page, yes I still plan to come back to this issue soon. If someone else wants to take a shot at it they'd be welcome to as well!

**Comment by DeaMariaLeon** [comment]
Thanks a lot for your reply @austin3dickey. Yes, it's for the webapp page.

I hope I didn't sound like I was rushing you. Not at all. I appreciate very much the work that you do. I was asking because I did a presentation about using conbench (for pandas), and I wrote that work was being done on this issue. I just wanted to make sure that it was still the case. 

In case you want to see my "sales pitch": https://drive.google.com/file/d/1xTrLbocmKBoHtRzvBNUMJGTnxojRh_Sp/view?usp=sharing

**Comment by austin3dickey** [comment]
That's fantastic! Thanks for sharing!

**Comment by austin3dickey** [comment]
^ The above PR should have helped. @DeaMariaLeon if you deploy the latest changes to your instance, hopefully you'll see an improvement in `/compare/runs` webapp page load time!

**Comment by DeaMariaLeon** [comment]
Thank you @austin3dickey! And yes, it improved. The commit that was timing-out shows nicely the comparison!
