### ISSUE TITLE
webapp: display raw repetition data in plots

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1573]
After merging #1571, plots look strange and legends are incorrect:

<img width="855" alt="image" src="https://github.com/conbench/conbench/assets/16600275/a34a5078-ef96-423a-9ab6-fb4ff09f2ae2">

This plot shows a benchmark that has 3 repetitions per result. The mean used to be represented by the grey dot, and the min by the black dot. Now, both dots show the best value (min if less is better, max otherwise). 

I propose we plot the raw repetition data with the grey dot, and have the visually distinctive black dot represent the best run. This may result in a lot of grey points, but after some experience sorting through plots I think it's more instructive to be able to see the raw data. This helps identify outliers and persistent warmup effects. We can downsample in the future if performance becomes a problem.

@boshek in https://github.com/conbench/conbench/pull/1571#issuecomment-1885714749 also recommended that the hover tooltip displays the repetition number, to help with identifying patterns.

**Comment by boshek** [comment]
Two additional parameters worth tweaking to see if they visually help with this:

- adjust the opacity of the raw points to give that "background" feel and to give primacy to the "best run"
- plot the raw points with a different symbol (diamond, star, etc) to further visually distinguish this.

Not prescriptive here. Just ideas to try out.
