### ISSUE TITLE
BMRT cache: takes too long to populate, being a noisy neighbor

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1577]
I've been noticing a slowdown for internal Conbench instances on the `vd-2` cluster. I checked the RDS Performance Insights dashboard and found this for our production instance:

![Screenshot 2024-01-16 at 08 39 40](https://github.com/conbench/conbench/assets/16600275/13c75c28-4790-4be0-9bd8-7e13328f9dcf)

Scanning the code, these FETCH FORWARD 2000 queries can only be coming from here:

https://github.com/conbench/conbench/blob/76365a5952de4a827f4b6ec2996e03acf2aebe43/conbench/bmrt.py#L245-L249

That's the query that populates the BMRT cache. Sure enough, checking our Grafana dashboard:

![Screenshot 2024-01-18 at 11 59 27](https://github.com/conbench/conbench/assets/16600275/165dabcf-32db-4252-861f-be2835926371)

I see a big variance in how long it takes to populate that cache, with an unfortunately long tail (as big as 50 minutes!) Those individual FETCH FORWARD queries are quite often taking 5-20 minutes to complete, and I notice that other queries that get executed at the same time end up being much slower than I'd ordinarily expect. (This is probably clobbering the shared buffer cache as well, which would otherwise help speed up common queries.)

Interestingly, over the same time range the `ursa-2` time-to-populate dashboard has been remarkably-consistently hovering around 4 minutes. Perhaps the reason: for the respective benchmarking frequencies, the default BMRT_CACHE_SIZE of 800_000 goes back only a few days for Arrow and a few years for the internal database. Due to the index on timestamp, it makes sense to me that the Arrow query would go faster, since the index provides a much smaller search space.

If that's the case, I propose filtering this query to the last 2 weeks. This matches the filter on the recent-runs query that we recently added in #1546, and I think a tail-end of 2 weeks in this cache will be acceptable to users.

**Comment by austin3dickey** [comment]
When I deployed to staging yesterday, the time-to-populate went from about 4 minutes to 2 seconds on average. Good sign. Will deploy to the problematic instance soon.

<img width="837" alt="image" src="https://github.com/conbench/conbench/assets/16600275/7f7bab0d-68e1-44c4-ad23-8cc8cd19de40">

**Comment by austin3dickey** [comment]
Deployed 20 minutes ago. Might be too early to draw conclusions but this is promising to me.
<img width="842" alt="image" src="https://github.com/conbench/conbench/assets/16600275/a956290a-72fc-4990-98e3-d1ce1fc70fd3">

**Comment by austin3dickey** [comment]
Also promising: the obvious change in how these cache queries are working (deployed around 16:00 on this graph). Now they're running much quicker and are waiting mostly for CPU, not DataFileRead.

<img width="1552" alt="image" src="https://github.com/conbench/conbench/assets/16600275/56a00468-d6eb-4507-a541-5fca3aa26fef">
<img width="1561" alt="image" src="https://github.com/conbench/conbench/assets/16600275/88c45930-775e-4c6f-8307-16bc1ea8a131">

**Comment by austin3dickey** [comment]
Yes, this made a huge difference.
<img width="839" alt="image" src="https://github.com/conbench/conbench/assets/16600275/c15afbc4-7952-4a28-8806-feddfd60565c">

I think the lack of a noisy neighbor helped the speed of the API and webapp as well.

<img width="840" alt="image" src="https://github.com/conbench/conbench/assets/16600275/0d29ba9d-e71e-4a94-a721-e136a18329cc">

**Comment by jgehrcke** [comment]
This was a nice read, thanks for those screenshots, too. Hello to Austin! :)
