### ISSUE TITLE
Ability to mark a commit as a discontinuity in the distribution history

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#171]
[feature request, copied here]

https://conbench.ursa.dev/compare/benchmarks/465d5a3b22934130a72fc56c587812b3...78e93bfac47647c3b432cc10c0ef0f36/ is super cool and I'm very excited that it exists!

Now that it does, I can see what's happening with the standard errors when we have a performance regression: they blow up for a long time. So when we fix the performance regression, it doesn't show up as a statistically significant change.

It seems like we should be able to mark a commit as a discontinuity in the time series and have a moment in time where the mean and sd adjust to the new level. Aside from the metrics themselves, it would make for a more interesting plot.

**Comment by jonkeane** [comment]
We have a few different directions that we could go here with at least two main areas of decisions: (1) how to identify discontinuities and (2) what to do about them?

On (1) how to identify discontinuities, we could:
* Do like Neal suggests, and create something in the API that we can declare a specific commit to be a discontinuity point for a specific benchmark. This is nice cause it brings in some human judgement and we can hopefully use that to refine any sort of automatic identification we do in the future
* We could also try marking any event that is outside of our alert threshold (or alert threshold * 2) as a discontinuity. (we could mix these two, and have something in the API that would let us say "no no this isn't really a discontinuity"

On (2) what to do about these discontinuities:
As a first-step, we could try to estimate the variance only in each discontinuous group. Generally what we would do there is: for each commit assign it some indicator (could be an int += 1, could be UUID, doesn't really matter) that only increments/changes when there is a discontinuity (from above). Once we have that, we can [alter the distribution table calculations](https://github.com/conbench/conbench/blob/0f924bb247a9608d5411d5a802b5d3a0aa5dd42c/conbench/entities/distribution.py#L87-L121) to scale each discontinuity group's means within themselves, and calculate the sd on the scaled means. This will give us an estimate of the variance regardless if there is a sudden large shift up or down.

A toy explanation of how this works:
```
> # Two distributions, one centered around 1, the other around 10
> dist_1 <- rnorm(n = 1000, mean = 1, sd = 2)
> dist_2 <- rnorm(n = 1000, mean = 10, sd = 2)
> 
> # if we simply take the `sd()` of both together, we get an sd >> 2
> sd(c(dist_1, dist_2))
[1] 4.921398
> 
> # but if we scale each to the mean, we get an sd much much closer to 2
> sd(c(dist_1 - mean(dist_1), dist_2 - mean(dist_2)))
[1] 1.993544
> 
```

We might need to do something special in the case of the first observation within a discontinuity-group to make sure we don't let a handful of observations change something important.

When we get started on this in earnest, I'll grab the data from a discontinuity like this via the API/DB and plot out a similar plot before/after calculations like this to confirm it's doing what we would like it to.

**Comment by jonkeane** [comment]
We have expanded this idea into a number of tickets at https://github.com/conbench/conbench/issues/472 https://github.com/conbench/conbench/issues/473 https://github.com/conbench/conbench/issues/474 https://github.com/conbench/conbench/issues/475 https://github.com/conbench/conbench/issues/476 https://github.com/conbench/conbench/issues/477 which should substantively cover this use case.

**Comment by jgehrcke** [comment]
Maybe I have not spent enough time on all the related tickets, but I find it really really important to distinguish:

i) annotate expected, explainable, permanent change (reset statistical aggregate calculation at a certain point in time)
ii) annotate an outlier (exclude a data point from statistical aggregate calculation)

I think that this ticket here was mainly about (i), right? Focusing on this statement:

> what's happening with the standard errors when we have a performance regression: they blow up for a long time. So when we fix the performance regression, it doesn't show up as a statistically significant change.

**Comment by jonkeane** [comment]
It was originally intended to capture both — though it didn't really have much detail to make it clear it was  covering both of those
