### ISSUE TITLE
Tweaks to tooltips in the history plot

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#181]
The tooltips in the history plot are great, being able to see the values exactly. Though it can sometimes be slightly confusing that you can get a tooltip for the mean of means line (the orange) and sometimes for the contender mean value. 

We have a few options, none are necessarily mutually exclusive:
* we could try to put something in the tooltips that tells you which one you're getting
* we could disable the mean-mean line (it's not _super super_ common that one wants the exact value from that)
* something else if the visualization framework supports it (like a vertical line that lists all the values at that point in time: the contender mean, the mean-mean, the alert thresholds).

**Comment by dianaclarke** [comment]
Tooltip was removed from all but the history line and benchmark dot:

- [Only add tooltips to history line and benchmark circle (#214)](https://github.com/conbench/conbench/commit/c2c3f7b0bb1823b15aec88a7ce075c27e244f2a4)

**Comment by dianaclarke** [comment]
@jonkeane Let me know if that's good enough to close this ticket. Thanks!

**Comment by jonkeane** [comment]
Yup, that's good!
