### ISSUE TITLE
Support GitHub App JWT Authentication

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#185]
Use env var: `GITHUB_APP_TOKEN`

See: https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps

Code that needs to change is here: https://github.com/conbench/conbench/blob/86228abc483ab9612556cfaab5d9afd349fe3f92/conbench/entities/commit.py#L226

**Comment by jgehrcke** [comment]
Closing for now, let's revisit if it makes sense.
