### ISSUE TITLE
Lookup a runid from a git hash?

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#194]
is there an API-way of getting a run id (or all the run ids) associated with a githash? E.g. I know which two commits I wanted to compare, and I ended up using the UI + hardcoding their run ids, but it would be slick to be able to do that programmatically.
 
And a possible extension of this is to go from two git hashes to a (set of) comparison(s) between those two. This set of comparisons might need some new UI since two commit hashes might have a set of runs (e.g. those runs on different systems)

**Comment by dianaclarke** [comment]
> is there an API-way of getting a run id (or all the run ids) associated with a githash? 

Yup!

Here's an example: https://conbench.ursa.dev/api/runs/?sha=62ff6590fc43e83381a8ec722a9c241a49619c78

That part of this issues was fixed in https://github.com/conbench/conbench/commit/4e7bae77ed1da548bc390b859594caf4da42863b
