### ISSUE TITLE
Add conbench version to lib, API, and UI

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#199]
The Conbench version is currently specified in setup.py:

   https://github.com/conbench/conbench/blob/main/setup.py

```
setuptools.setup(
    name="conbench",
    version="1.33.0",     # <------ Conbench version
    description="Continuous Benchmarking (CB) Framework",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(),
    entry_points={
        "console_scripts": [
            "conbench=conbench.cli:conbench",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: MIT License",
    ],
    python_requires=">=3.8",
    maintainer="Apache Arrow Developers",
    maintainer_email="dev@arrow.apache.org",
    url="https://github.com/conbench/conbench",
    install_requires=install_requires,
)
```

Perhaps do something similar to what arrow does:

```
>>> import pyarrow
>>> pyarrow.__version__
'5.0.0'
```

And also place it in the footer of the UI.

I'm not sure of the top of my head where it belongs in the API, but lib & UI would be a great start.

**Comment by drabastomek** [comment]
@dianaclarke Should this be tied to a version from Github? In the past I've used `versioneer` but not sure if this is what you had in mind: https://github.com/drabastomek/azureml-ngc-tools/blob/master/setup.py

**Comment by dianaclarke** [comment]
@drabastomek Thrilled to hear you're interested in taking this task on! I'm not familiar with `versioneer`, but it looks neat. I'm also open to the simplest possible thing that works too. Up to you :) Let us know if you have any questions along the way. Thanks again!

**Comment by dianaclarke** [comment]
@drabastomek Apologies for not answering clearer.

> Should this be tied to a version from Github? 

No, although having a way to get the git hash too would be a nice-to-have.

The version should be a semantic version: `major.minor.patch` (1.33.0, 1.34.0, etc.)

- https://semver.org/

I haven't been very strict about distinguishing between API breaking changes and not though. I've mostly just been incrementing the minor version for now.

**Comment by drabastomek** [comment]
@dianaclarke My current thinking is to use `setuptools_scm` just like Apache Arrow does: https://github.com/apache/arrow/blob/721aa019aa0cb3b6a15aa358a53f39e2c5c541ae/python/setup.py#L606 This way, we only need to set the `git tag -a conbench-v.1.xx.x -m "conbench version 1.xx.x"`. This should have the added benefit of being able to track the commits where version change occurred. Thoughts? 

Prototype already works:
```
(base) tom@opportunity:/fastdata/conbench$ python setup.py --version
1.33.0a0
(base) tom@opportunity:/fastdata/conbench$ git tag
conbench-1.33.0
```

**Comment by dianaclarke** [comment]
@drabastomek Sounds great! 

And would `python setup.py --version` return just `1.33.0` rather than `1.33.0a0` if the repo wasn't dirty?

**Comment by drabastomek** [comment]
@dianaclarke That definitely can be done :)

**Comment by drabastomek** [comment]
Tracking this work in #201

**Comment by dianaclarke** [comment]
I just looked at what [ibis](https://github.com/ibis-project/ibis) does, and perhaps something like this is good enough. And then add that to the footer of the UI.

```
$ git diff
diff --git a/conbench/__init__.py b/conbench/__init__.py
index d1561b0..b3a21d5 100644
--- a/conbench/__init__.py
+++ b/conbench/__init__.py
@@ -1,5 +1,9 @@
 import os
 
+import importlib.metadata as importlib_metadata
+
+__version__ = importlib_metadata.version(__name__)
+
 
 def create_application(config):
     import flask as f
```

```
>>> import conbench
>>> conbench.__version__
'1.33.0'
>>> 
```

I'm not sure what the additional use-cases are for `versioneer` and `setuptools_scm`, but perhaps until we need them keeping it simple might be the best plan.

PS. The ibis code does this, so perhaps we need the exception case too. I'm not sure.

https://github.com/ibis-project/ibis/blob/99491a03eb2815188fa5c4945a356425925e495d/ibis/__init__.py#L56

```
try:
    __version__ = importlib_metadata.version(__name__)
except Exception:
    __version__ = importlib_metadata.version("ibis-framework")
```

**Comment by drabastomek** [comment]
I already implemented the `setuptools_scm` in setup.py. This has the added benefit that if you're working off of a dirty version -- it'll show the hash of the latest commit. Additionally, with tags we can keep the track of the versions in github so it's immediately known which commit is the beginning of the new version. But I'm happy to change it back to use the `version=1.33.0` in the setup.py. Let me know.

I exposed the version in CLI as `conbench version` and in the lib in the same way that Ibis is doing it. You should be now able to `import conbench; print(conbench.__version__)`. 

For the API -- I think  the best place  would be in the `/api/ping` route. 
![image](https://user-images.githubusercontent.com/3249948/138394413-e9237d08-715d-4ba9-8e2a-a398574115c2.png)
As for the UI -- IMO the best place would be to include it in the title
![image](https://user-images.githubusercontent.com/3249948/138395019-c1da6822-8ed2-424a-943e-bff513ebcac1.png)

**Comment by dianaclarke** [comment]
> I already implemented the setuptools_scm in setup.py. 

I saw, and totally felt bad about the effort you already put in (much appreciated though!), but when I tested it I got the following which I don't think will work for PyPI. That said, I'm sure it could be configured to work.

https://pypi.org/project/conbench/#history

```
$ python setup.py --version
<ScmVersion 1.33.0 d=0 n=g4e7bae7 d=True b=main>
1.33.0+gg4e7bae7.dev0
```

> For the API -- I think the best place would be in the /api/ping route.

Good call.

> As for the UI -- IMO the best place would be to include it in the title

I'm not loving it in the header. I'd prefer it was somewhere less conspicuous - like the footer

We could also just omit it from the UI entirely, if it's in the API.

Thanks so much for working on this!

**Comment by drabastomek** [comment]
> when I tested it I got the following which I don't think will work for PyPI.

I think you might be on an earlier commit. I am getting the following
```
$ python setup.py --version
1.33.0
```
On a dirty branch I am getting 
```
$ python setup.py --version
1.33.0+ggcf00bd8.dev6
```
> I'm not loving it in the header. I'd prefer it was somewhere less conspicuous - like the footer
> We could also just omit it from the UI entirely, if it's in the API.

Lemme try the footer.

**Comment by drabastomek** [comment]
Moved to the footer. 
![image](https://user-images.githubusercontent.com/3249948/138499501-224dbbbb-bcd7-409e-abf2-677a03f361fc.png)

**Comment by dianaclarke** [comment]
Fixed in https://github.com/conbench/conbench/pull/201

Thanks @drabastomek!!
