### ISSUE TITLE
Plot cycling?

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#212]
The new regression plots for runs (e.g. https://conbench.ursa.dev/runs/77dcf7602880453aa59ad2f990ba3f2c/) are fantastic.

Would it be possible to stop them from autoscrolling (possibly with an option to turn that on) and instead manually click left/right. Alternatively, would we be able to stack them vertically so all the plots are there, they just run down the screen (either above or below the table).

**Comment by dianaclarke** [comment]
I added dots to jump between plots, but I left the scrolling on. Note that if you put your mouse over the graph, it will stop scrolling and let you just read that particular graph.

<img width="1146" alt="Screen Shot 2021-10-28 at 1 12 59 PM" src="https://user-images.githubusercontent.com/878798/139320685-0a6c7782-25b6-4c8f-9e5f-f89e70c9c990.png">

**Comment by jgehrcke** [comment]
Closing this in favor of https://github.com/conbench/conbench/issues/551.
