### ISSUE TITLE
Sphinx docs? Read the docs?

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#235]

**Comment by jgehrcke** [comment]
Closing either as of lack of context or because quite a bit of time passed -- let's create new tickets once special need arises.

**Comment by austin3dickey** [comment]
Going to reopen this and timebox myself to doing what I can by tomorrow. I've set up a system like this on many other projects. It works well.

1. Set up a `docs_src` folder at the root of the repo with `sphinx-quickstart`.
2. Use sphinx autodoc to autogenerate RST docs for all our python libraries.
3. Add a step in CI that tests that the sphinx docs are buildable without any warnings.
4. Create a GitHub Action workflow that knits the RSTs into HTML and commits the HTML into a `docs` folder at the root of the repo. This will be manually kicked off. (Maybe at the same time as deployment.)
5. Set up GitHub Pages for this repository to read from the `docs` folder.

**Comment by jonkeane** [comment]
My biggest ask is if we can please use markdown instead of rst? Markdown is so much more pervasive + makes it easier to get more content into docs without someone (me) having to remember how RST differs.

**Comment by austin3dickey** [comment]
Yes, there's a good plugin that allows for documenting in Markdown. I'm planning to include that so the READMEs can also be knitted into HTML.

We may need to still use RST for the `autodoc` pages that autogenerate the python library docs, because RST has the support for directives that Markdown is missing. But we can definitely keep only the boilerplate pages in RST, and write our actual content in Markdown (and whatever format we use in python docstrings).

**Comment by jonkeane** [comment]
> We may need to still use RST for the autodoc pages that autogenerate the python library docs, because RST has the support for directives that Markdown is missing. But we can definitely keep only the boilerplate pages in RST, and write our actual content in Markdown (and whatever format we use in python docstrings).

_nods_ yeah the (auto)doc from doc strings I'm a lot less worried about — but the more detailed content that we know we need, I don't want "UGH RST" to be the blocker :) Thanks!

**Comment by jgehrcke** [comment]
Thanks for the plan! Some thoughts :)

Let's always carefully distinguish:

1) general documentation for Conbench
2) library documentation generated from code and docstrings

(1) is as of today more important to build than (2).

For (2) yes we should do the work with proper code annotation (types, docstrings, ...). But for _consumers_ of this a good, modern IDE helps the most!

The general documentation (1) should render nicely in the GitHub UI straight from Markdown files. Would love to have explicit alignment on this one.

> Set up a `docs_src` folder at the root of the repo

`docs`, please :pray: 

> commits the HTML into a docs folder at the root of the repo. This will be manually kicked off. (Maybe at the same time as deployment.)

Oh! I would want to veto this :broken_heart:. If we are ever going to have a 'build website from code, and then deploy this website' kind of task then this _can_ of course be executed in the context of the conbench/conbench repo.

But if an implementation detail of "deploy this website" is to "commit the HTML somewhere" then the tree of static files itself is rather ephemeral and should certainly not go into conbench/conbench, just as one would typically also not check in binaries (the result of compilation, too).

**Comment by jonkeane** [comment]
> (1) is as of today more important to build than (2).

Strong agreed 

> Oh! I would want to veto this 💔. If we are ever going to have a 'build website from code, and then deploy this website' kind of task then this can of course be executed in the context of the conbench/conbench repo.
> 
> But if an implementation detail of "deploy this website" is to "commit the HTML somewhere" then the tree of static files itself is rather ephemeral and should certainly not go into conbench/conbench, just as one would typically also not check in binaries (the result of compilation, too).

The default for ghpages is deploy from a separate branch which contains the HTML (and frequently doesn't contain the rest of the code). The build website action then can (and should IMO) do the rendering -> pushing the rendered content to the special ghpages branch but no reason to keep the rendered files around in the main (set of) branch(es). How does that sound?  Any reason to deviate from that default?

**Comment by jgehrcke** [comment]
> should certainly not go into conbench/conbench

clarification: into the default/main branch. Thanks! :)

**Comment by austin3dickey** [comment]
Actually, it looks like GitHub Pages has a new [action](https://github.com/actions/deploy-pages) that's used to deploy a website without needing to ever commit the HTML to the repository! That will be the simplest way to set this up.

I agree that your (1) is way more important than (2) because of IDEs, and that (1) is already available via clicking around the repository and viewing GitHub Markdown. But (1) is still a pain point for users today. I think GitHub Pages is a low-effort way to set up something that's easily explorable, self-linkable, and all in one place (without code clutter).
