### ISSUE TITLE
Add run description (differs from run name)

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#239]

**Comment by jgehrcke** [comment]
A free text field for describing the purpose and context of a specific run might indeed be useful.

**Comment by alistaire47** [comment]
There is an `info` dict field on a run that I think could fit this type of information? I'm not sure we're populating it with anything beyond `{}` for the most part right now

**Comment by jonkeane** [comment]
Yeah, the run `info` dict | JSON does sound like the pattern of free(ish) form data we've done at a few levels (the run level, the benchmarkresult level, etc.).

So maybe we can close this as done for now and we should track what folks are putting in that run `info` and pull things out that seem common?

**Comment by austin3dickey** [comment]
And as we've discussed in https://github.com/conbench/conbench/issues/607, `run_name` could be a good place for a free-text field describing the purpose/context of the run. This issue was created before we ripped out the code that needed `run_name` to be in a specific format.
