### ISSUE TITLE
Is the schema up-to-date?

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#282]
Alembic is detecting the following differences between the code and a dump of the arrow benchmarks DB.

```
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_summary_id', table_name='data')
    op.create_index('data_summary_id_index', 'data', ['summary_id'], unique=False)
    op.drop_index('summary_context_id', table_name='summary')
    op.create_foreign_key(None, 'summary', 'run', ['run_id'], ['id'])
    op.drop_index('ix_time_summary_id', table_name='time')
    op.create_index('time_summary_id_index', 'time', ['summary_id'], unique=False)
    # ### end Alembic commands ###
```

**Comment by jgehrcke** [comment]
@austin3dickey if you find the time could you maybe look at this and see if this is still relevant?

**Comment by austin3dickey** [comment]
None of these are true anymore, but there is one difference today:
```py
op.create_foreign_key(None, 'benchmark_result', 'run', ['run_id'], ['id'])
```
The Arrow database is missing this foreign key that is present in the code.

This difference is not present in the Velox database.

**Comment by austin3dickey** [comment]
@ElenaHenderson ran a manual migration to fix the above issue. I think we can close this ticket.
