### ISSUE TITLE
Add machines page to UI so users can view all machines and their specs in one place

### ISSUE THREAD

**Issue by ElenaHenderson** [conbench/conbench#299]

**Comment by jonkeane** [comment]
Questions from @Christian8491 :

> Where can I find all the machines we are using?

The machines are all in the hardware table (the hardware entity is defined in https://github.com/conbench/conbench/blob/main/conbench/entities/hardware.py). Likely what you'll want to do is create a hardware page in https://github.com/conbench/conbench/tree/main/conbench/app that displays the info in that table

> The information we want to capture is the same that "hardware" label holds ?

This ticket is mostly for displaying the info that we already capture. We can add more info to hardware in our runners if we want, but let's display what we have now, and then we can make sure it is extensible + will display additional extra info when we get there.

**Comment by Christian8491** [comment]
> The machines are all in the hardware table (the hardware entity is defined in https://github.com/conbench/conbench/blob/main/conbench/entities/hardware.py). Likely what you'll want to do is create a hardware page in https://github.com/conbench/conbench/tree/main/conbench/app that displays the info in that table

Sorry but what hardware table are you talking about ? What I can see from https://github.com/conbench/conbench/blob/main/conbench/entities/hardware.py#L37-L52 is only the specs from a Machine.  How a user can see all the machines ? (if it is what this PR is supposed to).

**Comment by jonkeane** [comment]
Hardware is the parent class. There are two kinds: machines (for single machine infrastructure) and clusters (for multi machine infrastructure).

So for this ticket we will want one page that lists all the available hardware (both machines and clusters) in a table. And then also a page that shows all the detailed information about the specific piece of hardware. This is similar to how we have a runs page that lists all runs and then you click through and see the benchmarks that ran as that particular rub.
