### ISSUE TITLE
Have different levels of alerting?

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#307]
The situation described at https://issues.apache.org/jira/browse/ARROW-15785 is something we've seen a handful of times — a PR causes regressions, but for whatever reason folks didn't realize that the benchmarks were run + had a number of quite large regressions. In this case, the benchmarks showed a pretty massive regression (for regressed benchmarks, the Z-scores were from -76 to -759)

We might consider any of the following which might help this case (alone or in combination). Of course, some of these might be things that are actually changed in https://github.com/ursacomputing/arrow-benchmarks-ci .

* Raising our threshold of Z-score < -5 for labelling as a regression (if we think this is an example of alarm fatigue)
* Adding a second comment instead of only editing the first comment if we see regressions (this would trigger another email to those subscribed to the PR on github + mark it in their notifications). We could also always have a second comment when the benchmarks finish that say "Hey go check them out they're ready now?
* Possibly have a second level (or aggregate across z-scores, e.g. "if the sum of z-score changes is > 200, something is likely very wrong, so alert then") for reporting that something happened with a PR and do this with a little bit more noise. 

Thoughts @ElenaHenderson ?

**Comment by ElenaHenderson** [comment]
@jonkeane and I discussed this and we agreed that [arrow-benchmarks-ci](https://github.com/ursacomputing/arrow-benchmarks-ci) will make the second comment when all benchmark builds associated with PR are done and when either of these conditions is met:
1) contender machine run has at least one Python or R benchmark with Z-score < -10.0
2) sum of all negative Z-scores for a contender machine run's Python and R benchmarks < -200.0

I will post a PR associated with this change in [arrow-benchmarks-ci](https://github.com/ursacomputing/arrow-benchmarks-ci) once I am done working on it.

**Comment by ElenaHenderson** [comment]
This is done in https://github.com/ursacomputing/arrow-benchmarks-ci/pull/66
