### ISSUE TITLE
Let users focus on specific language

### ISSUE THREAD

**Issue by domoritz** [conbench/conbench#311]
For example https://conbench.ursa.dev/compare/runs/9292568e6e4b4c1882d0564bf8ebc3e7...9aef9573adc0475d88c70056788a4875/ is only relevant to the JS tests since there are no changes in the other directories. It would be great to easily filter to JS only.

**Comment by dianaclarke** [comment]
If you type "Javascript" in the search box, it will limit the datatable to just Javascript benchmarks.
<img width="1190" alt="Screen Shot 2022-03-08 at 9 26 22 AM" src="https://user-images.githubusercontent.com/878798/157281323-8830148f-a798-459d-9aff-4847a36e1b18.png">

**Comment by domoritz** [comment]
Ahh, I missed that at first. It would be awesome if the filter was also persistent in the URL so that we can easily share a link to a relevant subset.
