### ISSUE TITLE
Add `include_in_history` attribute to runs

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#350]
Currently, we decide whether to include a run in history by parsing the string for `^commit:`. This is a flaky convention that currently does the job of excluding manual runs, but could be more stable.

A better solution is to include an `include_in_history` boolean attribute on runs, which stores whether to include that run in history or not. Users may request this along with run name and run ID when submitting a run.

_Originally posted by @ElenaHenderson in https://github.com/conbench/conbench/issues/347#issuecomment-1147983741_

**Comment by austin3dickey** [comment]
I'm still deciding what to do by default if the user doesn't explicitly request this attribute. We could
1. not include by default
2. include by default
3. include if the run name starts with "commit:" by default, else not include

(3) would allow us to be slow about migrating CI processes, but then we'd still have flaky code in the repo. I'm leaning toward (2).

@ElenaHenderson @jonkeane thoughts?

**Comment by jonkeane** [comment]
This doesn't address the default question, but we might consider instead of a Boolean, we actually use a string so that we could have distinct sets of histories (this would be most useful if we had more than one long running branch) 

This would also unlock the ability to have some information from a PR branch contribute to history. When (and only when) that is relevant.

**Comment by austin3dickey** [comment]
A better solution is to handle all this automatically so the user doesn't have to ever think about what to put down.

We want the history commits to be the N preceding commits, which might be on that branch, might be on the parent branch, etc.

**Comment by austin3dickey** [comment]
This is done thanks to many changes in https://github.com/conbench/conbench/milestone/1 .
