### ISSUE TITLE
Conbench fails with urllib 1.25

### ISSUE THREAD

**Issue by jorisvandenbossche** [conbench/conbench#363]
You get an error about "TypeError: __init__() got an unexpected keyword argument 'allowed_methods'", because the `Retry` class only got that keyword in a more recent release.

(version 1.26 is already almost two years old, so this might not be a common issue to run into)

**Comment by jgehrcke** [comment]
Closing either as of lack of context or because quite a bit of time passed -- let's create new tickets once special need arises.
