### ISSUE TITLE
If I post an empty `context` for a run, I get a 500 when I click on the run in the UI

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#365]
We should either allow contexts to be empty or we should reject the `POST` if context must have at least one key.

**Comment by jgehrcke** [comment]
Oh. Does an empty context ever have meaning? Otherwise, sounds like the input validation should be tweaked so that each persisted (2xx-acked) context is meaningful and can be meaningfully displayed.

**Comment by jonkeane** [comment]
We've never had a circumstance where we've purposefully wanted an empty context (in other words, there's always been some details about the context of a benchmark run we've wanted to save). But it's possible that some style of running might not need or want to provide that information.

I would be ok either way that we handle this (either requiring it to be non-empty, or changing the display to ignore if it doesn't exist)

**Comment by jgehrcke** [comment]
I played with this a bit.

The current run schema seems to not allow for a `context` property (that's the schema as shown by the API docs):
```
{
  "cluster_info": {
    "info": {},
    "name": "string",
    "optional_info": {}
  },
  "error_info": {},
  "error_type": "string",
  "finished_timestamp": "2022-11-16T12:45:32.192Z",
  "github": {
    "branch": "string",
    "commit": "string",
    "pr_number": 0,
    "repository": "string"
  },
  "id": "string",
  "info": {},
  "machine_info": {
    "architecture_name": "string",
    "cpu_core_count": 0,
    "cpu_frequency_max_hz": 0,
    "cpu_l1d_cache_bytes": 0,
    "cpu_l1i_cache_bytes": 0,
    "cpu_l2_cache_bytes": 0,
    "cpu_l3_cache_bytes": 0,
    "cpu_model_name": "string",
    "cpu_thread_count": 0,
    "gpu_count": 0,
    "gpu_product_names": [
      "string"
    ],
    "kernel_name": "string",
    "memory_bytes": 0,
    "name": "string",
    "os_name": "string",
    "os_version": "string"
  },
  "name": "string",
  "reason": "string"
}
```

**Comment by jgehrcke** [comment]
I built a test to POST a run with a context property. It failed schema validation:
```
    def test_create_run_empty_context(self, client):
        self.authenticate(client)
        payload = _fixtures.VALID_RUN_PAYLOAD.copy()
        payload["context"] = {}
        resp = client.post(self.url, json=payload)
        print(resp.text)
>       assert resp.status == 201
E       AssertionError: assert '400 BAD REQUEST' == 201
E        +  where '400 BAD REQUEST' = <WrapperTestResponse 84 bytes [400 BAD REQUEST]>.status
```

Response body was
```
{"code": 400, "description": {"context": ["Unknown field."]}, "name": "Bad Request"}
```

**Comment by jgehrcke** [comment]
I have seen https://github.com/conbench/conbench/blob/353f1f9cf7dceb42cd287d8a0035b1ef9259dba5/conbench/tests/api/_fixtures.py#L49 which somehow indicates that in the past there was a run schema which allowed for `context` to be set on the run. That payload there named `VALID_PAYLOAD` is not valid anymore today:
```
{"code": 400, "description": {"batch_id": ["Unknown field."], "context": ["Unknown field."], "id": ["Missing data for required field."], "optional_benchmark_info": ["Unknown field."], "run_id": ["Unknown field."], "run_name": ["Unknown field."], "run_reason": ["Unknown field."], "stats": ["Unknown field."], "tags": ["Unknown field."], "timestamp": ["Unknown field."], "validation": ["Unknown field."]}, "name": "Bad Request"}
```

The current API still allows for fetching contexts. There is a handler for GET /api/contexts. I only skimmed the API docs briefly, and after that I am still unclear if and how with today's API we can create new contexts. Maybe the context is a legacy concept by now, and the current API allows for getting old data? Will inspect more later.

**Comment by jgehrcke** [comment]
I see, `context` now seems to be a property on Benchmark, not anymore on Run: https://github.com/conbench/conbench/blob/353f1f9cf7dceb42cd287d8a0035b1ef9259dba5/conbench/entities/benchmark_result.py#L380

**Comment by jonkeane** [comment]
Thank you for all the details here as you dig through this. 

Yeah, the original description of the issue is a bit misleading here. The concept of a run that was separate from the benchmarks that formed the run is actually relatively new (introduced in #405). Before that, the information that was associated with the run came from the `POST`s to the benchmarks endpoint it self.

In case it's helpful: the (very under-documented) intention is that context is information about how the system is configured when the benchmark is run (what language it's from, the compiler flags used, possibly default engine settings, etc, see below for an example from conbench). 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/700357/202203046-6b284be4-7b88-4212-b119-8562433927a5.png">

And more helpful for this issue: the intention is for a run to be able to have multiple contexts (though still a small number of unique contexts per run), but each benchmark itself is run in only one context. So we originally grabbed the context information with the `POST` to benchmark.

**Comment by jgehrcke** [comment]
Thanks @jonkeane! 

Quick question:

> I get a 500 when I click on the run in the UI

Do you happen to remember which API endpoint responded with the 500? 

In current `main` one can create a benchmark with an empty context. The resulting benchmark object returned by the API has a link to a context. When GETting that context one gets all the metadata of that 'emtpy' context, and no payload properties. For example:
```
GET http://localhost/api/contexts/1bf3ddc82c13409bae6b958c7bcffa5d/

-->

{
  "id": "1bf3ddc82c13409bae6b958c7bcffa5d",
  "links": {
    "list": "http://localhost/api/contexts/",
    "self": "http://localhost/api/contexts/1bf3ddc82c13409bae6b958c7bcffa5d/"
  }
}
```

Do we consider that sane? 

To be explicit: one can GET the benchmark associated with the empty context, and one can also GET the empty context itself, i.e. maybe the 500 response that you had mentioned in the original report doesn't even exist anymore.

**Comment by jgehrcke** [comment]
That is, let's see if we can still repro the original issue, otherwise we can close this I think. https://github.com/conbench/conbench/pull/405 indeed changed a lot :). One interesting action item though is to lock in / cover the create-benchmark-with-empty-context scenario in the test suite. Will do.

**Comment by austin3dickey** [comment]
Does this part of the benchmark-entity HTML template still work with an empty context?
https://github.com/conbench/conbench/blob/353f1f9cf7dceb42cd287d8a0035b1ef9259dba5/conbench/templates/benchmark-entity.html#L195-L200

**Comment by jgehrcke** [comment]
> Does this part of the benchmark-entity HTML template still work with an empty context?

Thanks for the pointer! In my video call with Jon yesterday he also let me know that it was actually the template rendering endpoint which emitted the 500 response, which answers my question from above:

> Do you happen to remember which API endpoint responded with the 500?

**Comment by jgehrcke** [comment]
> Does this part of the benchmark-entity HTML template still work with an empty context?

Seems so, yes. Just adding a test for that scenario.

**Comment by jgehrcke** [comment]
I think this can be closed. Let's revisit with more specific tickets if needed.
