### ISSUE TITLE
Make history duration configurable

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#379]
Right now we have a fixed window of history as the last 100 commits https://github.com/conbench/conbench/blob/2977fcda6af0ccacff88e76777fd333fe8b85bec/conbench/entities/benchmark_result.py#L171 (we should confirm this is actually where that's coming from + that this is actually what's happening. I'm 90% certain this is, but not completely certain!)

Can we make this value be configurable (still default to 100), just like our other configuration values (an env var that we deploy with, cf https://github.com/conbench/conbench/blob/main/conbench/config.py). We have at least one deployment of conbench which would rather use a longer time period even if it means more false negatives.

**Comment by jgehrcke** [comment]
Connecting the dots. Here is a discussion about what this number means, and about the trade-off between number of commits vs timeframe of commits:

https://github.com/conbench/conbench/pull/636#issuecomment-1412691736
https://github.com/conbench/conbench/issues/474

> The second point is slightly too broad with our implementation: for the purposes of calculating mean we only look at within-distribution data (e.g. "forget the past, all of it!"). For the purposes of calculating standard deviation we use all of the data (well, limited in scope to the last 100 commits, but see https://github.com/conbench/conbench/issues/473#issuecomment-1375958359 for details about what we should implement on that front in the future — let's not distract this discussion with rehashing that here).

https://github.com/conbench/conbench/issues/473#issuecomment-1375958359
