### ISSUE TITLE
Swagger docs don't give option to poke at live server

### ISSUE THREAD

**Issue by ericdill** [conbench/conbench#393]
I'm currently looking at the Swagger docs for a conbench instance and the only server dropdown choice is localhost
![image](https://user-images.githubusercontent.com/6223243/194589781-dea24743-961e-4ad9-9e6c-1475d1f45d53.png)

I accessed the swagger docs by clicking on 'API Docs' after logging in to conbench, so I'm already auth'd to the server. I'd expect to see the active server as the default option on the above dropdown

![image](https://user-images.githubusercontent.com/6223243/194590212-2380a958-fda6-4ad6-93bc-37d6830464d4.png)

**Comment by jonkeane** [comment]
A public example of swagger docs: https://conbench.ursa.dev/api/docs/#/

Could adding `DB_HOST` and `DB_PORT` to https://github.com/conbench/conbench/blob/fdb30f2934481989e981c49837506c0622d6bb3a/conbench/api/_docs.py#L16 be enough?

**Comment by jgehrcke** [comment]
Hello! Naive question: Is "poke at live server" safe, especially considering mutating API calls with http methods such as POST, DELETE? This would after all change the state in some database.

I suppose the current state (where only localhost:5000 is listed) is tailored for a development environment where a dev server runs locally and where mutating API calls do not need to be carefully crafted (can ignorantly be sent w/o fear of messing up state).

Interaction of the swagger docs with the live server should maybe be limited to read-only API calls? Happy to learn more about the context.

**Comment by jonkeane** [comment]
> I suppose the current state (where only localhost:5000 is listed) is tailored for a development environment where a dev server runs locally and where mutating API calls do not need to be carefully crafted (can ignorantly be sent w/o fear of messing up state).

When I was running this last, I actually had to change this even during local development to go from localhost to 127.0.0.1. So even in that case it would be nice if the swagger docs protected this.

> Hello! Naive question: Is "poke at live server" safe, especially considering mutating API calls with http methods such as POST, DELETE? This would after all change the state in some database.

> Interaction of the swagger docs with the live server should maybe be limited to read-only API calls? Happy to learn more about the context.

Yeah, we might want to disable trying it out (copying Swagger's terms) for post and put on production servers. It would be nice, if we could, to be able to still have the `GET`s or other non-state changing calls work. And ideally, be able to set this so that one could turn this on for a staging server (we don't (yet) have a staging server for arrow, but we do have one internally).

**Comment by jgehrcke** [comment]
Adding the quick thought that this topic relates strongly to the concept of user privileges. I found in the docs:

> By default, conbench has open read access, so a user account is not required to view results or read from the API.

**Comment by jgehrcke** [comment]
I think that https://github.com/conbench/conbench/pull/435 is a step into the right direction: adding _awareness_ to the app about how HTTP clients are supposed to reach it. I like to think of this as the "intended base URL".

After landing #435 we would still have to set the  new `INTENDED_BASE_URL` config parameter for the specific deployment in order for e.g. https://conbench.ursa.dev/api/docs/ to actually show `https://conbench.ursa.dev/` in the dropdown.

**Comment by jgehrcke** [comment]
I am closing this already, let's revive the discussion when we understand more specific needs.
