### ISSUE TITLE
accept all data for a benchmark result even if one iteration is failed

### ISSUE THREAD

**Issue by ericdill** [conbench/conbench#395]
lets say i did 3 iterations of a benchmark and one (or more) failed. Right now, conbench only supports a 'failed' state which means the data for the other iterations that didn't fail aren't available. the ask here is to accept and store all data and let the downstream viewer of said data decide how to interpret the failure state. This is especially important when some benchmark runs can take a long time (e.g., 30 mins per iteration)

- 0/3 failures: success
- 1/3 and 2/3 failures: partial failure, partial success
- 3/3 failures: total failure

**Comment by jgehrcke** [comment]
I adjusted the title to make this easier to understand based on the title alone.
