### ISSUE TITLE
Add INFO (json), STARTED_AT (datetime), FINISHED_AT (datetime), ERROR (json) fields to RUNS table and POST /runs api to post runs specific info

### ISSUE THREAD

**Issue by ElenaHenderson** [conbench/conbench#398]
I need these fields to keep track of
- runs that could not run at all (e.g., because setup failed) 
- errors preventing a run from executing benchmarks
- when run started
- when run finished

I have been keeping track of this on arrow-bci side but I feel like it is time to add this to Conbench so we can generalize this aspect of running benchmarks.

**Comment by jonkeane** [comment]
I like this. Having the started|finished will also let us show in the conbench UI that a run is pending.

For the `ERROR` field, would we make that instead a string that has a small number of possible valeus (maybe even just a binary?). And then also have an `ERROR_INFO` field where we keep the info about the error?

Then we could filter more easily on the kinds of errors elsewhere

**Comment by ElenaHenderson** [comment]
@jonkeane Yes, I like ERROR (string) and ERROR_INFO (json) fields.

I assume ERROR (string) is like a unique identifier for error, right? 
CI can decide what this unique identifier is when it does POST /runs.

I imagine ERROR (string) = [error message] - [ some stuff that varies from run to run] so we know that some errors are the same.

**Comment by jonkeane** [comment]
I was thinking more of, the string error column is something like one of the following: `["none", "catastrophic", "partial"]`

Where none means all attempted benchmarks are good, catastophic means that no benchmarks completed successfully, and partial is some benchmarks completed, some failed

**Comment by ElenaHenderson** [comment]
Got it. Maybe we should call it ERROR_CATEGORY?

**Comment by jonkeane** [comment]
Sure, or `ERROR_TYPE`?

**Comment by ElenaHenderson** [comment]
ERROR_TYPE sounds good.

**Comment by ElenaHenderson** [comment]
To summarize, RUNS table will have these additional fields:
- INFO (json)
- STARTED_AT (datetime)
- FINISHED_AT (datetime)
- ERROR_TYPE (string)
- ERROR_INFO (json)

**Comment by ElenaHenderson** [comment]
Correction. This fields were added:
```
INFO (json)
FINISHED_TIMESTAMP(datetime)
ERROR_TYPE (string)
ERROR_INFO (json)
```
Did not add CREATED_AT because runs already have TIMESTAMP, which = CREATED_AT.
