### ISSUE TITLE
Move info from info.tags into new benchmark_results.info field because info field for benchmark results is unique to each benchmark_results record

### ISSUE THREAD

**Issue by ElenaHenderson** [conbench/conbench#407]
The meaning of `INFO.TAGS` field changed since it was added a year ago. Now every benchmark result has its own INFO and there is no INFO that is shared between benchmark results.

Our schema should reflect this change in how `INFO.TAGS` is used .

Another reason for making this change is that users want to post a lot of data into `INFO.TAGS` field but since we index on this field, Postgres can't handle large JSONs being indexed and throws `psycopg2.errors.ProgramLimitExceeded: index row size 4360 exceeds btree version 4 maximum 2704 for index "info_index"` errors.

**Comment by jonkeane** [comment]
Are you proposing to have two kinds of additional info:

* One for context (basically the original conception of additional info, how it's used for arrowbenchmarks) this is information about the environment something is built or run in (that shouldn't change how the benchmarks perform, so we mark it as additional, unlike information in context which _do_ expect to have an impact on the benchmarks performance) 
* One for the benchmark (case) that is additional information that is additional information about the specific benchmark that is being run, but that isn't defining the case (which is what the tags do) and like other additional infos, we don't expect the information there to impact performance

**Comment by ElenaHenderson** [comment]
I am not proposing of touching `context` since it is used by history and distribution and is NOT unique to each benchmark results record.
I am proposing to only change how we keep track of `info`, which we sometimes refer as `additional info` which can vary from one benchmark result to another for the same exact benchmark. Since this additional info is not shared between multiple benchmark results and unique to one benchmark results record, we should store it in the same table and should not be treating as something that is separate from benchmark results.

**Comment by jonkeane** [comment]
Yup, Exactly! Sorry my first message might be confusing that first bullet point was what's already there, not touching that, the thing we would add is the second bullet point the per-benchmark additional info

**Comment by jonkeane** [comment]
I'll try and take a stab at this this afternoon

**Comment by jgehrcke** [comment]
https://github.com/conbench/conbench/issues/1426 I think picks up @ElenaHenderson's original intention (as e.g. reflected by the title of this ticket). Might/will do this as part of a larger DB schema change.
