### ISSUE TITLE
Redirect to desired url after login

### ISSUE THREAD

**Issue by mariusvniekerk** [conbench/conbench#411]
When going to a conbench url from a link and not being logged in already you are not redirected to the desired url upon completing the login flow.

**Comment by jgehrcke** [comment]
Quick thoughts: the URL path of entry needs to be passed along all parties contributing to the login flow (three: user, api server, identity provider)

- the server component emitting the 401 response (not authenticated) will redirect to the login URL, adding a query parameter containing the entry path
- in the OAuth2 flow initiation (in the api server) that entry path must be encoded in a state-holding parameter.
- the login callback http request handler must then decode the entry path from the bits it got back from the identity provider, and can then emit an http redirect response

code section to encode the entry path:
https://github.com/conbench/conbench/blob/fdb30f2934481989e981c49837506c0622d6bb3a/conbench/api/_google.py#L26

code section to reconstruct the entry path and to redirect the client to:
https://github.com/conbench/conbench/blob/fdb30f2934481989e981c49837506c0622d6bb3a/conbench/api/auth.py#L81

**Comment by jgehrcke** [comment]
This now works for SSO (not regular login), and only for these views: 
- batches
- benchmarks
- compare
- index
- runs

Closing this for now.

Follow-up work to do, if desired (let's review the need):

- make this work for username/password login
- make this work for other views, too.
