### ISSUE TITLE
Migrate to SQLAlchemy 2.0

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#434]
Once SQLAlchemy 2.0 comes out, remove the ceiling imposed in https://github.com/conbench/conbench/pull/433 and fix any broken tests.

**Comment by jgehrcke** [comment]
(talked today in Conbenchat that this would probably facilitate having better inferred types in our code base -- glad that we have movement on this front :heart:  thank you @austin3dickey! migration guide, if it applies: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html)
