### ISSUE TITLE
devprod: docker-compose tests do not pick up code changes

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#437]
`docker-compose run app pytest -vv conbench/tests` does not reliably pick up code changes to test/app files. Code gets into this test runner via a Docker image build:

https://github.com/conbench/conbench/blob/353f1f9cf7dceb42cd287d8a0035b1ef9259dba5/Dockerfile#L9

docker-compose does not seem to execute that image build upon every `run`. Makes sense. If it were to re-execute the Docker image layer cache would see the update and invalidate the cache layer. Therefore, a quick workaround is to run `docker-compose build app`, i.e. I currently run
```
docker-compose build app && \
  docker-compose run app pytest -k test_create_benchmark_empty_context -vv conbench/tests
```
to quickly iterate on a test. That works, it's however a little inefficient because for example it executes `RUN pip install .` for every test runner invocation.

Better approach would be to mount the code from the host into the container (downside, as always with privileged containers, would be root-created `__pycache__` etc).

Action item: find dockerized test invocation method that is efficient and picks up code changes; document that in the README.

**Comment by austin3dickey** [comment]
For clarity, are you suggesting we mount the code only during local development/testing, and keep the current "ADD" setup for CI and CD?

**Comment by jgehrcke** [comment]
I think that is what I mean, yes :)

**Comment by jgehrcke** [comment]
@sayantikabanik also runs into this challenge when using the containerized workflow. It's important to prioritize addressing this issue here, so that local changes are automatically picked up by the flask app.

Typical approach: mount local checkout into container.

points to consider:
- this must work w/o mounting the checkout into the container (for CI, and for having a stable reference).
- disadvantage of mounting local checkout into container: files written by container processes will for starters be root-owned: 
https://github.com/conbench/conbench/pull/468#discussion_r1036083675
- challenge of docker-compose: mount only conditionally.

**Comment by jgehrcke** [comment]
This has been addressed with the `make run-app-dev` command. 

Also see
https://github.com/conbench/conbench/issues/503
https://github.com/conbench/conbench/pull/546
