### ISSUE TITLE
Coveralls is not performing optimally

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#439]
As discussed in https://github.com/conbench/conbench/pull/438#issuecomment-1318823589, Coveralls has a few issues:
- `conbench/machine_info.py`'s coverage has been falsely "decreasing" on every PR for a long time
- it doesn't display the source when you click through the links
- it treats the `conbench/tests/` directory as source code because it's under `conbench/`, which can artificially inflate the coverage percent

See if we can solve these problems, or else find a new solution.

**Comment by jgehrcke** [comment]
Updated thinking: maybe we want to remove coveralls for now, indeed. The overhead right now is I think not worth it.

**Comment by austin3dickey** [comment]
Shall we repurpose this issue for that? I'm hoping to tackle it in the next month or two. Maybe we can find a good alternative.

**Comment by jgehrcke** [comment]
Also, publishing the coverage report to the external API is a source for transient issues. Seen for example here: https://github.com/conbench/conbench/pull/558#issuecomment-1361688365
