### ISSUE TITLE
DB bulk operations (such as commit backfill): consider using PostgreSQL upserts

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#441]
Motivated by [this loop](https://github.com/conbench/conbench/blob/a797b8a271b7c27b25791e92be2b7eb97af3422a/conbench/entities/commit.py#L228):

```python
    for commit_info in commits_to_try:
    ...
        try:
            commit = Commit.create_github_context(**commit_info)
            backfilled_commits.append(commit)
        except Exception as e:
            if "commit_index" in str(e):
                print(f"Commit {commit_info['sha']} already existed in the database")
            else:
                raise

    return backfilled_commits
```
This issues a database transaction for each loop iteration, and in each iteration we try to handle a key constraint error. This can be done by the database:

> Starting with version 9.5, PostgreSQL allows “upserts” (update or insert) of rows into a table via the ON CONFLICT clause of the INSERT statement. A candidate row will only be inserted if that row does not violate any unique constraints. In the case of a unique constraint violation, a secondary action can occur which can be either “DO UPDATE”, indicating that the data in the target row should be updated, or “DO NOTHING”, which indicates to silently skip this row.

(https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#insert-on-conflict-upsert)

**Comment by austin3dickey** [comment]
I like this idea! I originally wrote it this way to take advantage of the `Commit.create_github_context()` method that already existed, but I don't think there's any reason we couldn't make that method an upsert. It's only used elsewhere when we already know the commit doesn't exist yet.
