### ISSUE TITLE
Add short commit sha to conbench ui table

### ISSUE THREAD

**Issue by boshek** [conbench/conbench#445]
Currently the landing page for the arrow [conbench instance](https://conbench.ursa.dev/) looks like this:

![image](https://user-images.githubusercontent.com/18472598/203152942-3509f726-bc8c-4021-9322-c27f0850eb03.png)

In custom post-processing on conbench data it often useful to reference a sha as one of your grouping variables or column headers - in particular a short sha might be useful. However mapping that back visually to the conbench ui table can be challenging as only the commit message is displayed. It would be nice to have either a new column that displays the short sha _or_  append it to the text of the commit message.

**Comment by jgehrcke** [comment]
Makes sense!

> or append it to the text of the commit message.

I think the `Commit` column is the right place for displaying the _short_ hash (in addition to the commit msg prefix). In a column titled 'Commit' I actually would expect to see the short hash.

Worth discussing: how short should it be? 7, 8, 9, 10 characters? Interesting: https://stackoverflow.com/a/18134919/145400

>  to reference a sha as one of your grouping variables

For stuff like this -- is it important that the complete hash is also available in a column?

**Comment by boshek** [comment]
I think 7 would make sense. One example is GitHub turning this `https://github.com/conbench/conbench/commit/36231130871ce74f82e6cc3481a0a569778b5e4d` into this https://github.com/conbench/conbench/commit/36231130871ce74f82e6cc3481a0a569778b5e4d

> For stuff like this -- is it important that the complete hash is also available in a column?

For the actual grouping 100% but for labelling I'd tend to towards a 7 digit sha linked to the commit (just like the above).
