### ISSUE TITLE
benchmark details: auto-render URL lists as `a href`

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#460]
Picking up a question from @joosthooz -- when a property is a list of strings, then try to auto-render each of these as clickable link. See `grafana_trace_url` example in this screenshot:
![conb_clickable_url](https://user-images.githubusercontent.com/265630/203988455-d05ee238-15d8-4992-8d78-19ae22276f7c.png)

**Comment by jonkeane** [comment]
Thanks for this! We _do_ have some URLizing already added (https://github.com/conbench/conbench/pull/427 was relatively recent). I suspect what's going on is that those string representations of lists need to either be treated differently (there might be a URLize setting to look at embedded strings?) or we should iterate through items like that and treat them as more than just a string of the list representation of them
