### ISSUE TITLE
Track step changes on BenchmarkResults

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#472]
- Add a boolean column to BenchmarkResult called `is_step_change` that tracks whether this BenchmarkResult is sufficiently "different" from previous BenchmarkResults with the same hardware/case/context
- Add a way for humans using the webapp to mark a BenchmarkResult as a step change or not
- Mark step changes on the plots

**Comment by jgehrcke** [comment]
Interesting discussion! Maybe my comment from https://github.com/conbench/conbench/pull/575#issuecomment-1375491063 should better have been placed here. :) Well.
