### ISSUE TITLE
benchalerts: Allow wildcard suppression of alerts

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#475]
## Current plan
When setting up a benchalerts script to run in CI, you may provide string wildcard patterns for various fields like benchmark name, hardware name, tags, etc. If an alert for a specific benchmark result matches one of those string patterns, it will be suppressed.

## Old plan

Ability to mark a Distribution (i.e. a certain case/context/hardware/repo) as "never alert" by storing that info in the DB.
- Add a boolean column to Distribution called no_alerts that tracks whether this Distribution is "weird" enough to justify never alerting on regressions, etc
- Add a way for humans using the webapp to mark a Distribution as worthy of alerts or not
- Never say there was a regression/improvement if no_alerts is True

**Comment by jonkeane** [comment]
I wonder if instead of distributions here, we add it at the benchmarkresult level (for now?)

**Comment by austin3dickey** [comment]
Do you mean: mark a BenchmarkResult as "never alert on any results sharing this case/context/hardware/repo" or "never alert for this result in particular"?

**Comment by jonkeane** [comment]
Part of doing this task will be figuring out if either of those is useful to users and if either of those is feasible and then weighing that to figure out if + when we should do it

**Comment by austin3dickey** [comment]
This might actually be more suited to a `benchalerts` configuration rather than something that permanently lives in the database. I imagine something like this: when setting up a `benchalerts` script to run in CI, you may provide string wildcard patterns for various fields like benchmark name, hardware name, tags, etc. If an alert for a specific benchmark result matches one of those string patterns, it will be suppressed.

**Comment by jonkeane** [comment]
> This might actually be more suited to a benchalerts configuration rather than something that permanently lives in the database. I imagine something like this: when setting up a benchalerts script to run in CI, you may provide string wildcard patterns for various fields like benchmark name, hardware name, tags, etc. If an alert for a specific benchmark result matches one of those string patterns, it will be suppressed.

Yup, totally. We have two levels | areas where we flag these (one in benchalerts and one in the web UI). I'm more than happy to try out some things in benchalerts, see how they feel even if they don't (yet) bubble up into the UI (e.g. having benchalerts _not_ alert for a regression, but the UI still shows it as such) for a little bit while we play around with what works. Eventually we will want to unify the behaviors (which of course is easiest if the code is unified, but that's not the only way!), but getting it in front of people + getting their reactions + iterating on what's useful is the most important part of this, so doing it in one place first, iterating, etc. is the right move

**Comment by austin3dickey** [comment]
Okay, updated the title and description to reflect the new scope. I don't think this would be too hard to do.

**Comment by jonkeane** [comment]
I'm not sure if github keeps the original version of the description forever or what, but we might consider adding that into the new description under a section so it's a bit more obvious when we come back to that what the discussion is all about (since much of the discussion here is getting to the conclusion about benchalerts, it looks funny following that correctly updated new description)

**Comment by austin3dickey** [comment]
Oh good point. You can see the old description, but I don't know how long GitHub keeps it around. I'll add it back.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/16600275/219751998-3ce9763f-2f34-4c21-aead-ec9c7efb907c.png">
