### ISSUE TITLE
config: make CONBENCH_INTENDED_BASE_URL required

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#485]
The coding and debugging effort around the special case of _not_ having CONBENCH_INTENDED_BASE_URL set is getting a little out of hand (in the context of OIDC):

https://github.com/conbench/conbench/pull/469
https://github.com/conbench/conbench/pull/465
https://github.com/conbench/conbench/pull/462
https://github.com/conbench/conbench/pull/457
https://github.com/conbench/conbench/pull/456

I'd love to make this transition now: make `CONBENCH_INTENDED_BASE_URL` be a required configuration setting.

**Comment by jonkeane** [comment]
I'm ok with changing the `CONBENCH_INTENDED_BASE_URL` to be required. I appreciate all the work to make the transition smoother — but agree at this point there's a lot of work going on for not much benefit. 

These kinds of upgrades will also hopefully be easier once we have a slightly more structured release process like you've been talking about (e.g. where we auto deploy to a staging environment on merges to main, but wait for a push button or tag or something for deploys to production).

**Comment by jgehrcke** [comment]
First chunk of work: https://github.com/conbench/conbench/pull/494
Second chunk: https://github.com/conbench/conbench/pull/497

**Comment by jgehrcke** [comment]
This is completed.
