### ISSUE TITLE
Define CPython version recommeded to run Conbench with, use this across tooling

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#501]
The CPython version that we want the Conbench deployment to use is implicitly defined in the `Dockerfile`:

https://github.com/conbench/conbench/blob/ddfb3bdb1a343a89b8f9218d2dad46a61fc4f9ae/Dockerfile#L1

That is, this is CPython 3.8 as of now.

That's also what the deploy utils use to create a container image which is after all used in k8s deployments:

https://github.com/conbench/conbench/blob/ddfb3bdb1a343a89b8f9218d2dad46a61fc4f9ae/.buildkite/utils.sh#L5

This should be carried into the README for those local dev situations where Conbench is run straight on the host. So far the README recommends to derive from system python (3):

```
 python3 -m venv conbench
```

On modern systems this is often newer than Python 3.8.

------

I'd say let's recommend CPython 3.10 (I want to use `functools.cache`, for example, which was introduces in CPython 3.9). And then let's put this into the README, and adjust `Dockerfile` accordingly.

**Comment by austin3dickey** [comment]
+1 on 3.10.

**Comment by jgehrcke** [comment]
Cool, closing this for now.
