### ISSUE TITLE
developer experience: provide make/build targets for most common scenarios

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#503]
For the most common scenarios, introduce a make/build concept and use those command abstractions in the README and also in CI.

From the top of my head, these are interesting workflows that deserve abstraction, so that they can be nicely documented and tested:

- lint codebase
- start app so that it listens on a host's network interface
- run test suite
- re-generate _expected_docs.py
- ...

(we briefly talked about that on Slack today @sayantikabanik -- and then I also re-visited this topic as part of https://github.com/conbench/conbench/issues/496)

**Comment by jgehrcke** [comment]
@sayantikabanik proposed (I think) https://pydoit.org/ -- let's also consider this instead of Make. I started with Make because I am used to it (and the pain it comes along with) -- big upside: available by default in many environments, endless resources out there. Can work just fine.

**Comment by sayantikabanik** [comment]
Some additional thoughts:-

`doit` adds a pythonic tone, which feels easy to reciprocate/expand. Comprises dependency management/task runners: maybe useful in near future.

**Comment by jgehrcke** [comment]
Quick update. As of today I frequently use locally:

- `make tests`
- `make run-app-dev`
- `make lint`
- `make rebuild-expected-api-docs`

Those work reliably for me.

I also rather often do this to run a specific test in the containerized stack:
```
docker compose down --remove-orphans && \
    docker compose build app && \
    docker compose run app \
        pytest -vv -s -x -k test_backfill_default_branch_commits conbench/tests
```

I think we can close this here as 'done', and resort to more fine-grained tickets for further improvements.

**Comment by jgehrcke** [comment]
Quick update. As of today I frequently use locally:

- `make tests`
- `make run-app-dev`
- `make lint`
- `make rebuild-expected-api-docs`

Those work reliably for me.

I also rather often do this to run a specific test in the containerized stack:
```
docker compose down --remove-orphans && \
    docker compose build app && \
    docker compose run app \
        pytest -vv -s -x -k test_backfill_default_branch_commits conbench/tests
```

I think we can close this here as 'done', and resort to more fine-grained tickets for further improvements.
