### ISSUE TITLE
Provide a `make` target for generating a database migration

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#519]
Sometimes, developers need to generate and edit an `alembic` database migration file locally as part of their changes. In order to do this, there needs to be a local running database that's up-to-date in migrations. However, if the file is generated inside a local running container, it won't be picked up by git due to #437. So (perhaps similarly to `make rebuild-expected-api-docs`) it would be nice to have a target that can do this for you using `docker compose`.

**Comment by jgehrcke** [comment]
Yes!

**Comment by jgehrcke** [comment]
recipe:

- run DB in container (background): `docker compose run --detach db`
- have alembic go through all migrations (do not let app create tables): `CREATE_ALL_TABLES=false docker compose run -e CREATE_ALL_TABLES app alembic upgrade head`
- have alembic create a new migration: `CREATE_ALL_TABLES=false docker compose run -e CREATE_ALL_TABLES app alembic revision --autogenerate -m "new"`

to create on host fs:
```
$ CREATE_ALL_TABLES=false docker compose -f docker-compose.yml -f docker-compose.dev.yml run -e CREATE_ALL_TABLES app alembic revision --autogenerate -m "add_bmres_timestamp_index"
```

**Comment by jgehrcke** [comment]
I think we can close this as 'done'.
