### ISSUE TITLE
DeprecationWarning: 'safe_str_cmp' is deprecated

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#53]
- `flask_login/utils.py:63: DeprecationWarning: 'safe_str_cmp' is deprecated and will be removed in Werkzeug 2.1. Use 'hmac.compare_digest' instead.`

- ~`flask_wtf/csrf.py:105: DeprecationWarning: 'safe_str_cmp' is deprecated and will be removed in Werkzeug 2.1. Use 'hmac.compare_digest' instead.`~

**Comment by jgehrcke** [comment]
Closing for now, let's revisit if it makes sense.
