### ISSUE TITLE
populating local conbench with data

### ISSUE THREAD

**Issue by sayantikabanik** [conbench/conbench#531]
The current docker workflow worked flawlessly, was able to run the app.
While trying to update the db with data, running into below error:

Script I am using for data population - `conbench/tests/populate_local_conbench.py`

```shell
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/register/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1012007f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
``` 

A thought: could we integrate the above under makefile?

**Comment by jgehrcke** [comment]
Oh hey! Yeah that's a great suggestion that this flow should be supported by a Make target, and that this should be documented in the README.

So, you did `make run-app`, and then were you able to open `http://127.0.0.1:5000/` in the browser, seeing the Conbench UI? If that's the case then `python -m conbench.tests.populate_local_conbench` executed on your machine should also be able to reach the API via `(host='127.0.0.1', port=5000)`.

**Comment by sayantikabanik** [comment]
I tried again, previously my daemon unexpectedly stopped (now rectified)
this time ran into 02 different issues

```shell
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

After adding a header was able to connect to the API
`session.headers.update({'User-Agent': 'custom_agent'})`

```shell
{"code": 400, "description": {"email": ["Email address already in use."]}, "name": "Bad Request"}
```
Flagged as exception.

Happy to raise a PR, if this sounds like a good fix/probable issue

**Comment by jgehrcke** [comment]
Hey!

> `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Why do we think that this (mainly) was triggered by a bad user agent header? In CI and other environments this works without `session.headers.update({'User-Agent': 'custom_agent'})`.

> `{"code": 400, "description": {"email": ["Email address already in use."]}, "name": "Bad Request"}`

Sounds like this method was run against a database that was already partly populated.

We should set some goalds for `populate_local_conbench.py` -- should this exit indicating when executed repeatedly or should it exit non-zero when it sees that it's _not_ running against a fresh/empty database state?

I'd vote for the latter I think.

Maybe we need another helper that says "wipe DB state". Then the user can do "wipe-db, populate-db" in succession.

**Comment by sayantikabanik** [comment]
> Why do we think that this (mainly) was triggered by a bad user agent header? In CI and other environments this works without `session.headers.update({'User-Agent': 'custom_agent'})`.

Great question, if it's running in CI probably simply a sanity check issue from my end/ too many recurrent hits.

> Maybe we need another helper that says "wipe DB state". Then the user can do "wipe-db, populate-db" in succession.

Maybe two options:
- One to append data to db (thinking loud here: I can be wrong), which can come handy for analytical reasoning requiring bit of historic data.
- Second one "wipe DB state"

**Comment by jgehrcke** [comment]
Landed these two PRs to help with the situation:
https://github.com/conbench/conbench/pull/544
https://github.com/conbench/conbench/pull/545

Let's collect new ideas/issues in new tickets.

**Comment by sayantikabanik** [comment]
> Why do we think that this (mainly) was triggered by a bad user agent header? In CI and other environments this works without `session.headers.update({'User-Agent': 'custom_agent'})`.

For some reason I keep running into this, this vanishes when I update the header.

**Comment by jgehrcke** [comment]
> For some reason I keep running into this, this vanishes when I update the header.

I have looked into and addressed this: https://github.com/conbench/conbench/issues/555
