### ISSUE TITLE
Conbench client > Can methods return objects

### ISSUE THREAD

**Issue by ElenaHenderson** [conbench/conbench#539]
For example, 
if client has a method like this:
```
    def get_runs_for_commit_sha(self, commit_sha: str) -> list[dict]:
        url = f"{self.base_url}/runs/?sha={commit_sha}"
        return self.session.get(url).json()
```
It would be great if it returned a list of Run objects which look like this
```
class Run():
   id: str
   name: str


```

**Comment by jgehrcke** [comment]
Trying to understand. Is this about the Conbench CLI? And "return objects" instead of.. dictionaries?

So, this is basically proposing to build a nice client API abstraction where the most important entities are represented as classes, as far as I understand.

**Comment by jgehrcke** [comment]
Closing this in favor of https://github.com/conbench/conbench/issues/1108.
