### ISSUE TITLE
commit author prominence: rethink?

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#563]
Faces are nice! But maybe the author of a commit does not always have tooo much to do with a benchmark run. Maybe this is a bit of a philosophical question but so far I think the benchmark run itself might be a (slightly) more important entity than a commit, for Conbench UX considerations.

Looking at for example:
![image](https://user-images.githubusercontent.com/265630/209174069-56741511-5aa1-4b53-9f8c-34931d4ef0d8.png)

If we think about users, service accounts, identities in this context: I think it might be more interesting to show in this view _which identity submitted the benchmark results_ than who is the author of the commit.

**Comment by jgehrcke** [comment]
In the meantime we should rename the column title "Author" to "Commit author".

A column titled "Author" next to a column titled "Run" implies that this is the Run author.

**Comment by jonkeane** [comment]
I'm 💯 behind renaming to be more accurate with "Commit author" 

One positive side of having the commit authors on this page is I believe (though we could | should measure this in the fullness of time) that it increases developer engagement + makes it easier for a developer to find which benchmarks correspond to their patches. 

I wonder if there's something we could do with the information hierarchy that would make all of the Commit details more cohesive (and make it clear that all of those are information about the same thing | from the same source) that would make it clearer that one way we think about runs is by the data we get from git.

**Comment by jonkeane** [comment]
> If we think about users, service accounts, identities in this context: I think it might be more interesting to show in this view which identity submitted the benchmark results than who is the author of the commit.

Agreed that having this information in a more standardized way (especially when it varies) would be helpful (but IMO  would be good in addition to the commit details including (commit) author). With our current setups, these are almost always sent to Conbench by a single robot user per conbench instance, so a publisher column there would be a lot of the same. This will become much more important (and in fact critical!) if we have setups that have more arbitrary submission of results.

**Comment by jgehrcke** [comment]
> I'm 100 behind renaming to be more accurate with "Commit author"

Thanks for the feedback!

> makes it easier for a developer to find which benchmarks correspond to their patches.

Right! 

> I wonder if there's something we could do with the information hierarchy that would make all of the Commit details more cohesive (and make it clear that all of those are information about the same thing | from the same source) 

Love this. Thought the same. Commit hash, author, commit msg all are "commit information", could and probably should be shown so that they are visually nicely grouped. For example in the ~same table field, potentially revealing more detail when toggling a 'detail view'.

**Comment by jgehrcke** [comment]
Column title has been changed in #697.

One more item I'd love for us to do before closing this ticket: remove the commit author avatar from the table. (that was a definite thought when opening this ticket, maybe I wasn't really explicit about this above).

**Comment by jonkeane** [comment]
> remove the commit author avatar from the table

Could you expand more on this? I'm definitely not opposed to removing them, but personally I like the avatars there + think they drive a bit of engagement. And they are a welcome not-text element on something that's otherwise a lot of text – maybe there's something else that is a much better non-text element we could or should add that's more relevant to the actual benchmarks? 

Anyway, it's definitely not a requirement that I know of in any way that we keep them (no one asked for them, we have similar info in the author names|handles, etc.) but I've always thought they looked nice.

**Comment by jgehrcke** [comment]
> Could you expand more on this? 

I feel like they were too prominent/big. 

>  personally I like the avatars there + think they drive a bit of engagement

yeah I can see that :)

They are quite a bit smaller now. I think we're good for now. Closing this here as 'done'.
