### ISSUE TITLE
search not yeilding results for certain inputs

### ISSUE THREAD

**Issue by sayantikabanik** [conbench/conbench#564]
*Below I am filtering using the `lang`/language column*

### Bit more insight:
The input "R" didn't fetch any results while other inputs (Python, JavaScript etc) yielded the desired outcome. The instant thought that comes to mind is "maybe single char search is buggy" or maybe not (more digging could help)

https://conbench.ursa.dev/runs/9292568e6e4b4c1882d0564bf8ebc3e7/?search=python

![Screenshot 2022-12-23 at 3 40 34 PM](https://user-images.githubusercontent.com/17350312/209317430-d03ce56d-56c1-4efb-82e8-e6ab9cbf322e.png)

https://conbench.ursa.dev/runs/9292568e6e4b4c1882d0564bf8ebc3e7/?search=R
![Screenshot 2022-12-23 at 3 40 26 PM](https://user-images.githubusercontent.com/17350312/209317690-47bba464-20b0-43d9-bfd7-c40a5636d35b.png)

**Comment by jonkeane** [comment]
~Unfortunately~ _as it turns out_ the single-character search is doing the simplest version of search: returning anything that has that character anywhere in the fields that are searched (you can see in the attached screenshot (I used the link you sent there too) at the bottom you get `Showing 1 to 10 of 277 entries (filtered from 280 total entries)`. So a handful of entries _were_ filtered (the ones unlucky enough to not have an R anywhere in the search fields 😂 )

All of that being said, it's not a fantastic UX to _not_ be able to filter by language (what it looks like you're trying to do here). It would be really fantastic if we could filter by any of the columns in the table (e.g. for the Lang column, let me select any of Javascript, Python, R and then filter accordingly). I'm not familiar enough with the table framework we're using to know if that's as simple as turning on some feature, or if we would need to do something more than that.

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/700357/210087060-0f84f240-0b5f-48b6-938e-f4e84ff49d53.png">

**Comment by sayantikabanik** [comment]
Thanks for the insight here ✅

I am aware of something called a `full body text search` essentially takes all the data indexes and runs the search input to find possible/exact matches. This might be little complex to implement. Shall check if there are any default options available with the template we are using.

**Comment by sayantikabanik** [comment]
As I understand from the resources online, the feature requires the addition of JS method(s) and HTML components for column-wise search.

Overview of the steps:
- Turning off the existing search / or we can have it along with the updated search
- Adding HTML component for columns we would like to add a search feature to
- JS method to update search output based on the column chosen (one column at a time)
