### ISSUE TITLE
Cache less aggressively in `set_z_scores()`

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#567]
Currently in `set_z_scores()`, upon finding a baseline Run for a contender BenchmarkResult, we use that same baseline Run for each subsequent BenchmarkResult sharing the same contender Run. This might be inaccurate if, say, the baseline Run has fewer languages than the contender Run. (This isn't a huge deal because the problematic BenchmarkResults will just have a z-score of 0, but it is unintended behavior.)

See if there's a way to handle that situation (i.e. find the true baseline run of every given BenchmarkResult) without slowing the function down too much (i.e. don't call `benchmark_result.run.get_baseline_run()` on every single iteration of the loop).

One solution might be to figure out all the case/context pairs of the cached baseline runs, and only call `benchmark_result.run.get_baseline_run()` when the contender BenchmarkResult doesn't match one of those pairs.

_Originally posted by @jonkeane in https://github.com/conbench/conbench/pull/507#discussion_r1059462511_

**Comment by jgehrcke** [comment]
Related: https://github.com/conbench/conbench/issues/577
