### ISSUE TITLE
history plot: show raw data points

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#571]
One wants to see where the individual data points are along this 'history' line:

![image](https://user-images.githubusercontent.com/265630/210776250-d6db2822-1ab5-4c27-a198-8876399a37d8.png)

Line + scatter is usually more informative.

Other ideas, while I have them on my mind (independent tickets, ideally):
- add right padding so that the newest data point does not collide with right boundary of plot.
- rework legend to explain better how mean and sigma were built.
- add more date ticks

**Comment by jonkeane** [comment]
Love this. I also think it might be nice to fill in the +/- 5 sd area to make it a little more obvious that that is a range we expect the other values to land (again, this would ideally be a separate ticket, but while we're collecting improvement ideas)

**Comment by jgehrcke** [comment]
https://github.com/bokeh/bokeh/pull/2186

**Comment by jgehrcke** [comment]
https://github.com/conbench/conbench/pull/591 implements some ideas. Specifically:

> Line + scatter is usually more informative.

done

> add right padding so that the newest data point does not collide with right boundary of plot.

done

> rework legend to explain better how mean and sigma were built.

done (important improvement, but still ambiguity left!)

> add more date ticks

done

> fill in the +/- 5 sd area to make it a little more obvious that that is a range we expect the other values to land

not yet done

**Comment by jgehrcke** [comment]
This is done.
