### ISSUE TITLE
duration data samples from repetitions: sort by time (by spec)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#576]
We probably have that fulfilled right now, but I'd love to _specify_ that individual samples should be sorted by order of execution / time. Example:
```
[1.951955, 1.846497, 1.891674]
```
That should mean that the first data point corresponds to the first repetition, the second data point to the second repetition, and so on.

Exact knowledge about meaning of this order is important to understand the impact of things like 'warm up effect'.

**Comment by jonkeane** [comment]
These docs are hard to find as is, but we do have the following:

https://github.com/conbench/conbench/blob/bea8aacb84cd2de3c7e5650400e65ac00efa4d74/conbench/entities/benchmark_result.py#L207

We can (and probably should) change that `should` to `must`. But most importantly: find a way to surface those kinds of details in a more robust way than the swagger schemas that are hard to get to.

**Comment by jgehrcke** [comment]
Lovely, thanks!
