### ISSUE TITLE
Move away from storing a rolling window distribution result in the database

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#577]
Time series analysis / aggregation (such as rolling window analysis) for even many samples is extremely fast to calculate on the fly. 

Let's try to move to a world where there is no need to store these things in the database. 

Of course, if regression detection is based on such analysis then some results of such analysis may need to be stored in the database. But that's a different story.

**Comment by jonkeane** [comment]
This will also come up when we start looking at multiple metrics for benchmarks. As it stands now storing one distribution isn't so bad (though I agree with JP that if we can make that faster by fetching the raw data and aggregating at runtime, we should do that!) but once we start needing to do that for the mean, median, max, and min of durations (and then also the min and max memory consumptions, the mean, median, max, min of through put ....) storing all of that starts to make less sense.
