### ISSUE TITLE
Add JSON column to BenchmarkResult for "why" the result was a step change or outlier

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#581]
>If the expected change is permanent, it could be lovely to enrich the annotation with a free text field where users should explain the reason for the change. This can be powerful also when improving performance over time: get an auto-generated plot that shows how performance improved over time and also _why_.

_Originally posted by @jgehrcke in https://github.com/conbench/conbench/issues/575#issuecomment-1375491063_

**Comment by austin3dickey** [comment]
I'm going to pick this up now. I'm considering replacing the `is_step_change (bool)` column on BenchmarkResult with `change_annotations (json)`, which is intended (but not technically enforced) to contain the keys:
- `begins_permanent_change` (bool)
- `permanent_change_reason` (text)
- `is_outlier` (bool)
- `outlier_reason` (text)
- `exclude_from_distribution` (bool)
- `exclude_from_distribution_reason` (text)
- whatever else we might add in the future

Does this sound reasonable? It will help with #472, #474, #475, and #581 too.

Another option is to add these keys to `optional_benchmark_info` but I think I like the first-class way better?

**Comment by jonkeane** [comment]
Personally, I think we should let this be as free form as possible, and start collecting data before we decide on different categories of changes + what that might mean for the underlying calculations we're making. Even these three categories which do seem totally reasonable: we would need to document what each is intended to mean + what the (different) downstream consequences of each is on the calculations. If we can get away with not needing to prescribe those (and code up things that would link into them), I think that will free us from needing to get them right until we have enough information about how people will use them in actuality (as well as if we even need those distinctions mathematically speaking anyway)

**Comment by austin3dickey** [comment]
That makes sense. I just opened #582 to replace `is_step_change` with this new column. There's no prescription in the new PR about what fields to include. That can come as we figure them out.

**Comment by jonkeane** [comment]
And to be fair + clear I *do* absolutely believe we will need something like this (and probably soon!) I just think we should sequence it as: work through the history project we set out to do with the simplest possible version and then follow on as we gather data about how people are using it with new shades of discontinuities like this.
