### ISSUE TITLE
history endpoint: specify result object schema?

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#589]
I think the object properties of the individual objects returned by the history endpoint are not yet specified, at least not in the object schema in /api/docs as far as I have seen. Maybe we don't want to do this as of now because things are in flux. Just wanted to leave a reminder ticket.

**Comment by jgehrcke** [comment]
In local testing I just got a case where this endpoint returned an object that had just three properties:
```
{
'mean': 19.585377722298556,
'message': 'GH-15205: [R] Fix a parquet-fixture finding in R tests (#15207)',
'timestamp': '2023-01-06T14:25:20'
}
```

I noticed this because I was expecting the `sha` key to be set here, too. It looks like when a commit message is set, a commit hash isn't necessarily set. That's rather wild.

I would expect either complete commit info to be set, or none -- not partial. Maybe that is something that can be enforced in the input validation side of things.

**Comment by austin3dickey** [comment]
@jgehrcke Can you clarify which endpoint you used to get that object? Something like that should never come from `GET /api/history`; that should only return an object that looks like [this](https://github.com/conbench/conbench/blob/0c9adbc8bc19e9aede6d6ffe2f9492e671fbcd07/conbench/entities/history.py#L43-L61).

Your response looks suspiciously like one of these objects instead 🤔 
https://github.com/conbench/conbench/blob/0c9adbc8bc19e9aede6d6ffe2f9492e671fbcd07/conbench/app/_plots.py#L275-L279

**Comment by jgehrcke** [comment]
> Your response looks suspiciously like one of these objects instead

Oh! Thank you so much for thinking this through where I (seemingly) didn't. I forgot for a moment how often we call `_source()` and that it's not always a list of these history objects that we inject.

**Comment by jgehrcke** [comment]
Closing, because this is not relevant anymore.

**Comment by austin3dickey** [comment]
Oh, I still think this would be a nice feature. We document many aspects of the API, but the history endpoint is still not documented.

**Comment by jgehrcke** [comment]
Yes, we should keep working on that. I realize every now and then how this underspecification a lot of costs time when touching code.

**Comment by jgehrcke** [comment]
Closing this as 'done'! This was am important step forward. We should make the next-obvious tweaks to the schema though, making use of new names.
