### ISSUE TITLE
devprod: add more type annotations, do mypy in CI

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#605]
I often jump across places in the code base to figure out the shape and characteristics of the various complex objects and dictionaries passed between code segments. Often confusion remains, and it can become difficult to write robust code with confidence.

Invariants and specification make changing code much easier. Type annotations and CI-driven type checking can and will in my experience pay off, especially in this case here where we can and should re-use the more complex types across the entire code base.

**Comment by austin3dickey** [comment]
+1000!

**Comment by jgehrcke** [comment]
Value will come from having the first-class objects properly typed. We have those defined as SQLAlchemy models today. Without further help, mypy cannot use any of those details to do smart type inference.

When using a project like https://github.com/tiangolo/sqlmodel one can _at the same time_ define objects for SQLAlchemy _and_ pydantic.  

And

> pydantic models work with [mypy](http://mypy-lang.org/) provided you use the annotation-only version of required fields

See https://docs.pydantic.dev/usage/mypy/.

Great questions:

> Following the [SQL (Relational) Databases tutorial](https://fastapi.tiangolo.com/tutorial/sql-databases/), it seems one has to define Pydantic and SQLAlchemy models separately: .... As the number of models grows, this leads to large amounts of duplicate code and attributes. Is there a way to merge these two classes into one, or are there any plans on adding such functionality?

> So can/should Pydantic and SQLAlchemy models be used together? If they are, how is one meant to connect the two together and can this still be done while maintaining some kind of type hierarchy?

The answer seems to be between
- https://github.com/tiangolo/fastapi/issues/214#issuecomment-801318927
- https://github.com/tiangolo/sqlmodel

More good resources:
- https://docs.pydantic.dev/usage/dataclasses/
- https://github.com/dropbox/sqlalchemy-stubs
- https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html

**Comment by jgehrcke** [comment]
Closing this as 'done'. More work to do, but we'are already appreciating the value.
