### ISSUE TITLE
Search by full git commit SHA no longer working?

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#625]
I am nearly positive we used to be able to search for runs in the main conbench list UI by the full Git commit SHA as well as the short one. But that doesn't seem to be the case anymore.

https://conbench.ursa.dev/?search=f3637aca7750f43f7e1766e4495254f98adbe40b should return results, but says there are none however https://conbench.ursa.dev/?search=f3637ac _does_ return results. 

This might have changed when we updated the styling on the commit column. We should figure out how to make it so that full SHAs are useable in search but maintain the nice-looking short SHA we have now.

**Comment by sayantikabanik** [comment]
Woops, probably the hidden col "hash" facilitated the full commit SHA search. 

>We should figure out how to make it so that full SHAs are useable in search but maintain the nice-looking short SHA we have now.

Will take a peek here
