### ISSUE TITLE
ci: main: lint is broken as of black 23.1.0 release

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#652]
black 23.1.0 was released a couple of hours ago. `make lint` in our CI uses moving targets on purpose. 

https://black.readthedocs.io/en/stable/change_log.html 

> This is the first release of 2023, and following our [stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy), it comes with a number of improvements to our stable style, including improvements to empty line handling, removal of redundant parentheses in several contexts, and output that highlights implicitly concatenated strings better.

**Comment by austin3dickey** [comment]
Now that we've been broken by `black`, I can finally stop saying Happy New Year.
