### ISSUE TITLE
_inspect_for_multisample(): unexpected argument: case hit

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#658]
[code](https://github.com/conbench/conbench/blob/1f0ca1828212e158d4487ba1004d9df377307dbd/conbench/app/_plots.py#L296):
```
    # Get number of samples for each benchmark.
    try:
        samplecounts = [len(i["data"]) for i in items]
    except KeyError:
        # TODO: clean up once type checking is tight enough.
        # Likely, the provided `items` for testing here are not strictly of the
        # required shape. It's a programming bug, but do not crash in this
        # case. Return an answer: not multisample (at least not in the way as
        # expected).
        log.warning("_inspect_for_multisample: unexpected argument: %s", items)
        return False, None
```

today I saw in CI log this condition to be hit during populate_local_conbench.py:

```
[230201-13:02:04.552] [11] [conbench.app._plots] WARNING: _inspect_for_multisample: unexpected argument: 
    [{'mean': 24.577452378478558, 'message': 'ARROW-17144: [C++][Gandiva] Add sqrt function (#13656)', 'timestamp': '2023-01-02T13:36:18', 'sha': '1e8ca94fc3682eb97bcf243545dcb282c1aaa0b4', 'benchmark_id': '362b864911c44d618af51698a94c3b39', 'repository': 'https://github.com/apache/arrow'}]
```

It's also happening during the test suite.

This is not a bug, just re-inforcing that this TODO statement is somewhat important.

**Comment by austin3dickey** [comment]
Since I deployed this code to the production environments yesterday, this warning is showing up a lot in the webapp logs. It's a little noisy (but no worse than that).

**Comment by jgehrcke** [comment]
> this warning is showing up a lot in the webapp logs. It's a little noisy (but no worse than that).

ok! If it gets too noisy we can remove that again. I thought the condition is more special than it actually seems to be.

**Comment by jgehrcke** [comment]
Warning is unreachable since we moved to `HistorySample` abstraction as opposed to using those unpredictable dictionaries.

Code needs cleanup now:
https://github.com/conbench/conbench/blob/7c4968e631ecdc064559c86a1174a1353713b700/conbench/app/_plots.py#L370

**Comment by jgehrcke** [comment]
That is, this was taken care of via https://github.com/conbench/conbench/pull/811.
