### ISSUE TITLE
Enabling, Default to PR title for squash merge 

### ISSUE THREAD

**Issue by sayantikabanik** [conbench/conbench#666]
Ah, since there was just one commit the `squash & merge` action didn't pick the PR title instead picked the commit message. The `UI` prefix didn't get reflected.

Nice option here to update this: https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/

_Originally posted by @sayantikabanik in https://github.com/conbench/conbench/issues/665#issuecomment-1415308030_

**Comment by jonkeane** [comment]
I just updated this to Default to PR title + commits in the details (which IMO is a good balance). Let's see if this helps us avoid this generally!
