### ISSUE TITLE
ui: unique value filter per column: drop-down contains empty field, and also null

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#671]
I think the following screenshots show unintended behavior in various ways. Just leaving this here to hopefully save some time.

![Screenshot from 2023-02-04 14-24-38](https://user-images.githubusercontent.com/265630/216770258-4f5ee82f-fa89-425f-b786-ebc855726df4.png)
![Screenshot from 2023-02-04 14-27-28](https://user-images.githubusercontent.com/265630/216770286-7d3a924c-9415-45cb-9e94-a6ad23281f27.png)

Found in current staging environment, `runs/96d6f941f20e456a9d60b68699121084/`

**Comment by jgehrcke** [comment]
@sayantikabanik can you triage this? I don't know from the top of my head what's currently expected, so I'd love your opinion on what's a bug and what not.

**Comment by sayantikabanik** [comment]
Interesting anomaly, thanks for the screenshots taking a peek now

**Comment by sayantikabanik** [comment]
![Screenshot 2023-02-13 at 10 55 30 AM](https://user-images.githubusercontent.com/17350312/218378368-f2ad1e66-5812-4b2a-8487-23eb35b4b85a.png)

The `null` originates from strings entering as str.length = 0 vs string with white-spaces
Both are treated as empty with current regex in place. 

Another point to note is there is no `text` (rather Glyphicons) for error col when there is a message `Has error`
Which in-turn leads to null values.

![Screenshot 2023-02-13 at 11 11 39 AM](https://user-images.githubusercontent.com/17350312/218379764-1b055159-dfbd-4f3a-b8ac-2feb49c9b76e.png)



Possible way forward:
- update the has error `text` with the hyperlink/icon fr drop-down to catch

**Comment by sayantikabanik** [comment]
added a commit under #710 for the error column bug

**Comment by sayantikabanik** [comment]
As for the `null` anomaly, there seems to be empty tags and design inconsistency triggering this behavior.

UPDATE:
Tweaked the logic, hopefully its smooth now
