### ISSUE TITLE
ci: assign-issue-and-pr-author: might fail with gh: Not Found (HTTP 404)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#675]
See https://github.com/conbench/conbench/pull/674#issuecomment-1416803020. Needs some inspection :hammer_and_pick:.

**Comment by jonkeane** [comment]
Weird, it seems that it's working again — I wonder if the fix in the action needed to be on main before it would be picked up on each PR?

**Comment by jgehrcke** [comment]
The error shown in https://github.com/conbench/conbench/pull/674#issuecomment-1416803020 was as far as I understood not as of a missing token, and also as far as I briefly checked not as of an exhausted quota.

It looked to me like an instability with not-so-great debuggability :) But at this point it's not yet worth going deep. Let's see how frequently this happens (if it ever happens again).

**Comment by jonkeane** [comment]
> It looked to me like an instability with not-so-great debuggability :) But at this point it's not yet worth going deep. Let's see how frequently this happens (if it ever happens again).

💯 I've assigned it to myself + I'll keep an eye on it

**Comment by jgehrcke** [comment]
Closing this for now, can re-open if we see this again.
