### ISSUE TITLE
history plot in comparison view: min higher than mean

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#683]
Seen in https://conbench.ursa.dev/compare/benchmarks/a3faf3e6c7f048dab960f24f58618aa0...77aef10139db4f0a8376e1baa93f06b0/:

![image](https://user-images.githubusercontent.com/265630/217008282-c523b59d-75be-48ad-9d76-319c1805aaa0.png)

There are a couple of issues here, but two of them stand out:
- the seemingly _constant_ nature of the mean-over-time is suspicious.
- the min-over-time is greater than the mean-over-time is mathematically unsound.

We should investigate this information flow end-to-end and identify what's happening why.

Need to look at everything, e.g. "Which entity calculates the mean? Is it Conbench or is it the submission tooling?".

**Comment by jonkeane** [comment]
One possible theory for the seeming constant nature (that also could result in the min > mean). It's suspicious that the mean in the plot is at precisely at 0.002 I wonder if we're rounding (or worse, truncating) that value but not the min?

**Comment by jgehrcke** [comment]
> if we're rounding (or worse, truncating) that value but not the min?

We were indeed truncating:
https://github.com/conbench/conbench/blob/833dfa0b29c1207d82fb0951f5327c4e970acbd5/conbench/units.py#L30

Now that this is debugged, it's easy to resolve:
https://github.com/conbench/conbench/pull/1079.
