### ISSUE TITLE
ui: history plot: distribution change button: document how this affects data analysis

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#691]
I think as of today this is what users see:

![Screenshot from 2023-02-07 09-49-30](https://user-images.githubusercontent.com/265630/217198614-6b3c4fc7-f006-47ac-a4a0-06ed4db92ce0.png)

We need to make this more explicit, tangible, easier to understand.

From https://github.com/conbench/conbench/pull/575#issuecomment-1381676700

> I would like when the precise list of consequences is documented / specified in the Conbench UI. Could be something in the lines of "as of today, clicking this button results in a vertical line being shown in the plot above. In the future, we plan to ...".

Then

> @jgehrcke Good call; I forgot to document this. Right now it just adds a vertical line. I will document the full behavior in https://github.com/conbench/conbench/issues/473.

(https://github.com/conbench/conbench/pull/575#issuecomment-1382070096)

**Comment by austin3dickey** [comment]
Oops, thanks for keeping me honest! I'd also like to add the same documentation [here](https://github.com/conbench/conbench/blob/main/conbench/entities/benchmark_result.py#L382).

**Comment by austin3dickey** [comment]
I think we can mark this as done with https://github.com/conbench/conbench/pull/1044 and all the previous work.
