### ISSUE TITLE
ci instability: cb-on-minikube may fail during postgres-operator deployment

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#693]
Seen here: https://github.com/conbench/conbench/pull/692#issuecomment-1420616849
```
Wait for port forwarding to take effect
The command curl --location --silent --output /dev/null http://127.0.0.1:8080/clusters timed out
==== FAILURE: OPERATOR DID NOT START OR PORT FORWARDING DID NOT WORK
If you observe issues with minikube VM not starting/not proceeding, consider deleting the .minikube dir and/or rebooting before re-running the script
Error: Process completed with exit code 1.
```

Went away upon re-run, proving that this is a non-deterministic effect.

Maybe trying longer than 1 minute is a solution: https://github.com/zalando/postgres-operator/blob/933b45aba0d64243368e1ed8619ce1cbfb3e7ac6/run_operator_locally.sh#L34

Maybe _not_ swallowing stderr is of help: https://github.com/zalando/postgres-operator/blob/933b45aba0d64243368e1ed8619ce1cbfb3e7ac6/run_operator_locally.sh#L170

**Comment by jgehrcke** [comment]
@austin3dickey had this twice yesterday. Right?
Depending on the platform this is seemingly way more likely to hit in. Needs tackling.

**Comment by jgehrcke** [comment]
Seen by @alistaire47 here: https://github.com/conbench/conbench/actions/runs/4138141592/jobs/7154181896 but that was before adding the latest improvements on this front.

@austin3dickey I'd really love to see the current state on your machine. Thanks!

**Comment by jgehrcke** [comment]
Just observed this again locally:
```
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
Wait for port forwarding to take effect
The command curl --location --silent --output /dev/null http://127.0.0.1:8080/clusters timed out
==== FAILURE: OPERATOR DID NOT START OR PORT FORWARDING DID NOT WORK
```

Means that https://github.com/conbench/conbench/pull/725 did not help, which was one of two expected outcomes. We've learned that this needs further debugging.

It's entirely possible that the port-forward was never set up properly before going into the curl loop. We wouldn't see a corresponding error as I've pointed out in the initial comment above:

> Maybe not swallowing stderr is of help

**Comment by jgehrcke** [comment]
Submitted this patch: https://github.com/zalando/postgres-operator/pull/2218. Will start jgehrcke/postgres-operator (with the patch branch) for our CI for now.

**Comment by jgehrcke** [comment]
@austin3dickey tried with the last patch, and we got more debug info:
```
Wait for port forwarding to take effect
E0213 12:04:17.469541    3517 portforward.go:407] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod e9f066224446563e71976e0d5027405f6b68a64c73564fa395e9039868661e09, uid : exit status 1: 2023/02/13 18:04:17 socat[3528] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
E0213 12:04:17.469736    3517 portforward.go:233] lost connection to pod
```

As suspected, the port forward setup failed hard, and all the subsequent retrying is pointless.

Need to understand what's special about @austin3dickey's setup here. 

Also, valuable insight from there: I realize that in my patch the retry loop for  the port-forward command itself doesn't help because the process is sent to bg immediately, i.e. exit code inspection doesn't work like that.

Thanks @austin3dickey -- that was helpful.

**Comment by jgehrcke** [comment]
> As suspected, the port forward setup failed hard

Would the `kubectl port-forward ...` command succeed when tried out at a later time against the same k8s cluster? Two outcomes:

1) If it fails immediately again with `Connection refused` ~30 mins after starting the k8s machinery then we know it's a networking configuration thing that cannot be addressed with better waiting/retrying of the port-forward commant itself.

2) If it however succeeds after a while then it's a race condition hitting favorable conditions on Austin's machine, which can be addressed with retrying the command itself.

@austin3dickey reported via Slack that it was (2), yeah! :rocket: No further debugging needed to distinguish those two. 

I will do work to address (2).

**Comment by jgehrcke** [comment]
Update: invested a little more energy into child process management and submitted this refined patch: https://github.com/zalando/postgres-operator/pull/2218

**Comment by austin3dickey** [comment]
🎉 🎉 This patch worked for me!
```
==== FORWARD OPERATOR PORT 8080 TO LOCAL PORT 8080  ====
soon: invoke kubectl port-forward command (attempt 1)
port-forward process is still running
port-forward process is still running
port-forward process is still running
port-forward process is still running
port-forward process is still running
port-forward process is still running
port-forward process is still running
port-forward setup seems successful. leave retry loop.
```
I got almost to the end. Will create one more small issue.

**Comment by jgehrcke** [comment]
> tada tada This patch worked for me!

Thank you! The ironic thing here is that in this specific situation your system did _not_ need the retry loop that I worked on today (it worked upon first attempt, and most likely this is because of an additional 5 second wait time I also introduced in my patch _before_ the first attempt).

**Comment by jgehrcke** [comment]
More persistent retrying helped :rocket: our patch postgres-operator/pull/2218 has been upstreamed.
