### ISSUE TITLE
deploy failure: buildinfo.json: file does not exist

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#697]
As of #678, the `conbench-staging-deploy` Buildkite pipeline is failing when it gets to this line:
https://github.com/conbench/conbench/blob/22f00b779b878009099a0cc01e571087d12b2db8/.buildkite/utils.sh#L5
with the error message
```
Step 13/13 : COPY ./buildinfo.json /buildinfo.json
COPY failed: file not found in build context or excluded by .dockerignore: stat buildinfo.json: file does not exist
```

**Comment by jgehrcke** [comment]
Thank youu! I missed looking at the buildkite pipeline after merge. I really wanted to, but.. :-) forgot.
