### ISSUE TITLE
benchadapt: BenchmarkResult.run_name not defaulted if github set after instantiation

### ISSUE THREAD

**Issue by alistaire47** [conbench/conbench#701]
In `benchadapt.BenchmarkResult`, if `github` is set after instantiation (e.g. via `result_fields_override` in an adapter), `run_name` will not get generated like it would if `github` were provided on instantiation, because the setting code is in `__post_init__()` because it depends on both `run_reason` and `github`.

A solution here would be to also run the defaulting code in the `@_github_property.setter`. 

There are some oddities here around `run_reason`—the default for `run_name` will get whatever it is when the defaulting code is run, even if it is set/changed afterwards—but I don't think this is worth fixing, as what `run_name` is mostly doesn't matter. The `github` situation _is_ worth fixing, though, because the API still requires `run_name` to be set, so this will prevent results from being rejected, even if the `run_name` itself is sometimes `"None: <hash>"`.

**Comment by jgehrcke** [comment]
Confused. From https://github.com/conbench/conbench/issues/607:

> Can run_name currently be `""` or `null`?

> Yes, it could be either.

Error shown by user on Slack:
```
ERROR [2023-02-08 16:32:49,830] Response content: {"code": 400, "description": {"run_name": ["Field may not be null."]}, "name": "Bad Request"}
```

Let's decide on desired API behavior and quickly make sure that API behaves as desired. Then it's easier to reason about client tooling's behavior.

**Comment by austin3dickey** [comment]
Also confused. Maybe I'm misunderstanding what this means:
https://github.com/conbench/conbench/blob/c3e942c1434ae6fb1ffe43ab942e90127b2f3062/conbench/entities/benchmark_result.py#L402-L403

**Comment by austin3dickey** [comment]
Ah, I think we want `allow_none=True` for marshmallow fields where `required=False`. Like we do for `GithubCreate.pr_number`. I suspect that in most cases, for optional fields, we don't mind if they are omitted from the POST payload vs supplied with a value of None.

**Comment by alistaire47** [comment]
Oh! I could change the JSON serialization of `BenchmarkResult` and `BenchmarkRun` so they pop it off if it's `None`
