### ISSUE TITLE
Eagerly delete benchmark output to reduce RAM usage

### ISSUE THREAD

**Issue by westonpace** [conbench/conbench#73]
Benchmark output is kept by conbench in case the `--show-output` option is specified.  If conbench runs multiple iterations then the output for run X is not freed until run X+1 has completed.  This results in excess memory usage for the benchmarks that load large datasets.

We can optimize by deleting the output from the previous run before we run the next run.

**Comment by jgehrcke** [comment]
Closing for now, let's revisit if it makes sense. I think this was taken care of.
