### ISSUE TITLE
makefile: minikube-conbench-url during conbench-on-minikube fails on darwin

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#742]
Discovered this small bug while running `make conbench-on-minikube` on Mac M1. It only seems to affect printing out the last helpful statement, not necessarily the behavior of setting everything up.

At the end, I see this:
```
Grafana UI port-forward:
     run: kubectl --namespace monitoring port-forward svc/grafana 3000
     then open the Grafana UI at: http://localhost:3000
     log in with admin/admin

Conbench UI port-forward:
     run: kubectl port-forward svc/conbench-service 8000:conbench-service-port
     then open the Conbench UI at: http://localhost:8000
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

Based on the emoji, I'm assuming that this command is failing for some reason.
https://github.com/conbench/conbench/blob/c7528b43024e124710f4b7c150e248c1b749fb6b/Makefile#L172

I tried the subshell command by itself in a separate iTerm2 window, and got this, which hung:
```
> minikube --profile mk-conbench service conbench-service --url
http://127.0.0.1:50893
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

**Comment by jgehrcke** [comment]
Some background here:
https://github.com/kubernetes/minikube/issues/13788#issuecomment-1068640594
https://github.com/kubernetes/minikube/issues/14039

On the Linux setup the 'magic' is set up permanently; and the command in question here can immediately return to only display the URL.

On MacOS the required magic is not set up permanently, and the command in question here adds magic (and therefore becomes long-running).

> I tried the subshell command by itself in a separate iTerm2 window, and got this, which hung:

Thanks for trying.

In that case there is little additional value over running `kubectl port-forward svc/conbench-service 8000:conbench-service-port`.

**Comment by jgehrcke** [comment]
This is resolved.
