### ISSUE TITLE
Streamlining API calls for performance (faster&smaller HTTP responses via filters etc)

### ISSUE THREAD

**Issue by boshek** [conbench/conbench#746]
:wave: Thanks for everyone's efforts on conbench. It is really so great. Some thoughts and use patterns of the API.

I am frequently making use of the conbench API (via the [conbenchcoms](https://github.com/conbench/conbenchcoms) R package) to grab run and benchmark data. For static reporting this works well enough since all the data is pulled in a single event and used to generate a static report. However for dynamic reports and dashboards, the current api doesn't have enough flexibility to tailor queries making interactive documents and apps that use conbench data slow to load. 

This is a typical this pattern: 

``` r
tictoc::tic()
library(conbenchcoms)
library(dplyr)

last_1000_runs <- runs()

## Do some manipulations on the recent runs. Here so I'd like only those runs that
## use the ursa-i9-9960x machine
i9_df <- last_1000_runs |> filter(hardware.name == "ursa-i9-9960x")

## query length limits means I have to split this up into separate calls
split_id <- split(i9_df$id, ceiling(seq_along(i9_df$id) / 50))

bench_df <- lapply(split_id, benchmarks) |>
  bind_rows()

## join back with the benchmark info
results_raw <- bench_df %>%
  left_join(i9_df, by = c("run_id" = "id")) |>
  select(id, commit.timestamp, commit.sha, hardware.architecture_name)

tictoc::toc()
#> 117.784 sec elapsed
```

In this pattern I am bringing along so much data that I really don't need which really does slow things down. Waiting 117 seconds for app to grab data isn't going to work. Certainly I could streamline that a bit by using the GitHub api to first tailor the commits I am after etc. But since conbench already has done that it would be nice to make use of what we have already. Ideally I'd be able to have more query patterns than just the id|commit. IIRC you can query on a z-score threshold too. Things like time would be particularly nice but really the more variables we can tune a query with the better. 

In addition to reducing the number of rows returns, it would also be nice to be able to make api calls that reduce the number of columns that are returned. Each column is enormously useful but I don't need them all the time. For example `results_raw` has 105 columns. 

I am also finding that I rarely need benchmarking data without runs data - if we were able to implement the above, then doing that join on the server side would be _amazing_.

**Comment by jgehrcke** [comment]
Thank you so much! I have not given this deeper thought yet, but will so in the future!

Edit: added "(faster&smaller HTTP responses via filters etc)" to the title to reflect what I understood is the proposal here.

**Comment by jgehrcke** [comment]
Next up: extract/define one specific task from here.

**Comment by austin3dickey** [comment]
From my understanding of what @boshek wrote, his query pattern is "get me details of all benchmark results (and their runs/commits/hardware) from the last 1000 runs, filtered to hardware X." But that query pattern is hard to execute with the current state of the HTTP API. Here are some ideas to make that easier.

- add pagination to GET endpoints
- ability to filter `GET /api/benchmarks` by run hardware name
- ability to filter `GET /api/benchmarks` by run time range (I think @boshek implied he'd prefer this over "last 1000 runs")
- return more denormalized data from `GET /api/benchmarks`, including run, commit, and hardware info
- only return certain columns if requested (though I think this would only be useful if it increases performance)

**Comment by alistaire47** [comment]
There are other fields I've sometimes wanted to filter on as well, including but not limited to `tags["name"]` and `context["benchmark_language"]`. That would be a lot simpler to do if they weren't nested in dicts, and the fact that I want to filter by them suggests they should be officially part of the schema, but changing that sounds like a mess

**Comment by boshek** [comment]
@austin3dickey you've got it. Two notes:

> ability to filter GET /api/benchmarks by run time range (I think @boshek implied he'd prefer this over "last 1000 runs")

This is probably the most useful approach because it can be a naive call - that is I don't need to know any commit shas, run ids or anything to get data. Ideally it would be by time range _and_ then by some other filters but a discrete win here could be the time range filter.  

> only return certain columns if requested (though I think this would only be useful if it increases performance)

💯

**Comment by jgehrcke** [comment]
Nice discussion!

> ability to filter GET /api/benchmarks by run time range (I think @boshek implied he'd prefer this over "last 1000 runs")

First-classing the the tail view idea is tracked here: https://github.com/conbench/conbench/issues/789. 

Querying within a time window will require https://github.com/conbench/conbench/issues/790. 

> add pagination to GET endpoints

tracked in https://github.com/conbench/conbench/issues/871

>  Ideally it would be by time range and then by some other filters but a discrete win here could be the time range filter.

Specifically tracked in #872 now.

**Comment by austin3dickey** [comment]
I believe this is complete. The only open request in this thread that hasn't been addressed yet is the additional filters on GET /api/benchmark-results. Will open a new issue for scoping.
