### ISSUE TITLE
ui/ux: a benchmark list view?

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#772]
Currently all of our list views are pretty run centric: You can see a list of runs, and then for a run a list of benchmark(Result)s. But the vast majority of benchmark(Result)s happen over and over (e.g. every run, or at least in at least one run per commit or per hardware). 

Could we make a view that shows a list of benchmarks (possibly with filters for "only show me benchmarks on X hardware" or "only show me benchmarks that were benchmarked for Y commit")? And then allow diving in more deeply there.

One good source of prior art here is ASV: 

Their summary page is an interesting set of plots of history per each benchmark: https://www.astropy.org/astropy-benchmarks/#/
There's also a list view: https://www.astropy.org/astropy-benchmarks/#summarylist?sort=0&dir=asc

I really like the almost sparkline nature of the first view: there are not units or other things to distract (you can click through and get to that, of course). We might even be able to combine these together, have the list view with proper sparklines and a bit more info per-benchmark for that visual look and feel of scanning through and looking for bumps along with some of the details we see in the list view.

And this might be more in the spirit of #330 but their regression view is also benchmark-centric: https://www.astropy.org/astropy-benchmarks/#regressions?sort=3&dir=desc

From a value perspective: a view like this would be really fantastic for people who want a more high-level view (and possibly even a kind of daily-check in to scroll through patterns and see if there's anything funky).

**Comment by jgehrcke** [comment]
It's a really important one, I agree!

A benchmark-centric view is also what I had in mind when I thought about https://github.com/conbench/conbench/issues/560. There I forgot to mention the "list all benchmarks" idea explicitly, but I also imagined a clean overview over all known benchmarks (a listing), which can then be searched/filtered (by e.g. benchmark name, and all the other useful criteria you enumerate here).

This UX concept also helps clarifying the difference between "benchmark" and "benchmark result", if done well.

**Comment by jonkeane** [comment]
_nods_ yeah totally, there's some overlap there — it's possible I should have extended that issue more (when I searched the titles I assumed (wrongly) it was only about searching too. I'm not too worried about ticket structure just yet, I'm sure that these broader idea tickets will get broken down into more concrete tickets as we start working on them

**Comment by jgehrcke** [comment]
After making big leaps forward (in particular https://github.com/conbench/conbench/pull/1086 and https://github.com/conbench/conbench/pull/1085), I am closing this here as 'done'. Let's create more precise follow-up tasks.
More ideas also here: https://github.com/conbench/conbench/issues/1154
