### ISSUE TITLE
benchconnect: Set client logging to DEBUG

### ISSUE THREAD

**Issue by alistaire47** [conbench/conbench#775]
When posting results from arrowbench via benchconnect in abci: https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/99#issuecomment-1443401328 it's become obvious that it would be helpful to see JSON payloads in the logs (like the previous systems there did). The logging for this is already set up in benchclients, but at the DEBUG level (since in some cases the number of calls can be really enormous, particularly for microbenchmarks).

The simplest way to fix this is to change the benchclients logging level in benchconnect. This could be set behind a positive or negative flag (`--log` or `--no-log` or `--log-level=DEBUG` or whatever) if necessary, but for now I think we could just set it and add a flag later if necessary.

**Comment by austin3dickey** [comment]
-vvvv
