### ISSUE TITLE
k8s specs: review conbench service clusterip vs nodeport

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#782]
We currently use NodePort:
https://github.com/conbench/conbench/blob/faea929851065967bbf650f090db846ff2efecc9/deploy.yml#L59

I don't think in our EKS deployments there is a way to access the nodes directly from the Internet.

I think ClusterIP might be more appropriate for our use case (simpler, more explicit that the service with LB is _the_ way to access the API).

> NodePort services expose pods internally the same way a ClusterIP service does. In addition, a NodePort service allows external clients to access pods via network ports opened on the Kubernetes nodes. [...] In practice, I haven't seen NodePort services used much in production systems.

https://octopus.com/blog/difference-clusterip-nodeport-loadbalancer-kubernetes

This is an important consideration when trying to have _common_ code between minikube and EKS/GKE deployments.

**Comment by jgehrcke** [comment]
AWS ALB in `instance` mode would require `NotePort`: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type -- but it looks like we use `ip` mode (maybe/hopefully for sticky sessions).

**Comment by austin3dickey** [comment]
This may be completely unaffected by this decision, but for what it's worth, I often use a connection string of the form `postgresql://user:pwd@aws_host:5432/conbench_prod` to connect directly to the database that backs https://conbench.ursa.dev/ . I can access it from the public internet, and it has saved me a lot of time debugging. I don't have an informed opinion on this ticket except that I'd like to still be able to have direct access to a deployed Conbench database for debugging purposes.

**Comment by jgehrcke** [comment]
> I often use a connection string of the form postgresql://user:pwd@aws_host:5432/conbench_prod to connect directly to the database that backs

Ah! :) Yeah, that should be unaffected, because the database isn't _in_ the k8s cluster anyway, but it's a managed AWS service.

**Comment by austin3dickey** [comment]
oooh that clarifies things! Thank you!

**Comment by jgehrcke** [comment]
> AWS ALB in instance mode would require NotePort: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type -- but it looks like we use ip mode (maybe/hopefully for sticky sessions).

this was a misconception. I found the actual reason, and documented it here: https://github.com/conbench/conbench/blob/054b63ae05c4b4666ce9ae7bdeeb4a9b2649b841/k8s/conbench-service.yml#L15

Closing this here as 'done' -- it's now understood that the exact setup we're using is pretty much ALB-driven which goes _straight_ to the nodes (I think, surpassing the k8s service layer -- which is kindof stupid but OK).
