### ISSUE TITLE
stddev: set to NaN instead of 0 when not applicable

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#802]
Here, when the standard deviation is not calculated as of too-little-datapoints, we set it to 0:
https://github.com/conbench/conbench/blob/aa95b6d52ff6cb6697b7ab8d04c43d6cf3612860/conbench/entities/benchmark_result.py#L95

I think we should set it to NaN instead, to properly distinguish it from zero-ish stddevs.

Note: it's mathematically sound to calculate a standard deviation for a sample size of 2 -- but in practice we may only want to do so given a larger sample size.

**Comment by jonkeane** [comment]
Yeah, agreed, we should use `NaN` here if we can

**Comment by jgehrcke** [comment]
> Thanks for the feedback! I'd say let's build "calculate these statistics only if three or more samples have been provided" and then adjust consumers where necessary.

https://github.com/conbench/conbench/pull/811#discussion_r1129144143

**Comment by jgehrcke** [comment]
This was done in https://github.com/conbench/conbench/pull/1127.
