### ISSUE TITLE
benchadapt: consistently use stdlib logging (do not mix stdout, stderr -- bad message time order)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#805]
follow-up from #804.

> It's a good idea to not mix stdout/stderr for the app's log output because then the relative timing between messages sometimes becomes unclear (when querying logs from a log aggregator).

one problem is here: https://github.com/conbench/conbench/blob/aa95b6d52ff6cb6697b7ab8d04c43d6cf3612860/benchadapt/python/benchadapt/adapters/_adapter.py#L177

**Comment by alistaire47** [comment]
Ah yeah, I think that ended up as prints because logging was going weird somewhere. Really all that should get moved into benchclients directly and the logging integrated with that logging.

**Comment by jgehrcke** [comment]
> Ah yeah, I think that ended up as prints because logging was going weird somewhere.

Would love to understand more about what went weird where :)

Well, the problem is not necessarily the `print()` itself, but the fact that we write to `stdout` instead of `stderr`. Each stream is independently buffered, so exactly how they interleave is unpredictable, messing with relative order of messages.

One could also write to `stderr` when not using `logging`: `sys.stdout.write()` or `print(..., file=sys.stderr)`.

As far as I understand, `benchadapt` is a Python _library_. We still do not have that term in its README (I would love so, it's the canonical description, if that's what it is). As a Python library, one can sanely use `logging` when one does not modify the so-called root logger. That's what `logging.basicConfig()` is good for. I'll try this out.

**Comment by jgehrcke** [comment]
I think we can close this as 'done'
