### ISSUE TITLE
POST benchmark result: status code 500 response as of duplicate key value violates unique constraint "commit_index"

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#809]
follow-up from #804.

```
[2023-03-04 05:32:02,666] ERROR in app: Exception on /api/benchmarks/ [POST]
...
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "commit_index"
...
DETAIL:  Key (sha, repository)=(6b6cdaf7dcd03779193b8891349cdaa8d9fc56f4, https://github.com/<redacted>) already exists.
```

**Comment by jgehrcke** [comment]
more context:
```
File "/app/conbench/api/benchmarks.py", line 186, in post
benchmark_result = BenchmarkResult.create(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/conbench/entities/benchmark_result.py", line 168, in create
Run.create(
File "/app/conbench/entities/run.py", line 98, in create
commit = Commit.create_github_context(sha, repository, gh_commit_dict)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/conbench/entities/commit.py", line 176, in create_github_context
return Commit.create(
^^^^^^^^^^^^^^
File "/app/conbench/entities/_entity.py", line 93, in create
```

![image](https://user-images.githubusercontent.com/265630/223394448-eb526c3b-e037-4b94-8846-d59591858dea.png)

It's so hard to properly copy/paste from the datadog log viewer

**Comment by jgehrcke** [comment]
Will need to go back to specification, but it seems like we simply want to silently ignore when the commit is already in the database. It's a bit surprising that we don't do that so far. Maybe we introduced this as a regression, recently? Let's cover this with tests.

**Comment by jonkeane** [comment]
Yeah, if I'm reading this code correctly (which it doesn't look too unobvious, honestly!) line 81+83 should catch if the commit already exists in the DB and then skip over trying to create a new one, but clearly that didn't work here.


https://github.com/conbench/conbench/blob/408cba4db5ac914212b0be9cfd1bd0ceeccc7ff0/conbench/entities/run.py#L80-L113

**Comment by jgehrcke** [comment]
> line 81+83 should catch if the commit already exists in the DB and then skip over trying to create a new one

Ah, a typical check-then-try race condition :)

To be addressed conceptually with the EAFP paradigm (easier to ask for forgiveness than permission).

Between checking-if-it-exists and trying-to-create the state might have changed. So it's better to try-to-create while expecting the conflict.

Amplified because a lot of time can pass between the check and the creation, as of GitHub HTTP API interaction being done between both.

**Comment by jgehrcke** [comment]
Should be resolved via https://github.com/conbench/conbench/pull/816.
