### ISSUE TITLE
db schema: Commit object: require hash and repository specifier?

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#817]
I see that we have code that may create a Commit object in the database that for example has no commit hash set, but a repository specifier: 

https://github.com/conbench/conbench/blob/408cba4db5ac914212b0be9cfd1bd0ceeccc7ff0/conbench/entities/run.py#L110

```python

            elif sha or repository:
                commit = Commit.create_unknown_context(sha, repository)
            else:
                commit = Commit.create_no_context()
```

Let's simplify here if possible, and impose constraints.

**Comment by jgehrcke** [comment]
Update: the `sha` and `repository` columns are `NotNull()`-wrapped: 
https://github.com/conbench/conbench/blob/408cba4db5ac914212b0be9cfd1bd0ceeccc7ff0/conbench/entities/commit.py#L34

IIUC that means that the situation I described above cannot happen (that a Commit gets inserted into the DB specifying only one of both).

In the `GitHubCreate` schema both are also required, so the `elif sha or repository` implies that both are set.

**Comment by jgehrcke** [comment]
Turns out we _do_ allow for zero-length string in the commit hash, when the repository is set. See https://github.com/conbench/conbench/pull/816#issuecomment-1458629359.

Quoting @jonkeane:

> The original motivation for the looseness here was to also allow us to store results on other softwares (some where we might not have a specific hash that we know we're running)

Yes in this case we should not create a `Commit` object associated with the benchmark result I think.

**Comment by jgehrcke** [comment]
There is a test today that confirms that inserting a Commit object with empty string hash (only repo specifier) works: https://github.com/conbench/conbench/blob/020aabc67baed285dfb3ea0d179839bf3d8d7a67/conbench/tests/api/test_benchmarks.py#L818

Let's review this.

**Comment by jgehrcke** [comment]
This relates to https://github.com/conbench/conbench/issues/814. Both discussions will resolve once we have a clearer picture about intent.

**Comment by jonkeane** [comment]
I did a bit of git blame, and https://github.com/conbench/conbench/pull/147 is the source of that test. Unfortunately there's not much (well any!) description in the PR. But judging by the date + what I remember from around that time, what I said above is the source (we wanted to store arbitrary other results where we (might not) know the commit info). 

Like I mentioned in https://github.com/conbench/conbench/pull/816#issuecomment-1458629359, this was probably a bit _too_ forward thinking ultimately. We thought we would do much more of it, and in the past 1.5 years, we really haven't yet. If | when we do, I'm increasingly convinced that we will want to have a separate construct for these benchmarks to reference for their software under test (something like "externalBenchmarkableSoftware"). 

And ^^^ being the case, IMO we should make this restrictive again (require commit, possibly also require timestamp for #814 , but I have dug a bit less over there TBF), and we will solve the external software thing a different way entirely (when we get to it)

**Comment by jgehrcke** [comment]
Did an increment into the right direction I think in https://github.com/conbench/conbench/pull/889.

**Comment by jgehrcke** [comment]
https://github.com/conbench/conbench/issues/1095 is an outfall of this 'unclarity'.

**Comment by austin3dickey** [comment]
Yes, this is done.

https://github.com/conbench/conbench/blob/1f141414edefc721408e723cb5d978ad8e88dfe0/conbench/entities/commit.py#L276C2-L277
