### ISSUE TITLE
docs: Swagger isn't surfacing the docs in the way we need to.

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#819]
We have lots of details in our marshmallow-based API fields which bubble up into swagger (which is great!) but the way that swagger displays them (especially for the various object schemas at the bottom) makes it unlikely folks will find what they are looking for. 

What can we do to improve this?

**Comment by jgehrcke** [comment]
Is this about information that is currently not at all visible in the `api/docs` UI or (only) difficult to see?

Edit: judging by https://github.com/conbench/conbench/issues/818#issuecomment-1458468884 this is about info that's already there; I should have had another look! :)

But yeah, in the future I think we should have a nicer way to expose the schemas.

**Comment by jonkeane** [comment]
Yeah, it's _there_ but generally hidden behind (multiple!) 🔽 s. 

The other thing I personally find more frustrating than it should be: you can't deep-link into those schemas. So if I wanted to share with you details about the data fields, I need to send the main URL and tell you to click all the places 😦 

These might be easily solvable with a different swagger theme (if that's a thing — I haven't looked too much). Though it's not _totally_ off that those object schemas get lower priority than we want in most API docs like this. So maybe that's an indication swagger isn't good for us here?

**Comment by jgehrcke** [comment]
>  you can't deep-link into those schemas. So if I wanted to share with you details about the data fields, I need to send the main URL and tell you to click all the places frowning

Oh yes, that's an important one!

**Comment by alistaire47** [comment]
I've used [redoc](https://github.com/Redocly/redoc) since it comes with fastapi, and it gives schemas higher priority: https://redocly.github.io/redoc/#tag/pet/operation/addPet I think it should mostly just work on the same openapi metadata as swagger, though I haven't tried

**Comment by jgehrcke** [comment]
Closing this as 'done' for now, now that we have a redoc-based presentation. We have a lot of work to do on this front, but we should try to track specific goals with specific tickets.
