### ISSUE TITLE
Settle on name (for now) for "rolling window z-score" method

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#830]
Follow-up from https://github.com/conbench/conbench/pull/811#issuecomment-1461999137.

I would love to have a recognizable term that we can use _consistently_ across code, docs, discussion, UI. Need a name that we can use within the team to make sure we talk about a definite thing. Need a name to be able to communicate with users.

It's more important to achieve **consistency** than to find the perfect name (the name can change over time!).

In code I started using `zscorestats`, but that is not ideal. In GitHub issues I was trying to express myself with complicated and inconsistent sentences:

> z-score-based method that considers the distribution of results within "recent history".

> we largely discussed this in the context of the z-score-recent-history regression detection method.

> Recent history z-score method

Within the team, we do not have an easy way to talk about the same thing.

We need a call sign for this, a name that we can use in meetings, on Slack, in github issues, in the UI, in docs.

**Comment by jgehrcke** [comment]
I notice that I liked to use "recent history" because based on what I understood so far the "last 100 commits" is a way to say "look at history, but certainly not all of it, just at the recent history". And I liked to add "z score" because of the brand recognition.

But when I think about the fundamental aspects of this method and what we probably _can_ change within it without having to think about it as an entirely new method, then right now I like the following direction:

- "rolling window z-score" method.
- In code, we could nicely use `rolling_window_zscore`

What do we think about "standard score" instead of z-score? Based on my current understanding, "z-score" is more precise than "standard score", so "z-score" is probably better.

**Comment by austin3dickey** [comment]
I hadn't heard of "standard score" before and agree that "z-score" is probably better. I like `rolling_window_zscore`.

**Comment by jgehrcke** [comment]
@jonkeane would love your feedback here!

**Comment by jonkeane** [comment]
I've been ruminating on this for a while, and nothing is striking me as a perfect solution. Something that came to me just now is a slight variation on what you have there `rolling_lookback_zscore` very similar to window, but _slightly_ less specified about what that window looks like (and slightly _more specified that it's in the past, ultimately that's kind of obvious when you think about it for half a second, but it would be nice to have the incorporated in the name).

That being said, it still feels a little bit more clunky than I would like. But I haven't come up with a winner that's shorter (in words or syllables!) so maybe we should go with that and see if it lands well. 

As a side note I agree with all of what y'all say about the standard score thing. It's actually a nice general name, but we lose the branding we already have (and it doesn't have any flavor of lookback which I think we _do_ want)

**Comment by jgehrcke** [comment]
Thanks, @jonkeane I think I really do like the refinement from "window" to "lookback"!

**Comment by jonkeane** [comment]
And actually, now that I'm looking at it again, what if we got rid of the `rolling` there and made it just `lookback_zscore`. It again makes it a little bit more ambiguous, _but_ that ambiguity is in the part of the calculation we are still considering to possibly change (i.e. using a fix window, versus "all time" with a decay, etc.). We can (and should) document the stat of the window for now, but for the name it might be good to use only `lookback_zscore`

**Comment by jgehrcke** [comment]
Agree that "rolling" does not convey additional important/useful/correct information.

Lovely. What I really like about this discussion is an effect I have experienced before: coming up with good names is totally possible, and it usually takes multiple people and a number of iterations. Collaboration and iteration :rocket:

In code, `lookback_zscore` is perfect. In text, what do we perfer? 

> The z-score lookback method

or

> The lookback z-score method

?

I think the latter (your last proposal) might be more correct logically, but the former might flow better (read more smoothly). I think correctness should win, but I am open to both.

**Comment by austin3dickey** [comment]
I think "the lookback z-score method" flows fine, and has the benefit of being consistent with the code version.

**Comment by jgehrcke** [comment]
We can close this as 'done'. :)
