### ISSUE TITLE
Run view: what is Info?

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#837]
In one of our environments I see

![image](https://user-images.githubusercontent.com/265630/224373843-535ed6f3-b842-411e-8a5d-fdd682ff2556.png)

Viewing `Info` on `Run` was surprising. Because:
- I got used to us supporting _implicit_ Run creation based on properties in the `BenchmarkResult` schema. That schema does not document anything like "run info". It only documents per-benchmark-result `info` and `optional_benchnmark_info`.
- when a `Run` is created as part of benchmark result submission, then the `info` DB column is not populated: https://github.com/conbench/conbench/blob/fbf5a6ce898532d44327e3ac961f5abb852843bc/conbench/entities/benchmark_result.py#L213 (which makes sense, as a user cannot provide that kind of data).

But yes, we _also_ allow for explicit Run creation, prior to submitting benchmark results (this is against the "one way to ..." philosophy). That method allows for submitting `info`:
https://github.com/conbench/conbench/blob/fbf5a6ce898532d44327e3ac961f5abb852843bc/conbench/entities/run.py#L447

And then we also allow for updating a `Run` -- here, an API client can probably also provide `info`.

 `info` is documented as `Run's metadata` which is little:
![image](https://user-images.githubusercontent.com/265630/224377210-2268b1c6-4a68-41f4-8d39-19d1dd5d68c0.png)

- Discuss: do we need two ways to create a Run?
- If we have to provide two methods for Run creation, they should be entirely symmetric.
- We should improve the API specification, explain what `Run.info` should be used for.
- The Run view in the UI should show a tooltip, providing help.

**Comment by alistaire47** [comment]
Eventually I'd love to get to the point that all submissions explicitly post a Run and they never get created from results so we can strip off those fields from the result schema, but most of the ways we're submitting results right now don't manually create a run yet. But I dislike having those fields on the result, as it's unclear what should happen if they differ between results on the same run.

**Comment by austin3dickey** [comment]
Having two ways to create a Run has always been in service of "make it as easy as possible to post results," and we know that goal was achieved _because_ everyone posting results chose to go the "easy" way. But I agree that taking away that flexibility for the sake of reducing confusion would be overall beneficial. With tools like `benchadapt`, the "hard" way will be much easier. It would be nice to ensure our CI processes are using those tools before we made a big change like removing implicit run creation.

**Comment by alistaire47** [comment]
> With tools like `benchadapt`, the "hard" way will be much easier. It would be nice to ensure our CI processes are using those tools before we made a big change like removing implicit run creation.

Yeah, in theory benchadapt or benchconnect make manual run creation and management easy. 

But we're not handling this well most anywhere. arrow-benchmarks-ci treats a buildkite run on one machine as a single run but lets each benchmark submit its own results, so opening/closing the run would have to happen from a different level than submission, which seems likely to go wrong. Probably each runner should have its own run regardless of buildkite; the arrowbench implementation moves this way. All of this would be dependent on moving off of the legacy runner, though, so making this prettier could be quite a lot of otherwise low-priority work.

**Comment by jgehrcke** [comment]
> Eventually I'd love to get to the point that all submissions explicitly post a Run and they never get created from results so we can strip off those fields from the result schema

Thanks for adding your opinion! As this discussion is so important and has popped up in various issues/PRs, I have created a separate ticket where we can try to connect the dots over time: https://github.com/conbench/conbench/issues/863

**Comment by austin3dickey** [comment]
No longer an issue. A run has tags, and it's clearly specified that the client is in charge of ensuring those tags are consistent among results with the same run_id.
