### ISSUE TITLE
timeseries fingerprint: use this to define comparability (re-think term "tags" and "case" -- generic label set, with fingerprint being hash thereof)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#862]
Borrowing some terms and concepts from the Observability space, enriched with own ideas.

A benchmark might be uniquely identified by a labelset (collection of key-value pairs). That is what we call case/context, I think.

In code, the hash of that labelset can be called "fingerprint" (as Prometheus does [here](https://github.com/prometheus/common/blob/66b493f42b757378fbad83e42b0ed441d425a17b/model/labelset.go#L142)). We also perform hashing on the context k/v pair set. Strong conceptual analogy.

In text, "fingerprint" can be used as a nice, recognizable term for "a unique labelset". For Conbench documentation and UI/UX it might make sense to use the term "fingerprint" as much as possible to explain what e.g. data points shown in a history plot have in common.

Architecturally, this perspective might give us important clues!  In the Prometheus ecosystem, kind of everything related to data storage and data querying is centered around those label sets. We may want to take inspiration from there. Everything is optimized for dynamic time series querying (an important part of the query is the user-given labelset filter).

(this is just a collection of ideas I wanted to keep note of, not yet convinced about everything in here, let's see where this leads)

**Comment by jonkeane** [comment]
I do very much like the idea | use of the term fingerprint here. And it could help as a nice bundler for all of the things that come together (tags + context and since context + hardware). And then we can document that in detail and use the term fingerprint to go from there.

**Comment by jgehrcke** [comment]
I like the term "timeseries fingerprint". However, regardless of the name, the underlying concept is one of the most foundational ones in what we do. Questions came up. So, let's dive into the concept.

We have implicitly used the concept all the time.

We started using the term "timeseries fingerprint" here: https://github.com/conbench/conbench/blob/b03b1ffa0716098143ac0cbe354aa9169205a275/conbench/entities/history.py#L191

We will make more use of it in a DB schema iteration in the context of https://github.com/conbench/conbench/issues/1227.

What is it? "timeseries fingerprint"  is
- a grouping construct.
- a formalization of the 'comparability' question.
- a precise string identifier, mainly meant consumption by machines, but also for humans.

We (try hard to) group benchmark results by **comparability**. The timeseries fingerprint is an attempt to give each group (timeseries) a precise (unique!) and short-ish name (string identifier).

Examples for usage: that identifier can be used for
- efficiently querying the database (implementation detail)
- labeling a plot or building a filename (when precision, unambiguity, and reasonable shortness) is needed

That identifier is built from all aspects that we care about to **achieve comparability**, and it precisely represents one specific group of benchmark results. 

Think: the identifier can be used to _define_ comparability between any two benchmark results.

Definition (a few examples):

- Two benchmark results are directly comparable when their timeseries fingerprint matches.
- Likewise, two benchmark results are not comparable when their timeseries fingerprint does not match.
- Two benchmark results can be meaningfully plotted / analyzed in a timeseries when their timeseries fingerprint matches :)

And now the magic: a timeseries (group of results) can be efficiently queried from the database by simply asking for all results with a specific timeseries fingerprint. (sorting them by 'time' is part of that or not).

The fact that we have not made use of that clear, simple concept so far has incurred great cost, is one of the reasons for fundamental API slowness and weaknesses.

This concept must be first-classed in code and thinking and communication because then we have it easier, much easier.

Naturally, this concept pops up in our code base. It has to. That is, we have so far implicitly tried to do something like that! But because we never identified this properly we have ended up with
- unclear naming
- inconsistent ingredients
- various slightly different string representations (not precise, not necessarily unique, not short)
- inefficient database schema / query methods

Examples for 'the same thing' that we didn't build as the same thing:
- https://github.com/conbench/conbench/blob/b03b1ffa0716098143ac0cbe354aa9169205a275/conbench/types.py#L11
- https://github.com/conbench/conbench/blob/b03b1ffa0716098143ac0cbe354aa9169205a275/conbench/api/compare.py#L455

I probably repeat myself. Still: regardless of the name/terminology, the 'timeseries fingerprint' is a concept intrinsic to what we're doing. Not identifying and using the concept has a cost (which we suffered from already).

It's critical to align on the concept. The name is not so important.

**Comment by alistaire47** [comment]
> The fact that we have not made use of that clear, simple concept so far has incurred great cost, is one of the reasons for fundamental API slowness and weaknesses.

We've arguably had the idea previously; it's what defines `/api/history`. But explicitly naming that idea is new, and important for seeing its reflection in code. Which is your main point, I think; clarifying naming will help us streamline code.

One consideration on this front Jon was pushing for and I know Sam would like is the ability for what's in a timeseries fingerprint [TSF] used for querying to be user-defined, e.g. pay attention to these tags but ignore others. I suspect the answer here might be "go find all the relevant TSFs and combine the results", but I still think it's worth thinking about because that highlights we need robust TSF discoverability in our API structure if that's what we want users to use to query. Or if that's not what we want users to query with, some thought about how we get from what's supplied to a TSF/TSFs. Currently with the history endpoint that's just a result ID, for better and worse.

**Comment by austin3dickey** [comment]
I love everything you said, @jgehrcke. Additions:

- Each benchmark result has exactly one fingerprint. It can't have more than one, and it can't have zero. That means each benchmark result is directly comparable to exactly one set of benchmark results (including itself), which is mutually exclusive from all other benchmark results not in that set. This is an assumption that makes coding easier and will lead to all the benefits you've enumerated.
- A feature request we've heard from Conbench users is that we should still let users compare two benchmark results that don't share the same fingerprint—but with a loud, clear warning.

>e.g. pay attention to these tags but ignore others

I think you're proposing, @alistaire47, that a benchmark result might have more than one fingerprint (possibly an uncountable number depending on how an API consumer might want to define fingerprint). I like the user-facing concept of flexible querying, but in implementation, I think we should treat this as a separate concept than the fingerprint. Conbench should have an opinion about the 1 fingerprint each benchmark result has. And if a user wants to query for all results that, say, share a certain context tag, regardless of the other elements that go into the fingerprint, we'll find a different way to execute that query.

**Comment by alistaire47** [comment]
> > e.g. pay attention to these tags but ignore others
> 
> I think you're proposing, @alistaire47, that a benchmark result might have more than one fingerprint (possibly an uncountable number depending on how an API consumer might want to define fingerprint). I like the user-facing concept of flexible querying, but in implementation, I think we should treat this as a separate concept than the fingerprint. Conbench should have an opinion about the 1 fingerprint each benchmark result has. And if a user wants to query for all results that, say, share a certain context tag, regardless of the other elements that go into the fingerprint, we'll find a different way to execute that query.

Oh I'm in total agreement that a result should have exactly one fingerprint. I was suggesting we need a good way to query fingerprints, and maybe merge their timeseries in some contexts, though we can leave the merging to users. Or if we allow editing as I suggested in https://github.com/conbench/conbench/pull/1425#discussion_r1291529189 the issue largely goes away because results can be fixed to have the same fingerprint when they should. Theoretically a user could still want to compare against meaningfully different fingerprints, but that's a much less common case than metadata changing for reasons.

**Comment by boshek** [comment]
+1 to what @alistaire47 said and I think there is lots of merit to what he is saying for an approach. I _love_ the idea of a fingerprint for these things. If conbench did this for me it would provide a degree of certainty and provide an easier path to leverage history. I think we need to provide a nice path that extends beyond this:

> Two benchmark results can be meaningfully plotted / analyzed in a timeseries when their timeseries fingerprint matches :)

to

> go find all the relevant TSFs and combine the results

Folks will _always_ want to compare different benchmarks. Experimentation where you change one tag/hardware/whatever and then compare those will be a regular workflow. And those same folks often (i expect) will want to bypass the UI entirely and just pull this from the API hence Ed's suggestion of discoverability in the API. Thanks for the additional explanations. This approach sounds like it has lots of merits. 

I will say that `timeseries` still does not land with me. IIUC correctly, I think something like `history_fingerprint` might be more descriptive.

**Comment by jgehrcke** [comment]
> Folks will always want to compare different benchmarks.

**Comment by jgehrcke** [comment]
> Folks will always want to compare different benchmarks.

Agree. Just want to clarify my mental model about this. There's a clear progression here; first we want to have a decent way to query for a fixed/known fingerprint representing a static label set (hash/fingerprint is index in DB). That's what we have with smarter implementation. Think: API basically does not change.

Second step, let's treat it separate:  the ability to construct dynamic timeseries query using a user-given combination of key/value pairs. I have commented above that the Observability/Prometheus ecosystem has always had a solution for that; was optimized for that from the start:

> Everything is optimized for dynamic time series querying (an important part of the query is the user-given labelset filter).

This kind of work would clearly enrich the API with super convenient features, but it's a different beast. Maybe for achieving that we in fact will have to / want to resort to using a database from the Observability ecosystem that is optimized for this specific use case.

That is, I agree with what Austin wrote:

> I like the user-facing concept of flexible querying, but in implementation, I think we should treat this as a separate concept than the fingerprint.

About @austin3dickey "Additions: ..." -- ack, great, thank you!

**Comment by austin3dickey** [comment]
Maybe `control_group_fingerprint` would be a good name, tying this concept to the fact that the comparability of results relates strongly to the experimental setup of the benchmarks? Or `control_fingerprint` would be shorter but a bit more ambiguous.

**Comment by alistaire47** [comment]
> Maybe `control_group_fingerprint` would be a good name, tying this concept to the fact that the comparability of results relates strongly to the experimental setup of the benchmarks? Or `control_fingerprint` would be shorter but a bit more ambiguous.

I'm a bit confused by "control"...as in a control group relative to a treatment group? But it's not really that. `history_fingerprint` or something like that would make more sense to me if we want to specify what timeseries.

**Comment by austin3dickey** [comment]
I was thinking "in this group of results we control for these N variables" but you're right that there's another meaning there.

**Comment by alistaire47** [comment]
Oh I see, [control variables](https://en.wikipedia.org/wiki/Control_variable), i.e. the other independent variables beyond the code. It's apt now that I understand the reference

**Comment by austin3dickey** [comment]
mm, yeah, maybe `control_vars_fingerprint`? Naming is hard.

**Comment by boshek** [comment]
+1 for `history_fingerprint` or `histroy_signature` though I certainly don't mind `control_vars_fingerprint` either.

**Comment by austin3dickey** [comment]
Done in #1463!
