### ISSUE TITLE
review and resolve the challenging topic of implicit Run creation

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#863]
In #628 I tried to shed light on implicit Run creation. Also see the API spec update and discussion in https://github.com/conbench/conbench/pull/628#discussion_r1088728679 where I tried to find arguments for why things have been built the way they are.

Lovely discussion emerged. That discussion popped up again in various places, e.g. in https://github.com/conbench/conbench/issues/837 where @alistaire47 wrote

> Eventually I'd love to get to the point that all submissions explicitly post a Run and they never get created from results so we can strip off those fields from the result schema

We need to figure out what we want and why, and then build accordingly.

@austin3dickey wrote

>  It would be nice to ensure our CI processes are using those tools before we made a big change like removing implicit run creation

Of course this will be important. It's a good idea to first define a specific way how things would look like ideally, forgetting for a moment about the existing environments. With an ideal, specific setup in mind the question of migrating environments is more productive to think through. With the right abstractions I think this will be ~easy.

**Comment by austin3dickey** [comment]
Implicit Run creation no longer happens.
