### ISSUE TITLE
discuss: consistency of Commit between BenchmarkResult and Run (and other properties)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#864]
This relates to 
https://github.com/conbench/conbench/issues/863.

The schema for benchmark result submission has the optional(?) `github` property. This has the required `commit` property, which is supposed to contain a commit hash. (currently documented as "The 40-character commit SHA of the repo being benchmarked")

As of implicit Run creation an important question pops up: do all benchmark results within a run _really_ have a specific commit in common? Which entity enforces that today?

The UI makes it look so, because it suggests a one-to-one mapping between Run and Commit:

![image](https://user-images.githubusercontent.com/265630/224985020-ae2bfe8f-af92-46eb-a5d8-94627c607666.png)

What does the code say?

First benchmark result for non-existing Run adds _their_ opinion about Commit to Run by doing `"github": data.pop("github", None),` here:
https://github.com/conbench/conbench/blob/f951788d3e6f64231dd5462c241cc39e1bea67e7/conbench/entities/benchmark_result.py#L218

But if the `Run` already exists, there does not seem to be a confirmation/validation.

I believe: we should be strict about what benchmark results within a Run must have in common, and reject adding a benchmark to a run when it doesn't comply.

**Comment by alistaire47** [comment]
Yeah, I ran into this issue when writing benchconnect—what if the metadata on the result you're submitting doesn't correspond to the open run? I added some validation:

https://github.com/conbench/conbench/blob/67cbe18fe7674a065f08e72d10ea38a966952f3a/benchconnect/benchconnect/_submit.py#L28-L36

which has subsequently stopped me from submitting a lot of poorly-arranged data.

> But if the `Run` already exists, there does not seem to be a confirmation/validation.

Right, I believe presently the API just ignores all those fields (`run_name`, `run_reason`, `github_info`, etc.) if `run_id` already corresponds to a `Run`. Agreed, rejecting the result if the run metadata doesn't match would be better.

**Comment by austin3dickey** [comment]
Just to be pedantic:

>do all benchmark results within a run really have a specific commit in common?

From the database's point of view, yes, all benchmark results with the same `run_id` have the same `commit_id`. Those database relationships are both strictly many-to-one. There is a lot of existing code that relies on this property. This is unlike the batch_id discussion (#880) where there is no database enforcement of relationship.

As you both said, this is accomplished by completely ignoring any run/commit details in the payload of `POST /api/benchmarks` if a run with the given `run_id` already exists in the database. This behavior is [documented](https://github.com/conbench/conbench/blob/main/conbench/entities/benchmark_result.py#L490) in a [few](https://github.com/conbench/conbench/blob/main/benchadapt/python/benchadapt/result.py#L112-L113) user-facing places. This _could_ lead to a BenchmarkResult row where the benchmark was run on one commit but successfully submitted to a Conbench run on a different commit, through user error. (This wouldn't happen if the user is using a recent version of our client tooling, as Ed said.)

I agree that we should instead reject those payloads if the run/commit details don't match! That will result in no future user error. 

But looking backwards, I would pedantically call all existing data "consistent." We gave the user two ways to specify commit of a benchmark result—existing `run_id` and `github_info.commit`—and documented that if the two ways disagree, we will prefer the commit implied by the existing `run_id`. That is, we shouldn't need to do a migration to "fix" old data, or make any design choices today that rely on inconsistencies. (I know you already know that; I just wanted to be sure we're all on the same page. 🙂)

**Comment by jgehrcke** [comment]
Thanks for the detailed response @austin3dickey.

> we should instead reject those payloads if the run/commit details don't match! That will result in no future user error.

Let's do that. The relationship between commit information and benchmark results is too important to not be strict. I created https://github.com/conbench/conbench/issues/932 for tracking that.

> We gave the user two ways to specify commit of a benchmark result—existing run_id and github_info.commit—and documented that if the two ways disagree, we will prefer the commit implied by the existing run_id.

Yes! But we only started documenting that this year, when we tried to shed light on how code is behaving: https://github.com/conbench/conbench/pull/628.

> we shouldn't need to do a migration to "fix" old data, or make any design choices today that rely on inconsistencies

agree

**Comment by austin3dickey** [comment]
no runs, no problem!
