### ISSUE TITLE
ui: benchmark result view: breadcrumb: hierarchy not properly used

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#865]
![image](https://user-images.githubusercontent.com/265630/224996374-dccc48d9-b59c-4919-895c-80e57226795e.png)

`Benchmark / 3ba0f122cb974472b507882c09c1a3f0` are the same level, the separator is misleading.

**Comment by jgehrcke** [comment]
When changing this, also change this to "benchmark result"

**Comment by jgehrcke** [comment]
A little better now, referring to "benchmark result", and showing the ID: 
![image](https://user-images.githubusercontent.com/265630/225242429-f28886d4-a3cb-4570-bf81-880d89f71e00.png)

We can shorten the ID (for display), and _also_ make this a link.

**Comment by jonkeane** [comment]
> We can shorten the ID (for display), and also make this a link.

Also what about the form: 

> Run / Batch / Benchmark result: `2b6c486`

+ `: ` and then like you say shortening the ID + linking

**Comment by jgehrcke** [comment]
> Also what about the form:

I like that! yes!

**Comment by jgehrcke** [comment]
Improved a bit in #954; current look:
![image](https://user-images.githubusercontent.com/265630/228216979-3522282d-0770-47af-a315-ef8a1a29e509.png)

Closing this as 'done' for now.
