### ISSUE TITLE
commit: URL construction based on user-given data should not generally lower()

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#887]
Side discussion from #818. 

> we might want to continue storing URLs lowercase

This is about https://github.com/conbench/conbench/blob/782abc9e2c1147866eb251acb612192d8fded5d3/conbench/entities/commit.py#L265.

Hmm. Danger! :fire:  I mean, I don't know about the fallout, but URLs in general are case-sensitive.

github.com documentation says

> The repository you're trying to fetch must exist on GitHub.com, **and the URL is case-sensitive**.

(https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors)

> Typos happen, and repository names are case-sensitive. If you try to clone git@github.com:user/repo.git, but the repository is really named User/Repo you will receive this error.
https://stackoverflow.com/q/6650488/145400

> GitHub recently made a change that now allows mixed-case repository names.

(from https://metacpan.org/pod/App::GitHub::FindRepository)

There is value in auto-correcting user-given input _if_ we know the correction is, well, correct :)

**Comment by austin3dickey** [comment]
Yeah, it probably makes sense not to `.lower()` the repository identifier. I think this exists in the codebase as a hack from when we lowercased a private repository and chose not to migrate the database. We probably didn't realize that repo names are case-sensitive when interacting with GitHub.

**Comment by jgehrcke** [comment]
btw, for the record to quickly show what this is about:
```
>>> repository_to_url('peter/PaN')
'https://github.com/peter/pan'
```

**Comment by jgehrcke** [comment]
This was resolved via https://github.com/conbench/conbench/pull/1134.
