### ISSUE TITLE
benchalerts: add more to PR comments

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#919]
Right now we show the first 20 lines of the body of the report in the PR comment. But we're missing the title of the report and the link to Conbench, both of which would add value.

**Comment by austin3dickey** [comment]
In general the PR comments could use a little love. Some thoughts:
- They should provide the minimum information necessary to have users either click through to the report or ignore
- The content should be different from the full report because the audience is necessarily different. This might add a bit of code complexity but it's worth it
- No big headings. If anything, collapsible blocks.
- Link to all the runs in the webapp individually
- Clarify the "lookback z-score" language we've decided on in #830

**Comment by jonkeane** [comment]
> No big headings. If anything, collapsible blocks.

IMO the collapsible blocks probably are reserved for the markdown report. We should let the content be the judge here (i.e. there might be exceptions to this), but if we're putting content in a collapsible block in the comment we should think if that's really necessary in the comment or if it's something that's better off only in the report.

> Link to all the runs in the webapp individually

❤️ I imagine this is also (probably) in the report, and (again, probably) not also in the comment?

**Comment by joosthooz** [comment]
Hi, I've noticed that the new PR comment no longer contains a link directly to the conbench run. Instead, there is a link to the github action, that in turns contains a link to conbench. That link should fill in the search bar, but for me that is not working. So currently it is a lot of work to go from a PR comment to the conbench run page!

**Comment by austin3dickey** [comment]
>IMO the collapsible blocks probably are reserved for the markdown report.

Yes, thinking about it more, this is probably for the best.

>I imagine this is also (probably) in the report, and (again, probably) not also in the comment?

>I've noticed that the new PR comment no longer contains a link directly to the conbench run.

Thanks for your input @joosthooz! It sounds like at least one user does want direct links to Conbench webapp runs in the PR comment. I think this makes sense, as different comment readers can then choose whether to look at the summarized, actionable report, or do their own analysis by diving into the webapp data. Happy to hear other opinions though. Maybe it's a better UX to funnel everyone through the report first.

**Comment by jonkeane** [comment]
>  Maybe it's a better UX to funnel everyone through the report first.

IMO we should try this first. We might need to bubble more up into the comment later. But I would love love love for that comment to be a teaser to get folks to look at the report where we can go wild with hierarchy + nitty gritty details
