### ISSUE TITLE
benchalerts: stop hitting /api/compare/runs

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#953]
In `benchalerts`, the pattern for hitting the Conbench API to look for lookback z-score regressions on a contender run (as codified [here](https://github.com/conbench/conbench/blob/34e9be27221389d5dec5adce8e2df95c993f1818/benchalerts/benchalerts/pipeline_steps/conbench.py#L86)) is the following:
- GET `/api/runs/{contender_run_id}`
- if baseline, GET `/api/compare/runs/{baseline_run_id}...{contender_run_id}/?threshold_z=100`
- scan through results for `"z_regression": True`
- if no baseline, you're out of luck

This pattern might make sense for a "point" regression analysis that needs to compare the contender run directly to the baseline run, but it doesn't make sense for the lookback z-score analysis, because the lookback z-score analysis uses much more data than just the baseline run (and can survive without it).

I propose a better pattern:
- GET `/api/benchmarks/?run_id={contender_run_id}`
- scan through results for `["stats"]["z_regression"]: True`

This has fewer API calls, less server load (it's calculating z-scores less often), and works even in weird baseline-run edge cases that might have failed with our current method.

One part of this is adding the ability to supply `threshold_z` to the `/api/benchmarks` endpoint as a query parameter too.

**Comment by jonkeane** [comment]
We might want to re-think what the comparison endpoints are useful for and if that's still satisfying the features we need to power with them.

**Comment by austin3dickey** [comment]
I misunderstood the purpose of the /api/compare endpoints when writing this issue. Through upcoming changes to those endpoints, we'll make this workflow better.

**Comment by austin3dickey** [comment]
Related:
- #1029
- #955
- #992
- #1030
- #1027
- #1031
- #384
