### ISSUE TITLE
make tests: upon db connect: SCRAM authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#957]
@alistaire47 saw

```
/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py:122: in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E   sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```
during
```
conbench/db.py:128: in create_all
    Base.metadata.create_all(engine)
```
As of the nature of the error (permanent), the retry loop is of course not resolving this.

What's a little puzzling about this error is that it suggests that we use different versions of libpq across people/machines; but as of our containerized workflow we try to prevent exactly this. The error is probably a red herring.

Btw, we pip-install https://pypi.org/project/psycopg2-binary/ in the app's container image, and that bundles a pre-built version of libpq.

**Comment by jgehrcke** [comment]
@alistaire47 did this ever work? :) It could be that we broke this only last week for you:
- https://github.com/conbench/conbench/pull/921 (landed last week) has affected which specific binary would be installed on AArch64 (your machine)
- https://github.com/conbench/conbench/pull/930 (also landed last week) might have affected the authentication handshake

**Comment by jgehrcke** [comment]
OK, problem understood. Pre-built binaries come with problems :). 

https://github.com/psycopg/psycopg2/issues/1360 has all the details.

@alistaire47 I think in your case pip installed this:

https://files.pythonhosted.org/packages/b9/97/61d8794442b50456f3263ca263af9fde2a1fde93811b74fe0c5a9519f6ca/psycopg2_binary-2.9.5-cp311-cp311-manylinux_2_24_aarch64.whl, Uploaded Oct 25, 2022.

This was built in an environment where libpq 9.6.23 was present. Many people are running into this problem with `psycopg2-binary` because for the AArch64 manylinux they linked against rather old binaries. This is still the last release from them on PyPI, so we have to (and also want to) build from source.

**Comment by alistaire47** [comment]
> @alistaire47 did this ever work? :) It could be that we broke this only last week for you:
> 
> - https://github.com/conbench/conbench/pull/921 (landed last week) has affected which specific binary would be installed on AArch64 (your machine)
> - https://github.com/conbench/conbench/pull/930 (also landed last week) might have affected the authentication handshake

Yes, it worked previously. I'm not sure exactly the last time I ran it—definitely at some point last week, but may have been Tuesday? I noticed the failure after updating macOS and restarting.

**Comment by jgehrcke** [comment]
@alistaire47 did https://github.com/conbench/conbench/pull/958 fix this on your system?

**Comment by alistaire47** [comment]
Yes, thank you!
