### ISSUE TITLE
api: baseline runs should be on the default branch

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#992]
Currently when we `get_baseline_run()` it usually chooses the parent commit, even if the parent commit was a PR commit. But the baseline run should always be on the default branch for effective pointwise analysis.

Looking through the code, I suspect we can simplify many queries upon making this change. That's also because of the changes we've made to the rolling z-score calculation code.

**Comment by jgehrcke** [comment]
> baseline runs should be on the default branch

I like the clarity of that statement! That's great, towards effectively communicating internally and externally was expected/correct behavior is.

I wonder if/why the definition of "baseline run" might have shifted recently. Did we always have the correct definition, and the code deviated accidentally? Were we not entirely clear about the definition in our heads, and in writing?

I would appreciate if you can add your perspective to this @austin3dickey 

A discussion like this helps developing a paper trail around decision-making, which is invaluable for deriving and iterating on design and knowledge.

**Comment by jonkeane** [comment]
💯 on doing a bit of a retro to figure out what happened (also happy to do something in person if that helps). #384 might be relevant here as well

**Comment by austin3dickey** [comment]
I dove into the blame and found that https://github.com/conbench/conbench/pull/507 is what originally caused this "regression." Regression is in quotation marks because before that PR, we were enforcing that baseline runs should always be on the default branch by filtering the query to `Run.reason == "commit"`. 🙃 That's not the same as being on the default branch, but practically it was, back in those days.

Notably -- in that PR, I [didn't have to](https://github.com/conbench/conbench/pull/507/files#diff-bcc9f9347c1c76d32472bac607097505072ee0d0c0b1c87135e007e040fee2b3) change any tests that were directly related to ensuring baselines were always on the default branch. So I must have misunderstood the intention when doing that PR, and no tests failed, so I thought everything was fine.

I'll definitely add a test in this patch!

**Comment by jonkeane** [comment]
Thanks for all of that details + candid assessment of what happened
